### PR TITLE
Changed all context value of all try-catch implementations

### PR DESCRIPTION
**Pull request by gabiwassan**
Hi team,
This PR modifies in all try catch implementations, the way to obtain the context for our orchestrator, adding the name of the class + the name of the method in which the error was caught.

### CODE REVIEW

**Review by Machi3mfl — APPROVED** [review]
CR ✅

**Review by Desvelao — APPROVED** [review]
**review**
Code Review ✅

**Comment by Desvelao** [comment]
**review**
Code Review ✅

**Review by eze9252 — APPROVED** [review]
Code Review Ok!

**Pull request merged**
