### PR TITLE
Fixed code editor component height in logs layout (Management and Settings)

### LINKED ISSUE #4206: Management and Settings -> logs page: the load button appears half hidden
**Describe the solution you'd like**
When navigating with safari browser to Management -> Logs, the default style shows the page as follows: 

image

We need to redesign this so:
* the load more events button appears at the end of the page, and it is visible, without scrolling 
* if we load more events, the button does not move. Instead, the text area showing the logs increases its contents, and the scrollbar takes care of the log's movement.
* in a responsive environment, we use the same behavior

### PR DESCRIPTION
**Pull request by Machi3mfl**
Hi Team,
This PR fixes a Management > Logs layout to ensure that the "Load more logs" show correctly.

Closes #4206

### CODE REVIEW

**Review by Desvelao — CHANGES_REQUESTED** [review]
**nitpick**: add an entry to the changelog

**Review by yenienserrano — APPROVED** [review]
Test: ✔️ 
CR: ✔️ 

2560x1440

image (8)

**Comment by chantal-kelm** [comment]
Test: heavy_check_mark
CR: heavy_check_mark

**Review by AlexRuiz7 — APPROVED** [review]
LGTM!

**Pull request merged**
