### PR TITLE
Feature Disable Wazuh by roles

### LINKED ISSUE #3164: Hide/Block the Wazuh app depending by role or config
**Describe the solution you'd like**
Certain environments need to exclude the Wazuh app access for certain roles, spaces, or tenants. 
The proper approach should be to find a way to deny access through Elastic (ODFE / X-Pack) policies.

**Describe alternatives you've considered**
An alternative way could be through the Wazuh app (code) with some policies or configs to deny the access.

**Additional context**
The solution should take care of the indices, patterns, templates, etc, too.

### PR DESCRIPTION
**Pull request by asteriscos**
Hi team!

this adds the feature to set roles in `wazuh.yml` to disable Wazuh App.

Closes #3164 

Test case:

- Add disabled role entry in `wazuh.yml`
```
disabled_roles: 
   - wazuh_disabled
```
image

- Make sure the logged in user has the role assigned
image

- Wazuh should be disabled when logging in or refreshing the browser
image

image

### CODE REVIEW

**Comment by pablomarga** [comment]
When I add the disabled rol I still see the Wazuh app in the sidebar but I can't access to it.
Screenshot_20210510_113503
Screenshot_20210510_113517

**Review by CPAlejandro — COMMENTED** [review]
When entering kibana, if Wazuh appears in the bar, but when I click and enter, it does not allow me to access the app, showing me the following:
image
And also it does not appear in the bar, but once entered the Wazuh app:
image

**Comment by frankeros** [comment]
> The configuration should also appear in Settings section. Also when a role is disabled and you try to enabled a refresh is needed

It should be proposed because it involves a change in the UI

**Review by frankeros — APPROVED** [review]
It looks fine for a first iteration. I'm merging now.

**Pull request merged**
