### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by yenienserrano**
### Description

This pull request updates some of the project's dependencies and deletes an unused one.
 
### Issues Resolved

- #5059 

### Evidence

image
image

### Test

Check that the app is still working as intended

### Check List
- [x] All tests pass
  - [x] `yarn test:jest`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [x] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Review by Tostti — DISMISSED** [review]
CR ✔️
Test ✔️ - Application works normally, no errors related to this found in console

LGTM

**Comment by AlexRuiz7** [comment]
Needs a Changelog entry.

**Review by chantal-kelm — DISMISSED** [review]
CR: ✅ 
TEST: ✅ 

Evidence:

image

image

image

image

image

image

image

image

image

**Review by chantal-kelm — APPROVED** [review]
CR: ✅ 
TEST: ✅ 

Evidence:

image

image

image

image

image

image

image

image

image

**Review by Tostti — APPROVED** [review]

**Comment by Desvelao** [comment]
If we removed the `pug-loader` dependency, then we should have removed the used files (pug templates `*.pug`)

**Comment by Desvelao** [comment]
`json5` is subdependency of  `pug-loader` dependency. The `pug-loader` dependency was removed. There is no related entry in the changelog. 

I think the entry in the changelog related to updating the `json5` doesn't make sense because this was not updated.

**Pull request merged**
