### PR TITLE
Fix invalid xml config generation

### PR DESCRIPTION
**Pull request by jbiset**
## Description
This pull fixes invalid XML config generation on management configuration.
We have decided to remove the display of the JSON and XML formats of the Management configurations in the modal that appears when one of the configurations is selected, for example, Log Collection. This is decided based on the fact that they are features that do not present use cases and, in particular, the XML format generates an invalid XML configuration.
Since this is a functionality provided through the HOC pattern, the best solution is to remove the corresponding tabs and views, leaving only the default one and access to the corresponding help links.
The component that adds the tabs for the selection of the JSON and XML formats is WzConfigurationsSettingsTabSelector. By removing this functionality it no longer makes sense to continue using WzConfigurationsSettingsTabSelector. For this reason, the most appropriate thing would be to remove this component and modify those components that use it, avoiding unnecessary nesting of components.
In the issue is the research process documented
 
## Issues Resolved
- #5617 

## Evidence
The following screenshots show how the configuration screens were left without access to the JSON and XML format tabs.

0-management-configurations

<details>
<summary>
Main configurations
</summary>

1-global-configuration

2-cluster

3-registration-service

</details>

<details>
<summary>
Alerts and output management
</summary>

4-alerts

5-integrations

</details>

<details>
<summary>
Auditing and policy monitoring
</summary>

6-policy-monitoring

7-open-scap

8-cis-cat

</details>

<details>
<summary>
System threats and incident response
</summary>

9-vulnerabilities

10-osquery

11-inventory-data

12-active-response

13-commands

14-docker-listener

</details>

<details>
<summary>
Log data analysis
</summary>

15-log-collection

16-integrity-monitoring

17-agentless

</details>

<details>
<summary>
Cloud security monitoring
</summary>

18-amazon-s3

19-azure-logs

20-google-cloud-pub-sub

21-github

22-office-365

</details>

### Tests executed

<details>
<summary>
The corresponding tests have been updated and executed:
</summary>

- alerts_test

Alerts_test

- api-auth-tab_test

api-auth-tab_test

- general-tab_test

general-tab_test

- log-collection_test

log-collection_test

- office365_test

office365_test

- subscription-tab_test

subscription-tab_test

</details>

## TEST

Legend:
:black_circle:: none
:green_circle:: pass
:yellow_circle:: warning
:red_circle:: fail
:white_circle:: not applicable

### UI
Check that the accesses to the JSON and XML formats are not shown in the following configuration management screens and their internal tabs.

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| Global configuration |  :black_circle: | :black_circle: | :black_circle: |
| Cluster |  :black_circle: | :black_circle: | :black_circle: |
| Registration Service |  :black_circle: | :black_circle: | :black_circle: |
| Alerts |  :black_circle: | :black_circle: | :black_circle: |
| Integrations |  :black_circle: | :black_circle: | :black_circle: |
| Policy monitoring |  :black_circle: | :black_circle: | :black_circle: |
| OpenSCAP |  :black_circle: | :black_circle: | :black_circle: |
| CIS-CAT |  :black_circle: | :black_circle: | :black_circle: |
| Vulnerabilities |  :black_circle: | :black_circle: | :black_circle: |
| Osquery |  :black_circle: | :black_circle: | :black_circle: |
| Inventory data |  :black_circle: | :black_circle: | :black_circle: |
| Active Response |  :black_circle: | :black_circle: | :black_circle: |
| Commands |  :black_circle: | :black_circle: | :black_circle: |
| Docker listener |  :black_circle: | :black_circle: | :black_circle: |
| Log collection |  :black_circle: | :black_circle: | :black_circle: |
| Integrity monitoring |  :black_circle: | :black_circle: | :black_circle: |
| Agentless |  :black_circle: | :black_circle: | :black_circle: |
| Amazon S3 |  :black_circle: | :black_circle: | :black_circle: |
| Azure Logs |  :black_circle: | :black_circle: | :black_circle: |
| Google Cloud Pub/Sub |  :black_circle: | :black_circle: | :black_circle: |
| GitHub |  :black_circle: | :black_circle: | :black_circle: |
| Office 365 |  :black_circle: | :black_circle: | :black_circle: |

### Test
Run the folowing test:
| Test | Pass | 
| --- |  --- | 
| alerts_test |  :black_circle: | 
| api-auth-tab_test |  :black_circle: | 
| general-tab_test |  :black_circle: | 
| log-collection_test |  :black_circle: | 
| office365_test |  :black_circle: | 
| subscription-tab_test |  :black_circle: | 

### Check List
- [ ] All tests pass
  - [ ] `yarn test:jest`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [x] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Comment by Machi3mfl** [comment]
## TEST (In progress :hourglass_flowing_sand:)

Legend:
:black_circle:: none
:green_circle:: pass
:yellow_circle:: warning
:red_circle:: fail
:white_circle:: not applicable

### UI
Check that the accesses to the JSON and XML formats are not shown in the following configuration management screens and their internal tabs.

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| Global configuration |  :black_circle: | :black_circle: | :black_circle: |
| Cluster |  :black_circle: | :black_circle: | :black_circle: |
| Registration Service |  :black_circle: | :black_circle: | :black_circle: |
| Alerts |  :black_circle: | :black_circle: | :black_circle: |
| Integrations |  :black_circle: | :black_circle: | :black_circle: |
| Policy monitoring |  :black_circle: | :black_circle: | :black_circle: |
| OpenSCAP |  :black_circle: | :black_circle: | :black_circle: |
| CIS-CAT |  :black_circle: | :black_circle: | :black_circle: |
| Vulnerabilities |  :black_circle: | :black_circle: | :black_circle: |
| Osquery |  :black_circle: | :black_circle: | :black_circle: |
| Inventory data |  :black_circle: | :black_circle: | :black_circle: |
| Active Response |  :black_circle: | :black_circle: | :black_circle: |
| Commands |  :black_circle: | :black_circle: | :black_circle: |
| Docker listener |  :black_circle: | :black_circle: | :black_circle: |
| Log collection |  :black_circle: | :black_circle: | :black_circle: |
| Integrity monitoring |  :black_circle: | :black_circle: | :black_circle: |
| Agentless |  :black_circle: | :black_circle: | :black_circle: |
| Amazon S3 |  :black_circle: | :black_circle: | :black_circle: |
| Azure Logs |  :black_circle: | :black_circle: | :black_circle: |
| Google Cloud Pub/Sub |  :black_circle: | :black_circle: | :black_circle: |
| GitHub |  :black_circle: | :black_circle: | :black_circle: |
| Office 365 |  :black_circle: | :black_circle: | :black_circle: |


### Test
Run the folowing test:
| Test | Pass | 
| --- |  --- | 
| alerts_test |  :black_circle: | 
| api-auth-tab_test |  :black_circle: | 
| general-tab_test |  :black_circle: | 
| log-collection_test |  :black_circle: | 
| office365_test |  :black_circle: | 
| subscription-tab_test |  :black_circle: |

**Comment by yenienserrano** [comment]
## TEST

Legend:
:black_circle:: none
:green_circle:: pass
:yellow_circle:: warning
:red_circle:: fail
:white_circle:: not applicable

### UI
Check that the accesses to the JSON and XML formats are not shown in the following configuration management screens and their internal tabs.

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| Global configuration |  :black_circle: | :black_circle: | :black_circle: |
| Cluster |  :black_circle: | :black_circle: | :black_circle: |
| Registration Service |  :black_circle: | :black_circle: | :black_circle: |
| Alerts |  :black_circle: | :black_circle: | :black_circle: |
| Integrations |  :black_circle: | :black_circle: | :black_circle: |
| Policy monitoring |  :black_circle: | :black_circle: | :black_circle: |
| OpenSCAP |  :black_circle: | :black_circle: | :black_circle: |
| CIS-CAT |  :black_circle: | :black_circle: | :black_circle: |
| Vulnerabilities |  :black_circle: | :black_circle: | :black_circle: |
| Osquery |  :black_circle: | :black_circle: | :black_circle: |
| Inventory data |  :black_circle: | :black_circle: | :black_circle: |
| Active Response |  :black_circle: | :black_circle: | :black_circle: |
| Commands |  :black_circle: | :black_circle: | :black_circle: |
| Docker listener |  :black_circle: | :black_circle: | :black_circle: |
| Log collection |  :black_circle: | :black_circle: | :black_circle: |
| Integrity monitoring |  :black_circle: | :black_circle: | :black_circle: |
| Agentless |  :black_circle: | :black_circle: | :black_circle: |
| Amazon S3 |  :black_circle: | :black_circle: | :black_circle: |
| Azure Logs |  :black_circle: | :black_circle: | :black_circle: |
| Google Cloud Pub/Sub |  :black_circle: | :black_circle: | :black_circle: |
| GitHub |  :black_circle: | :black_circle: | :black_circle: |
| Office 365 |  :black_circle: | :black_circle: | :black_circle: |


### Test
Run the folowing test:
| Test | Pass | 
| --- |  --- | 
| alerts_test |  :black_circle: | 
| api-auth-tab_test |  :black_circle: | 
| general-tab_test |  :black_circle: | 
| log-collection_test |  :black_circle: | 
| office365_test |  :black_circle: | 
| subscription-tab_test |  :black_circle: |

**Review by yenienserrano — APPROVED** [review]
LGTM

**Review by Machi3mfl — DISMISSED** [review]
CR: :heavy_check_mark: 
Test: :heavy_check_mark: 

Test evidence in https://github.com/wazuh/wazuh-kibana-app/pull/5747#issuecomment-1660860723

**Review by yenienserrano — APPROVED** [review]
LGTM

**Pull request merged**
