### PR TITLE
Statistical histograms did not update the x-axis with large time intervals

### LINKED ISSUE #5258: Statistics Histograms don't update X axis with large time intervals
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.3   | 7.x     | 4xxx | Basic, ODFE, Xpack |

| Browser |
| ------- |
| Chrome, Firefox, Safari, etc|

**Description**
Histograms in Management Statistics show hours as X-axis labels even when several days/months or years are filtered.

**Preconditions**
1. Hace information in the statistics index.

**Steps to reproduce**
1. Navigate to Management -> Statistics
2. Select a filter with 90 days
3. Check the x-axis labels

**Expected Result**
1. x-axis should change the unit of reference suitable for the interval length

**Actual Result**
1. Always shows 00:00 hours in the x-axis labels

**Screenshots**

image

image

image

image

image

### PR DESCRIPTION
**Pull request by chantal-kelm**
### Description

Statistical histograms did not update the x-axis with large time intervals
 
### Issues Resolved

#5258 

### Evidence

https://github.com/wazuh/wazuh-kibana-app/assets/99441266/36f3a743-ed70-4560-a179-7a09743bf523

### Test

Verify that all displays in the management > statistics section are line displays.

List of visualizations:

- Total number of bytes received
- Events sent to Analysisd
- TCP sessions
- Events processed
- Events Dropped
- Queue Usage
- Events Decoded summary
- Syscheck
- Syscollector
- Rootcheck
- SCA
- Host Info

### Check List
- [x] All tests pass
  - [x] `yarn test:jest`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [x] Update [CHANGELOG.md](./../CHANGELOG.md)
- [x] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Comment by yenienserrano** [comment]
While testing I saw something strange, I was with a manager that had only 1 node, and in the graphs I had 5 nodes. 

image

image

also saw that it is hardcoded some colors with some workers

image

**Review by yenienserrano — COMMENTED** [review]
https://github.com/wazuh/wazuh-kibana-app/pull/5707#issuecomment-1665463906

**Review by Tostti — APPROVED** [review]
Verify that all displays in the management > statistics section are line displays.  ✔️


image
image
image
image


TEST:✔️
CR:✔️

LGTM

**Review by jbiset — APPROVED** [review]
CR: :heavy_check_mark: 

## TEST UI

### Capture screen evidence

https://github.com/wazuh/wazuh-kibana-app/assets/43619595/cc0a6a47-ede3-4531-a5d0-6030e48b87a2


### List of visualizations

<details>
<summary>
:green_circle:  Total number of bytes received
</summary>

visualization_1

</details>

<details>
<summary>
:green_circle:  Events sent to Analysisd
</summary>

visualization_2

</details>

<details>
<summary>
:green_circle:  TCP sessions
</summary>

visualization_3

</details>

<details>
<summary>
:green_circle:  Events processed
</summary>

visualization_4

</details>

<details>
<summary>
:green_circle:  Events Dropped
</summary>

visualization_5

</details>

<details>
<summary>
:green_circle:  Queue Usage
</summary>

visualization_6

</details>

<details>
<summary>
:green_circle:  Events Decoded summary
</summary>

visualization_7

</details>

<details>
<summary>
:green_circle:  Syscheck
</summary>

visualization_8

</details>

<details>
<summary>
:green_circle:  Syscollector
</summary>

visualization_9

</details>

<details>
<summary>
:green_circle:  Rootcheck
</summary>

visualization_10

</details>

<details>
<summary>
:green_circle:  SCA
</summary>

visualization_11

</details>

<details>
<summary>
:green_circle:  Host Info
</summary>

visualization_12

</details>

**Pull request merged**
