### PR TITLE
Add Agent Stats section

### PR DESCRIPTION
**Pull request by Desvelao**
Hi team, this PR:
- Add Agent Stats section with the new API endpoints:
```
GET /agents/:agent_id/stats/agent
GET /agents/:agent_id/stats/logcollector
```

**Screenshots**

- Agent Stats view

image

- Agent Stats prompt when the agent status is not `active`.

image

### Tests
- Agent with a version equal or higher version than v4.2.0 and `active` status
  ✅ Expected see the information of new API endpoints
- Agent with a version equal or higher version than v4.2.0 and no `active` status (`disconnect` by example ) 
  ✅ Expected see a prompt with requiring `active` agent status
- Agent with a version lower than v4.2.0
  ✅ Expected see a prompt displaying the feature is not available for that agent

Closes: https://github.com/wazuh/wazuh-kibana-app/issues/2951 https://github.com/wazuh/wazuh-kibana-app/issues/2800

### CODE REVIEW

**Comment by pablomarga** [comment]
I have tested it and I think that a prompt should be added if you click on the stats section and the agent version is lower than 4.2.
Captura de pantalla 2021-03-09 a las 11 28 53

**Comment by Desvelao** [comment]
### TODO
[ ] Add prompt with user permisions
[ ] Add prompt with agent version >= 4.2.0

**Comment by Desvelao** [comment]
### Changes
- Added a prompt with the required user permissions
- Added a prompt with agent version requirement

Screenshots:
- Prompt with agent version requirement
image

**Comment by Desvelao** [comment]
### Update
- Merged changes from `4.2-7.10` into the branch
- Use the format dates function in Agent stats section
- Fix some problems with old code using the deprecated TimeService

**Review by pablomarga — APPROVED** [review]
Tested it and everything seems to be working fine, great job! LGTM!

**Comment by frankeros** [comment]
Testing it with a custom police (**agent:read** **agent:id:001**)
I got this result when I try to open the stats section
image

**Review by frankeros — APPROVED** [review]
tested :heavy_check_mark: 
LGTM! Great Job :tada:

**Pull request merged**
