### PR TITLE
error message when changing a group's config with right permissions

### PR DESCRIPTION
**Pull request by sortizowlh**
Hi team, this PR fixes:

An error message is displayed when changing a group's configuration although the user has the right permissions

Closes: #2937

### CODE REVIEW

**Review by gabiwassan — APPROVED** [review]
LGTM!

**Comment by Desvelao** [comment]
I tested the PR with the user permissions defined in the issue and the `Save` button is now displaying a permission `cluster:status` (`*:*:*`)

Screenshot
image

**Comment by Desvelao** [comment]
The change in the `CHANGELOG.md` is missing. You should add it.

**Comment by sortizowlh** [comment]
Updated `CHANGELOG.md`

**Pull request merged**
