### PR TITLE
fix for 4499-validate-that-the-added-filter-label-is-removed-after-click-remove-filter-option-dashboard

### PR DESCRIPTION
**Pull request by mauceballos**
## Description:

This PR includes the fix for the feature "Validate that the added filter label is remove after click remove filter option modules Dashboard"

We decided to delete some modules because on wzd these modules are disabled by default
Modules:

- GDPR
- HIPAA
- NIST

the feature remains:

```
  Scenario Outline: The user remove an added filter - Module - Dashboard <Module Name>
    When The user goes to <Module Name>
    And The user adds a new filter
    And The user checks filter label is added
    And The user removes the applied filter
    Then The user checks filter label is not added
    Examples:
      | Module Name          |
      | Security Events      |
      | Integrity Monitoring |
      | System Auditing      |
      | Mitre & Attack       |
      | TSC                  |
      | Policy Monitoring    |
      | PCIDSS               |

```
### Test
<details>
<summary> Feature</summary>

Screenshot from 2022-09-14 09-52-35

</details>

<details>
<summary> Test execution</summary>

Screenshot from 2022-09-14 09-56-49
 
Screenshot from 2022-09-14 09-51-47

</details>

### CODE REVIEW

**Review by Mayons95 — APPROVED** [review]

**Comment by Mayons95** [comment]
CR: :heavy_check_mark: 

LGTM!

**Review by Mayons95 — CHANGES_REQUESTED** [review]
The NIST module it's working fine on this Test, it's not necessary to remove it

image

**Review by Machi3mfl — APPROVED** [review]
LGTM!

**Comment by mauceballos** [comment]
Hi @Mayons95, 
I Add a screenshot of the fix of your comment

<details>

Screenshot from 2022-09-16 10-11-57

</details>

**Pull request merged**
