### PR TITLE
Fix API request to get the manager labels and broken documentation link

### LINKED ISSUE #5565: Invalid API calls and broken link in the `Management < Configuration < Alerts` section
| Wazuh | Rev  |
| ----- | ---- |
| 4.4.4 | 01   |

## Description
This section has several problems: 

- Invalid API requests returning a 500 response.
- A broken link to the documentation.

### Steps to reproduce
1. Navigate to `Management < Configuration < Alerts`
2. Check the Network tab: there are several requests with 500 response code

1. Click on 'Labels'
2. Click on the info icon
3. Click on`Agent labels`
4. Redirects to a 404 in the documentation page

## Additional info

Request:
```json
{
  "method": "GET",
  "path": "/cluster/node01/configuration/analysis/labels",
  "body": {},
  "id": "default"
}
```

Response
```json
{
  "statusCode": 500,
  "error": "Internal Server Error",
  "message": "3013 - Invalid configuration for the given component: Valid configuration values for 'analysis': {'global', 'active_response', 'alerts', 'internal', 'command', 'rule_test', 'rules', 'decoders'}"
}
```

Request:
```json
{
  "method": "GET",
  "path": "/cluster/node01/configuration/monitor/reports",
  "body": {},
  "id": "default"
}
```

Response
```json
{
  "statusCode": 500,
  "error": "Internal Server Error",
  "message": "3013 - Invalid configuration for the given component: Valid configuration values for 'monitor': {'internal', 'global'}"
}
```

Broken link: https://documentation.wazuh.com/4.4/user-manual/capabilities/labels.html
should be: https://documentation.wazuh.com/current/user-manual/agents/labels.html

### Tasks

- [x] Fix broken link
- [x] Fix broken API requests

## Screenshots
image

image

## Related issues 

- [ ] #5396

### PR DESCRIPTION
**Pull request by Desvelao**
### Description

Changes:
- API request to get the manager labels

Fixed:
- Broken documentation link to the agent labels
 
### Issues Resolved
#5565

### Evidence

# Check

Check changes in https://github.com/wazuh/wazuh/issues/17610.

I installed from sources a Wazuh manager based in the current `4.5.1` version.
```json
{"data": {"title": "Wazuh API REST", "api_version": "4.5.1", "revision": 40501, "license_name": "GPL 2.0", "license_url": "https://github.com/wazuh/wazuh/blob/v4.5.1/LICENSE", "hostname": "wazuh-manager-master-7102", "timestamp": "2023-07-18T11:10:11Z"}, "error": 0}
```

Review changes in https://github.com/wazuh/wazuh/issues/17610

## Labels manager

- Manager
Adapting the API request and managing the response:
image
image

- Cluster
Adapting the API request and managing the response:
image
image

## Labels - agent

- API request
image

- UI
image

### Reports

- Cluster node
image

- Manager node
image

- UI
image

### Test

# Wazuh dashboard

Legend:
:black_circle:: none
:green_circle:: pass
:yellow_circle:: warning
:red_circle:: fail
:white_circle:: not applicable

## UI

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| Select an agent and go to its Labels configuration. Review the Agents labels help link is pointing to user-manual/agents/labels.html | :black_circle: | :black_circle: | :black_circle: |
| Configure the manager labels and see in Management> Configuration > Alerts > Labels the labels are displayed (Manager mode) | :black_circle: | :black_circle: | :black_circle: |
| Configure the manager labels and see in Management> Configuration > Alerts > Labels the labels are displayed (Cluster mode) | :black_circle: | :black_circle: | :black_circle: |
| Configure the manager reports and see in Management> Configuration > Alerts > Reports the reports are displayed (Manager mode) | :black_circle: | :black_circle: | :black_circle: |
| Configure the manager reports and see in Management> Configuration > Alerts > Reports the reports are displayed (Cluster mode) | :black_circle: | :black_circle: | :black_circle: |
| Configure the agent labels and see in Configuration > Labels the labels are displayed | :black_circle: | :black_circle: | :black_circle: |

**Details**
<details>
<summary>:black_circle: Select an agent and go to its Labels configuration. Review the Agents labels help link is pointing to user-manual/agents/labels.html</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Configure the manager labels and see in Management> Configuration > Alerts > Labels the labels are displayed (Manager mode)</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Configure the manager labels and see in Management> Configuration > Alerts > Labels the labels are displayed (Cluster mode)</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Configure the manager reports and see in Management> Configuration > Alerts > Reports the reports are displayed (Manager mode)</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Configure the manager reports and see in Management> Configuration > Alerts > Reports the reports are displayed (Cluster mode)</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Configure the agent labels and see in Configuration > Labels the labels are displayed</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

### Check List
- [x] All tests pass
  - [ ] `yarn test:jest`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [x] Update [CHANGELOG.md](./../CHANGELOG.md)
- [x] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Review by jbiset — APPROVED** [review]
### Test

# Wazuh dashboard

Legend:
:black_circle:: none
:green_circle:: pass
:yellow_circle:: warning
:red_circle:: fail
:white_circle:: not applicable

## CR: :heavy_check_mark: 

## UI

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| Select an agent and go to its Labels configuration. Review the Agents labels help link is pointing to user-manual/agents/labels.html | :green_circle: | :green_circle: | :black_circle: |
| Configure the manager labels and see in Management> Configuration > Alerts > Labels the labels are displayed (Manager mode) | :green_circle: | :green_circle: | :black_circle: |
| Configure the manager labels and see in Management> Configuration > Alerts > Labels the labels are displayed (Cluster mode) | :green_circle: | :green_circle: | :black_circle: |
| Configure the manager reports and see in Management> Configuration > Alerts > Reports the reports are displayed (Manager mode) | :green_circle: | :green_circle: | :black_circle: |
| Configure the manager reports and see in Management> Configuration > Alerts > Reports the reports are displayed (Cluster mode) | :green_circle: | :green_circle: | :black_circle: |
| Configure the agent labels and see in Configuration > Labels the labels are displayed | :green_circle: | :green_circle: | :black_circle: |

**Details**
<details>
<summary>:green_circle: Select an agent and go to its Labels configuration. Review the Agents labels help link is pointing to user-manual/agents/labels.html</summary>

Chrome - :green_circle:
Test1_Chrome

Firefox - :green_circle:
Test1_Firefox

Safari - :black_circle:

</details>

<details>
<summary>:green_circle: Configure the manager labels and see in Management> Configuration > Alerts > Labels the labels are displayed (Manager mode)</summary>

Chrome - :green_circle:
Test2_API_Chrome

Test2_UI_Chrome

Firefox - :green_circle:
Test2_API_Firefox

Test2_UI_Firefox

Safari - :black_circle:

</details>

<details>
<summary>:green_circle: Configure the manager labels and see in Management> Configuration > Alerts > Labels the labels are displayed (Cluster mode)</summary>

Chrome - :green_circle:
Test3_API_Chrome

Test3_UI_Chrome

Firefox - :green_circle:
Test3_API_Firefox

Test3_UI_Firefox

Safari - :black_circle:

</details>

<details>
<summary>:green_circle: Configure the manager reports and see in Management> Configuration > Alerts > Reports the reports are displayed (Manager mode)</summary>

Chrome - :green_circle:
Test4_API_Chrome

Test4_UI_Chrome


Firefox - :green_circle:
Test4_API_Firefox

Test4_UI_Firefox

Safari - :black_circle:

</details>

<details>
<summary>:green_circle: Configure the manager reports and see in Management> Configuration > Alerts > Reports the reports are displayed (Cluster mode)</summary>

Chrome - :green_circle:
Test5_API_Chrome

Test5_UI_Chrome

Firefox - :green_circle:
Test5_API_Firefox

Test5_UI_Firefox

Safari - :black_circle:

</details>

<details>
<summary>:green_circle: Configure the agent labels and see in Configuration > Labels the labels are displayed</summary>

Chrome - :green_circle:
Test6_API_Chrome

Test6_UI_Chrome

Firefox - :green_circle:
Test6_API_Firefox

Test6_UI_Firefox

Safari - :black_circle:

</details>

**Comment by yenienserrano** [comment]
### Test

# Wazuh dashboard

Legend:
:black_circle:: none
:green_circle:: pass
:yellow_circle:: warning
:red_circle:: fail
:white_circle:: not applicable

## UI

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| Select an agent and go to its Labels configuration. Review the Agents labels help link is pointing to user-manual/agents/labels.html | :black_circle: | :black_circle: | :black_circle: |
| Configure the manager labels and see in Management> Configuration > Alerts > Labels the labels are displayed (Manager mode) | :black_circle: | :black_circle: | :black_circle: |
| Configure the manager labels and see in Management> Configuration > Alerts > Labels the labels are displayed (Cluster mode) | :black_circle: | :black_circle: | :black_circle: |
| Configure the manager reports and see in Management> Configuration > Alerts > Reports the reports are displayed (Manager mode) | :black_circle: | :black_circle: | :black_circle: |
| Configure the manager reports and see in Management> Configuration > Alerts > Reports the reports are displayed (Cluster mode) | :black_circle: | :black_circle: | :black_circle: |
| Configure the agent labels and see in Configuration > Labels the labels are displayed | :black_circle: | :black_circle: | :black_circle: |

**Details**
<details>
<summary>:black_circle: Select an agent and go to its Labels configuration. Review the Agents labels help link is pointing to user-manual/agents/labels.html</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Configure the manager labels and see in Management> Configuration > Alerts > Labels the labels are displayed (Manager mode)</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Configure the manager labels and see in Management> Configuration > Alerts > Labels the labels are displayed (Cluster mode)</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Configure the manager reports and see in Management> Configuration > Alerts > Reports the reports are displayed (Manager mode)</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Configure the manager reports and see in Management> Configuration > Alerts > Reports the reports are displayed (Cluster mode)</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Configure the agent labels and see in Configuration > Labels the labels are displayed</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

**Review by Tostti — DISMISSED** [review]
### Test

# Wazuh dashboard

Legend:
:black_circle:: none
:green_circle:: pass
:yellow_circle:: warning
:red_circle:: fail
:white_circle:: not applicable

## CR: :heavy_check_mark: 

## UI

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| Select an agent and go to its Labels configuration. Review the Agents labels help link is pointing to user-manual/agents/labels.html | :green_circle: | :green_circle: | :black_circle: |
| Configure the manager labels and see in Management> Configuration > Alerts > Labels the labels are displayed (Manager mode) | :green_circle: | :green_circle: | :black_circle: |
| Configure the manager labels and see in Management> Configuration > Alerts > Labels the labels are displayed (Cluster mode) | :green_circle: | :green_circle: | :black_circle: |
| Configure the manager reports and see in Management> Configuration > Alerts > Reports the reports are displayed (Manager mode) | :green_circle: | :green_circle: | :black_circle: |
| Configure the manager reports and see in Management> Configuration > Alerts > Reports the reports are displayed (Cluster mode) | :green_circle: | :green_circle: | :black_circle: |
| Configure the agent labels and see in Configuration > Labels the labels are displayed | :green_circle: | :green_circle: | :black_circle: |

**Details**
<details>
<summary>:green_circle: Select an agent and go to its Labels configuration. Review the Agents labels help link is pointing to user-manual/agents/labels.html</summary>

Chrome - :green_circle:
image

Firefox - :green_circle:
image

Safari - :black_circle:

</details>

<details>
<summary>:green_circle: Configure the manager labels and see in Management> Configuration > Alerts > Labels the labels are displayed (Manager mode)</summary>

Chrome - :green_circle:
image


Firefox - :green_circle:
image

Safari - :black_circle:

</details>

<details>
<summary>:green_circle: Configure the manager labels and see in Management> Configuration > Alerts > Labels the labels are displayed (Cluster mode)</summary>

Chrome - :green_circle:
image

Firefox - :green_circle:
image

Safari - :black_circle:

</details>

<details>
<summary>:green_circle: Configure the manager reports and see in Management> Configuration > Alerts > Reports the reports are displayed (Manager mode)</summary>

Chrome - :green_circle:
image

Firefox - :green_circle:
image

Safari - :black_circle:

</details>

<details>
<summary>:green_circle: Configure the manager reports and see in Management> Configuration > Alerts > Reports the reports are displayed (Cluster mode)</summary>

Chrome - :green_circle:
image

Firefox - :green_circle:
image

Safari - :black_circle:

</details>

<details>
<summary>:green_circle: Configure the agent labels and see in Configuration > Labels the labels are displayed</summary>

Chrome - :green_circle:
image

Firefox - :green_circle:
image


Safari - :black_circle:

</details>

TEST:✔️
CR:✔️

LGTM

**Review by yenienserrano — APPROVED** [review]
LGTM

**Review by yenienserrano — APPROVED** [review]

**Pull request merged**
