### PR TITLE
Fix pre-release environments for kibana 7.10.2

### PR DESCRIPTION
**Pull request by yenienserrano**
### Description
The pre-release environments in Kibana 7.10.2 were not working. Because of a file permissions problem that caused the container where Kibana was located to stop working.
 
### Evidence
image

### Test
Try to use the pre-release environment and install wazuh on version 7.10.2 and 7.16.x or 7.17.x.

### Check List
- [ ] All tests pass
  - [ ] `yarn test:jest`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [x] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Review by AlexRuiz7 — DISMISSED** [review]

**Comment by Desvelao** [comment]
# Kibana

Legend:
:black_circle:: none
:green_circle:: pass
:yellow_circle:: warning
:red_circle:: fail
:white_circle:: not applicable



## Other

| Test | Result |
| --- |  --- |
| All the containers should be initiated without problems in a docker/wazuh-4.3-es/pre.sh for Elastic version 7.10.2 | :green_circle: |

**Details**
<details>
<summary>:green_circle: All the containers should be initiated without problems in a docker/wazuh-4.3-es/pre.sh for Elastic version 7.10.2</summary>

```console
user:docker/wazuh-4.3-es $ ./pre.sh 7.10.2 0 up
[+] Running 10/10
 ⠿ Network es-pre-7.10.2             Created                                                                                                                                             0.0s
 ⠿ Volume "es-pre-7102_esdata01"     Created                                                                                                                                             0.0s
 ⠿ Volume "es-pre-7102_kibanadata"   Created                                                                                                                                             0.0s
 ⠿ Volume "es-pre-7102_certs"        Created                                                                                                                                             0.0s
 ⠿ Container es-pre-7102-imposter-1  Started                                                                                                                                             0.8s
 ⠿ Container es-pre-7102-exporter-1  Started                                                                                                                                             0.9s
 ⠿ Container es-pre-7102-setup-1     Healthy                                                                                                                                             5.1s
 ⠿ Container es-pre-7102-es01-1      Healthy                                                                                                                                            26.0s
 ⠿ Container es-pre-7102-filebeat-1  Started                                                                                                                                            26.4s
 ⠿ Container es-pre-7102-kibana-1    Started                                                                                                                                            26.4s

Install the pre-release package manually with:

1. Copy the pre-release package to the running Kibana container:
docker cp wazuh_kibana-4.3.0_7.10.2-1.zip es-pre-7102-kibana-1:/tmp

2. Install the pre-release package:
docker exec -ti es-pre-7102-kibana-1 /usr/share/kibana/bin/kibana-plugin install file:///tmp/wazuh_kibana-4.3.0_7.10.2-1.zip

3. Restart Kibana:
docker restart es-pre-7102-kibana-1

4. Upload the Wazuh app configuration:
docker cp ./config/kibana/wazuh.yml es-pre-7102-kibana-1:/usr/share/kibana/data/wazuh/config/

5. Open Kibana in a browser:
http://localhost:5601

user:docker/wazuh-4.3-es $ docker ps
CONTAINER ID   IMAGE                                                       COMMAND                   CREATED          STATUS                            PORTS                                       NAMES
209df91944f5   docker.elastic.co/kibana/kibana:7.10.2                      "/usr/local/bin/dumb…"    31 seconds ago   Up 4 seconds (health: starting)   0.0.0.0:5601->5601/tcp, :::5601->5601/tcp   es-pre-7102-kibana-1
70e180aa2962   elastic/filebeat:7.10.2                                     "/bin/bash -c '\n  mk…"   31 seconds ago   Up 4 seconds                                                                  es-pre-7102-filebeat-1
b1d8fd8ff2dc   docker.elastic.co/elasticsearch/elasticsearch:7.10.2        "/tini -- /usr/local…"    31 seconds ago   Up 25 seconds (healthy)           9200/tcp, 9300/tcp                          es-pre-7102-es01-1
315bba08f0d5   docker.elastic.co/elasticsearch/elasticsearch:7.10.2        "/tini -- /usr/local…"    31 seconds ago   Up 30 seconds (healthy)           9200/tcp, 9300/tcp                          es-pre-7102-setup-1
00948f9a466a   outofcoffee/imposter                                        "java -classpath /op…"    31 seconds ago   Up 30 seconds                     8080/tcp, 8443/tcp                          es-pre-7102-imposter-1
67c2bfd8a492   quay.io/prometheuscommunity/elasticsearch-exporter:latest   "/bin/elasticsearch_…"    31 seconds ago   Up 30 seconds                     7979/tcp                                    es-pre-7102-exporter-1
```
</details>

**Review by Desvelao — APPROVED** [review]
**review**:

:green_circle: code
:green_circle: test https://github.com/wazuh/wazuh-kibana-app/pull/5311#issuecomment-1479025189

**Comment by Desvelao** [comment]
# Kibana

Legend:
:black_circle:: none
:green_circle:: pass
:yellow_circle:: warning
:red_circle:: fail
:white_circle:: not applicable

## Other

| Test | Result |
| --- |  --- |
| All the containers should be initiated without problems in a docker/wazuh-4.3-es/rel.sh for Elastic version 7.10.2 | :green_circle: |

**Details**
<details>
<summary>:green_circle: All the containers should be initiated without problems in a docker/wazuh-4.3-es/rel.sh for Elastic version 7.10.2</summary>

```console
user:wazuh-4.3-es $ ./rel.sh 7.10.2 4.3.9 up
[+] Running 5/5
 ⠿ Container es-rel-7102-exporter-1       Started                                                                                                                                        0.8s
 ⠿ Container es-rel-7102-es01-1           Healthy                                                                                                                                       25.3s
 ⠿ Container es-rel-7102-wazuh.manager-1  Started                                                                                                                                        4.8s
 ⠿ Container es-rel-7102-kibana-1         Started                                                                                                                                       25.5s
 ⠿ Container es-rel-7102-setup-1          Healthy                                                                                                                                        4.0s

Install Wazuh 4.3.9 into Elastic 7.10.2 manually with:

1. Install the Wazuh app for Kibana
docker exec -ti es-rel-7102-kibana-1 /usr/share/kibana/bin/kibana-plugin install https://packages.wazuh.com/4.x/ui/kibana/wazuh_kibana-4.3.9_7.10.2-1.zip

2. Restart Kibana
docker restart es-rel-7102-kibana-1

3. Configure Kibana
docker cp ./config/kibana/wazuh.yml es-rel-7102-kibana-1:/usr/share/kibana/data/wazuh/config/

4. Open Kibana in a browser:
http://localhost:5601

5. (Optional) Enroll an agent (Ubuntu 20.04):
docker run --name es-rel-7102-agent --network es-rel-7102 --label com.docker.compose.project=es-rel-7102 -d ubuntu:20.04 bash -c '
  apt update -y
  apt install -y curl lsb-release
  curl -so \wazuh-agent-4.3.9.deb \
    https://packages.wazuh.com/4.x/apt/pool/main/w/wazuh-agent/wazuh-agent_4.3.9-1_amd64.deb \
    && WAZUH_MANAGER='wazuh.manager' WAZUH_AGENT_GROUP='default' dpkg -i ./wazuh-agent-4.3.9.deb

  /etc/init.d/wazuh-agent start
  tail -f /var/ossec/logs/ossec.log
'

user:wazuh-4.3-es $ docker ps
CONTAINER ID   IMAGE                                                       COMMAND                  CREATED          STATUS                    PORTS                                       NAMES
34426980772c   docker.elastic.co/kibana/kibana:7.10.2                      "/usr/local/bin/dumb…"   50 seconds ago   Up 24 seconds (healthy)   0.0.0.0:5601->5601/tcp, :::5601->5601/tcp   es-rel-7102-kibana-1
af5a72187f61   docker.elastic.co/elasticsearch/elasticsearch:7.10.2        "/tini -- /usr/local…"   51 seconds ago   Up 45 seconds (healthy)   9200/tcp, 9300/tcp                          es-rel-7102-es01-1
c2a4bbc5bd52   wazuh/wazuh-manager:4.3.9                                   "/init"                  51 seconds ago   Up 45 seconds             1514-1516/tcp, 514/udp, 55000/tcp           es-rel-7102-wazuh.manager-1
890d7011e5d7   quay.io/prometheuscommunity/elasticsearch-exporter:latest   "/bin/elasticsearch_…"   51 seconds ago   Up 49 seconds             7979/tcp                                    es-rel-7102-exporter-1
```
</details>

**Review by Desvelao — APPROVED** [review]
**review**

:green_circle: code
:green_circle: test

**Review by AlexRuiz7 — APPROVED** [review]

**Pull request merged**
