### PR TITLE
[Backport 4.5-7.16] Fix macos apple install command

### PR DESCRIPTION
**Pull request by Machi3mfl**
Backport https://github.com/wazuh/wazuh-kibana-app/commit/fc10c84a77e9834ff0875de43389c5a1c517f219 from #5470

### CODE REVIEW

**Review by Tostti — DISMISSED** [review]
imagen

TEST:✔️
CR:✔️

LGTM

**Comment by Desvelao** [comment]
# Changes

- Changed the pull request entry on changelog
- Fixed release version titles on changelog

**Comment by Desvelao** [comment]
# Wazuh dashboard

Legend:
:black_circle:: none
:green_circle:: pass
:yellow_circle:: warning
:red_circle:: fail
:white_circle:: not applicable

## UI

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| The command in the deployment guide to starting a new macOS agent must use `sudo` | :green_circle: | :green_circle: | :black_circle: |

**Details**
<details>
<summary>:green_circle: The command in the deployment guide to starting a new macOS agent must use `sudo`</summary>

Chrome - :green_circle:
image

Firefox - :green_circle:
image

Safari - :black_circle:

</details>

**Review by Desvelao — APPROVED** [review]
**review**

code :green_circle: 
test :green_circle:

**Pull request merged**
