### PR TITLE
Replace search bar in Management > Cluster > Nodes

### PR DESCRIPTION
**Pull request by Desvelao**
### Description
This pull request replaces the search bar and table component in Management/Cluster/Nodes.

Affected sections:
- Management > Cluster > Nodes

Additional changes:
- Remove unused code
- Change the title of the panel from `Nodes` to `Cluster nodes`
- Fix the tooltip in the back button

> It depends on https://github.com/wazuh/wazuh-kibana-app/pull/5442

### Issues Resolved
https://github.com/wazuh/wazuh-kibana-app/issues/4312

### Evidence
image
image

Table - Explore agent
Suggestions:
| field | get distinct values | searchable | searchable term |
| --- | --- | --- | --- |
| ip | GET /cluster/nodes?distinct=true&limit=30&select={field}&sort=+{field}&q={currentValue} |  :white_check_mark: |  :white_check_mark: |
| name | GET /cluster/nodes?distinct=true&limit=30&select={field}&sort=+{field}&q={currentValue} |  :white_check_mark: |  :white_check_mark: |
| types | GET /cluster/nodes?distinct=true&limit=30&select={field}&sort=+{field}&q={currentValue} |  :white_check_mark: |  :white_check_mark: |
| version | GET /cluster/nodes?distinct=true&limit=30&select={field}&sort=+{field}&q={currentValue} |  :white_check_mark: |  :white_check_mark: |

### Test

> Use a Wazuh manager

Legend:
:black_circle:: none
:green_circle:: pass
:yellow_circle:: warning
:red_circle:: fail
:white_circle:: not applicable

## UI

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| Management > Cluster > Nodes: For each suggested field, check the value suggestion display results or at least doesn't break | :black_circle: | :black_circle: | :black_circle: |
| Management > Cluster > Nodes: Using a value suggested should allow to run the search | :black_circle: | :black_circle: | :black_circle: |
| Management > Cluster > Nodes: Type a term and run the search should search in each displayed field | :black_circle: | :black_circle: | :black_circle: |
| Management > Cluster > Nodes: Type a simple field search and this should returns the expected results | :black_circle: | :black_circle: | :black_circle: |
| Management > Cluster > Nodes: Type a complex field search and this should returns the expected results | :black_circle: | :black_circle: | :black_circle: |
| Management > Cluster > Nodes: Clicking on the Refresh button should refresh the data | :black_circle: | :black_circle: | :black_circle: |
| Management > Cluster > Nodes: Clicking on the Export formatted button should refresh export the data to CSV | :black_circle: | :black_circle: | :black_circle: |

**Details**
<details>
<summary>:black_circle: Management > Cluster > Nodes: For each suggested field, check the value suggestion display results or at least doesn't break</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Management > Cluster > Nodes: Using a value suggested should allow to run the search</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Management > Cluster > Nodes: Type a term and run the search should search in each displayed field</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Management > Cluster > Nodes: Type a simple field search and this should returns the expected results</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Management > Cluster > Nodes: Type a complex field search and this should returns the expected results</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Management > Cluster > Nodes: Clicking on the Refresh button should refresh the data</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Management > Cluster > Nodes: Clicking on the Export formatted button should refresh export the data to CSV</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

### Check List
- [ ] All tests pass
  - [ ] `yarn test:jest`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [ ] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Comment by Tostti** [comment]
Legend:
:black_circle:: none
:green_circle:: pass
:yellow_circle:: warning
:red_circle:: fail
:white_circle:: not applicable

## UI

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| Management > Cluster > Nodes: For each suggested field, check the value suggestion display results or at least doesn't break | :black_circle: | :black_circle: | :black_circle: |
| Management > Cluster > Nodes: Using a value suggested should allow to run the search | :black_circle: | :black_circle: | :black_circle: |
| Management > Cluster > Nodes: Type a term and run the search should search in each displayed field | :black_circle: | :black_circle: | :black_circle: |
| Management > Cluster > Nodes: Type a simple field search and this should returns the expected results | :black_circle: | :black_circle: | :black_circle: |
| Management > Cluster > Nodes: Type a complex field search and this should returns the expected results | :black_circle: | :black_circle: | :black_circle: |
| Management > Cluster > Nodes: Clicking on the Refresh button should refresh the data | :black_circle: | :black_circle: | :black_circle: |
| Management > Cluster > Nodes: Clicking on the Export formatted button should refresh export the data to CSV | :black_circle: | :black_circle: | :black_circle: |

**Details**
<details>
<summary>:black_circle: Management > Cluster > Nodes: For each suggested field, check the value suggestion display results or at least doesn't break</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Management > Cluster > Nodes: Using a value suggested should allow to run the search</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Management > Cluster > Nodes: Type a term and run the search should search in each displayed field</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Management > Cluster > Nodes: Type a simple field search and this should returns the expected results</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Management > Cluster > Nodes: Type a complex field search and this should returns the expected results</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Management > Cluster > Nodes: Clicking on the Refresh button should refresh the data</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Management > Cluster > Nodes: Clicking on the Export formatted button should refresh export the data to CSV</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

**Review by Tostti — APPROVED** [review]
TEST:✔️
CR:✔️

LGTM

**Comment by lucianogorza** [comment]
Legend:
:black_circle:: none
:green_circle:: pass
:yellow_circle:: warning
:red_circle:: fail
:white_circle:: not applicable

## UI

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| Management > Cluster > Nodes: For each suggested field, check the value suggestion display results or at least doesn't break | :black_circle: | :black_circle: | :black_circle: |
| Management > Cluster > Nodes: Using a value suggested should allow to run the search | :black_circle: | :black_circle: | :black_circle: |
| Management > Cluster > Nodes: Type a term and run the search should search in each displayed field | :black_circle: | :black_circle: | :black_circle: |
| Management > Cluster > Nodes: Type a simple field search and this should returns the expected results | :black_circle: | :black_circle: | :black_circle: |
| Management > Cluster > Nodes: Type a complex field search and this should returns the expected results | :black_circle: | :black_circle: | :black_circle: |
| Management > Cluster > Nodes: Clicking on the Refresh button should refresh the data | :black_circle: | :black_circle: | :black_circle: |
| Management > Cluster > Nodes: Clicking on the Export formatted button should refresh export the data to CSV | :black_circle: | :black_circle: | :black_circle: |

**Details**
<details>
<summary>:black_circle: Management > Cluster > Nodes: For each suggested field, check the value suggestion display results or at least doesn't break</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Management > Cluster > Nodes: Using a value suggested should allow to run the search</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Management > Cluster > Nodes: Type a term and run the search should search in each displayed field</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Management > Cluster > Nodes: Type a simple field search and this should returns the expected results</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Management > Cluster > Nodes: Type a complex field search and this should returns the expected results</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Management > Cluster > Nodes: Clicking on the Refresh button should refresh the data</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Management > Cluster > Nodes: Clicking on the Export formatted button should refresh export the data to CSV</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

**Review by Tostti — APPROVED** [review]

**Review by lucianogorza — DISMISSED** [review]
TEST:✔️
CR:✔️

LGTM

**Pull request merged**
