### PR TITLE
Fixed unsopported components of solaris

### LINKED ISSUE #2773: Wazuh UI crashes when navigate over Solaris Wazuh agent information
| Wazuh | Open Distro for Elasticsearch | Rev |
| ----- | ------- | --- |
| 4.0.3   | 7.9.1     | 4013 |

**Description**
Related: https://github.com/wazuh/wazuh-kibana-app/issues/2725 
When I navigate over different Wazuh UI sections in a Solaris agent, if I want to click on Wazuh logo for home redirection, the Wazuh UI crash. Please find the behavior in the video attached:

https://user-images.githubusercontent.com/3830293/104331001-dd7f7700-54ee-11eb-8fc4-f19595483912.mp4

Best regards, 
Alberto R

### PR DESCRIPTION
**Pull request by pablomarga**
Hi team this PR fixed the unsupported components of solaris agents.
Closes #2773

### CODE REVIEW

**Review by Desvelao — DISMISSED** [review]
LGTM!

**Review by Desvelao — COMMENTED** [review]
Add the fix to changelog.md

**Review by frankeros — APPROVED** [review]
LGTM!

**Review by frankeros — APPROVED** [review]
LGTM!

**Review by Desvelao — APPROVED** [review]
LGTM!

**Pull request merged**
