### PR TITLE
Added new DB Limit on FIM configuration

### LINKED ISSUE #3849: Add DB limit settings to the FIM configuration
Hi team,

As part of https://github.com/wazuh/wazuh/issues/9103 new options have been added to the FIM configuration in order to limit the number of entries in the FIM databases. 

Before the change, the FIM configuration was limited to file entries and look like:
```xml
<!-- Maximum number of files to be monitored -->
<file_limit>
  <enabled>yes</enabled>
  <entries>100000</entries>
</file_limit>
```

In the WUI, it is represented as follows:
image

Now, that block is replaced by:
```xml
<!-- Maximum number of entries to be monitored -->
<db_entry_limit>
  <enabled>yes</enabled>
  <files>50000</files>
  <registries>50000</registries>
</db_entry_limit>
```

So this change should be applied in the WUI as well.

## Update

The requirements for these settings changed, here the latest update:

- Instead of the `db_entry_limit` block, the `file_limit` block remains in use, and also a new block called `registry_limit` is added with the same appearance as the `file_limit`.
```
    <registry_limit>
      <enabled>yes</enabled>
      <entries>100000</entries>
    </registry_limit>
```

- Inside the synchronization config, a new setting called `thread_pool` is added. It specifies the number of threads used by the FIM database synchronization. FIM will use the minimum number between the configured value and the number of CPU cores of the system.
```
<synchronization>
  <thread_pool>1</thread_pool>
</synchronization>
```

Best regards,
Chema.

### PR DESCRIPTION
**Pull request by Machi3mfl**
Hi Team,
This adds a new DB limit tab in FIM agent configuration 
Close #3849

### CODE REVIEW

**Comment by Machi3mfl** [comment]
### Scope

**Added new blocks inside `syscheck` configuration (FIM configuration):**

- file_limit
- registy_limit `(only for Windows agent, hide in manager configuration)`
- synchronization > thread_pool


```xml
// ossec.conf
<syscheck>
... 
<file_limit>
  <enabled>yes</enabled>
  <entries>100000</entries>
</file_limit>

<synchronization>
  ...
  <thread_pool>1</thread_pool>
</synchronization>

</syscheck>

```

# Test cases (:hourglass: In progress...)

## 1. Agent configuration


### A. Windows agent

### B. NO Windows agent


## 2.. Manager configuration

**Comment by Machi3mfl** [comment]
# Template test cases
# 7.10.2

Legend:
:black_circle:: none
:green_circle:: pass
:yellow_circle:: warning
:red_circle:: fail
:white_circle:: not applicable

## UI

| Test | Chrome | Firefox |
| --- |  --- | --- |
| FIM Files limit enabled in agent config | :black_circle: | :black_circle: |
| FIM Files limit disabled in agent config | :black_circle: | :black_circle: |
| FIM Files limit enabled in manager config | :black_circle: | :black_circle: |
| FIM Files limit disabled in manager config | :black_circle: | :black_circle: |
| FIM Registries limit enabled in agent (windows) config | :black_circle: | :black_circle: |
| FIM Registries limit disabled in agent (windows) config | :black_circle: | :black_circle: |
| FIM Registries limit is hidden in manager config | :black_circle: | :black_circle: |
| FIM Registries limit is hidden in agent (no windows) config | :black_circle: | :black_circle: |
| FIM Synchronization new Number of threads field in agent config | :black_circle: | :black_circle: |
| FIM Synchronization new Number of threads field in manager config | :black_circle: | :black_circle: |

**Details**
<details>
<summary>:black_circle: FIM Files limit enabled in agent config</summary>

Chrome - :black_circle:

Firefox - :black_circle:

</details>

<details>
<summary>:black_circle: FIM Files limit disabled in agent config</summary>

Chrome - :black_circle:

Firefox - :black_circle:

</details>

<details>
<summary>:black_circle: FIM Files limit enabled in manager config</summary>

Chrome - :black_circle:

Firefox - :black_circle:

</details>

<details>
<summary>:black_circle: FIM Files limit disabled in manager config</summary>

Chrome - :black_circle:

Firefox - :black_circle:

</details>

<details>
<summary>:black_circle: FIM Registries limit enabled in agent (windows) config</summary>

Chrome - :black_circle:

Firefox - :black_circle:

</details>

<details>
<summary>:black_circle: FIM Registries limit disabled in agent (windows) config</summary>

Chrome - :black_circle:

Firefox - :black_circle:

</details>

<details>
<summary>:black_circle: FIM Registries limit is hidden in manager config</summary>

Chrome - :black_circle:

Firefox - :black_circle:

</details>

<details>
<summary>:black_circle: FIM Registries limit is hidden in agent (no windows) config</summary>

Chrome - :black_circle:

Firefox - :black_circle:

</details>

<details>
<summary>:black_circle: FIM Synchronization new Number of threads field in agent config</summary>

Chrome - :black_circle:

Firefox - :black_circle:

</details>

<details>
<summary>:black_circle: FIM Synchronization new Number of threads field in manager config</summary>

Chrome - :black_circle:

Firefox - :black_circle:

</details>

**Comment by yenienserrano** [comment]
# Template test cases
# 7.10.2

Legend:
:black_circle:: none
:green_circle:: pass
:yellow_circle:: warning
:red_circle:: fail
:white_circle:: not applicable

## UI

| Test | Chrome | Firefox |
| --- |  --- | --- |
| FIM Files limit enabled in agent config | :black_circle: | :black_circle: |
| FIM Files limit disabled in agent config | :black_circle: | :black_circle: |
| FIM Files limit enabled in manager config | 🟢 | :black_circle: |
| FIM Files limit disabled in manager config | 🟢 | :black_circle: |
| FIM Registries limit enabled in agent (windows) config | :black_circle: | :black_circle: |
| FIM Registries limit disabled in agent (windows) config | :black_circle: | :black_circle: |
| FIM Registries limit is hidden in manager config | 🟢 | :black_circle: |
| FIM Registries limit is hidden in agent (no windows) config | :black_circle: | :black_circle: |
| FIM Synchronization new Number of threads field in agent config | :black_circle: | :black_circle: |
| FIM Synchronization new Number of threads field in manager config | 🟢 | :black_circle: |

**Details**
<details>
<summary>:black_circle: FIM Files limit enabled in agent config</summary>

Chrome - :black_circle:

Firefox - :black_circle:

</details>

<details>
<summary>:black_circle: FIM Files limit disabled in agent config</summary>

Chrome - :black_circle:

Firefox - :black_circle:

</details>

<details>
<summary>🟢 FIM Files limit enabled in manager config</summary>

Chrome - 🟢 

image


Firefox - :black_circle:

</details>

<details>
<summary>🟢 FIM Files limit disabled in manager config</summary>

Chrome - 🟢 

image

Firefox - :black_circle:

</details>

<details>
<summary>:black_circle: FIM Registries limit enabled in agent (windows) config</summary>

Chrome - :black_circle:

Firefox - :black_circle:

</details>

<details>
<summary>:black_circle: FIM Registries limit disabled in agent (windows) config</summary>

Chrome - :black_circle:

Firefox - :black_circle:

</details>

<details>
<summary>🟢 FIM Registries limit is hidden in manager config</summary>

Chrome - 🟢 

image

Firefox - :black_circle:

</details>

<details>
<summary>:black_circle: FIM Registries limit is hidden in agent (no windows) config</summary>

Chrome - :black_circle:

Firefox - :black_circle:

</details>

<details>
<summary>:black_circle: FIM Synchronization new Number of threads field in agent config</summary>

Chrome - :black_circle:

Firefox - :black_circle:

</details>

<details>
<summary>🟢 FIM Synchronization new Number of threads field in manager config</summary>

Chrome - 🟢 

image

Firefox - :black_circle:

</details>

**Review by yenienserrano — APPROVED** [review]
LGTM

**Pull request merged**
