### PR TITLE
Fix Most active agent button in the Agents section

### PR DESCRIPTION
**Pull request by Desvelao**
### Description

This pull request fixes a problem in the `Most active agent` button in the Agents section due to a not defined method.
 
### Issues Resolved
[List any issues this PR will resolve]

### Evidence
[Provide screenshots or videos to prove this PR solves the issues]

### Test
[Provide instructions to test this PR]

### Check List
- [x] All tests pass
  - [x] `yarn test:jest`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [x] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Review by AlexRuiz7 — CHANGES_REQUESTED** [review]
LGTM but needs an issue and the fields in the PR description filled

**Review by yenienserrano — APPROVED** [review]
CR: ✔️ 
TEST: ✔️ 

<details><summary>Screenshots</summary>

image

image

</details>

**Review by AlexRuiz7 — APPROVED** [review]

**Comment by Machi3mfl** [comment]
Test: :heavy_check_mark: 
CR: :heavy_check_mark: 

image

image

P.D: I was late for a few seconds

**Review by Machi3mfl — COMMENTED** [review]
Test: :heavy_check_mark: 
CR: :heavy_check_mark: 

image

image

P.D: I was late for a few seconds

**Pull request merged**
