### PR TITLE
Replace search bar on Explore agent modal

### PR DESCRIPTION
**Pull request by Desvelao**
### Description
This pull request replaces the search bar and table component on Explore agent modal

Affected sections:
- Explore agent modal

Additional changes:
- Remove unused code

> It depends on https://github.com/wazuh/wazuh-kibana-app/pull/5442

### Issues Resolved
https://github.com/wazuh/wazuh-kibana-app/issues/4312

### Evidence
image
image
image

Table - Explore agent
Suggestions:
| field | get distinct values | searchable | searchable term |
| --- | --- | --- | --- |
| id | GET /agents?distinct=true&limit=30&select={field}&sort=+{field}&q={currentValue} |  :white_check_mark: |  :white_check_mark: |
| group | GET /agents?distinct=true&limit=30&select={field}&sort=+{field}&q={currentValue} |  :white_check_mark: |  :white_check_mark: |
|name | GET /agents?distinct=true&limit=30&select={field}&sort=+{field}&q={currentValue} |  :white_check_mark: |  :white_check_mark: |
|os.name | GET /agents?distinct=true&limit=30&select={field}&sort=+{field}&q={currentValue} |  :white_check_mark: |  :white_check_mark: |
|os.version | GET /agents?distinct=true&limit=30&select={field}&sort=+{field}&q={currentValue} |  :white_check_mark: |  :white_check_mark: |
|status | active,disconnected,pending,neved_connected | :white_check_mark: |  :white_check_mark: |
|version | GET /agents?distinct=true&limit=30&select={field}&sort=+{field}&q={currentValue} |  :white_check_mark: |  :white_check_mark: |

### Test

> Use a Wazuh manager

Legend:
:black_circle:: none
:green_circle:: pass
:yellow_circle:: warning
:red_circle:: fail
:white_circle:: not applicable

## UI

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| Explore agent modal: For each suggested field, check the value suggestion display results or at least doesn't break | :black_circle: | :black_circle: | :black_circle: |
| Explore agent modal: Using a value suggested should allow to run the search | :black_circle: | :black_circle: | :black_circle: |
| Explore agent modal: Type a term and run the search should search in each displayed field | :black_circle: | :black_circle: | :black_circle: |
| Explore agent modal: Type a simple field search and this should returns the expected results | :black_circle: | :black_circle: | :black_circle: |
| Explore agent modal: Type a complex field search and this should returns the expected results | :black_circle: | :black_circle: | :black_circle: |

**Details**
<details>
<summary>:black_circle: Explore agent modal: For each suggested field, check the value suggestion display results or at least doesn't break</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Explore agent modal: Using a value suggested should allow to run the search</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Explore agent modal: Type a term and run the search should search in each displayed field</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Explore agent modal: Type a simple field search and this should returns the expected results</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Explore agent modal: Type a complex field search and this should returns the expected results</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

### Check List
- [ ] All tests pass
  - [ ] `yarn test:jest`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [x] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Comment by Desvelao** [comment]
# TODO
- [ ] Use `agent_list` query parameter to get the selected agent. method: `selectAgentAndApply` file: plugins/main/public/controllers/overview/components/overview-actions/agents-selection-table.js. Reason: performance.

**Comment by Tostti** [comment]
Legend:
:black_circle:: none
:green_circle:: pass
:yellow_circle:: warning
:red_circle:: fail
:white_circle:: not applicable

## UI

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| Explore agent modal: For each suggested field, check the value suggestion display results or at least doesn't break | :black_circle: | :black_circle: | :black_circle: |
| Explore agent modal: Using a value suggested should allow to run the search | :black_circle: | :black_circle: | :black_circle: |
| Explore agent modal: Type a term and run the search should search in each displayed field | :black_circle: | :black_circle: | :black_circle: |
| Explore agent modal: Type a simple field search and this should returns the expected results | :black_circle: | :black_circle: | :black_circle: |
| Explore agent modal: Type a complex field search and this should returns the expected results | :black_circle: | :black_circle: | :black_circle: |

**Details**
<details>
<summary>:black_circle: Explore agent modal: For each suggested field, check the value suggestion display results or at least doesn't break</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Explore agent modal: Using a value suggested should allow to run the search</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Explore agent modal: Type a term and run the search should search in each displayed field</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Explore agent modal: Type a simple field search and this should returns the expected results</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Explore agent modal: Type a complex field search and this should returns the expected results</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

**Review by jbiset — COMMENTED** [review]
### Test

> Use a Wazuh manager

Legend:
:black_circle:: none
:green_circle:: pass
:yellow_circle:: warning
:red_circle:: fail
:white_circle:: not applicable

## UI

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| Explore agent modal: For each suggested field, check the value suggestion display results or at least doesn't break | :black_circle: | :black_circle: | :black_circle: |
| Explore agent modal: Using a value suggested should allow to run the search | :black_circle: | :black_circle: | :black_circle: |
| Explore agent modal: Type a term and run the search should search in each displayed field | :black_circle: | :black_circle: | :black_circle: |
| Explore agent modal: Type a simple field search and this should returns the expected results | :black_circle: | :black_circle: | :black_circle: |
| Explore agent modal: Type a complex field search and this should returns the expected results | :black_circle: | :black_circle: | :black_circle: |

**Details**
<details>
<summary>:black_circle: Explore agent modal: For each suggested field, check the value suggestion display results or at least doesn't break</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Explore agent modal: Using a value suggested should allow to run the search</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Explore agent modal: Type a term and run the search should search in each displayed field</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Explore agent modal: Type a simple field search and this should returns the expected results</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Explore agent modal: Type a complex field search and this should returns the expected results</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

### Check List
- [ ] All tests pass
  - [ ] `yarn test:jest`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [x] Commits are signed per the DCO using --signoff

**Comment by chantal-kelm** [comment]
| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| Explore agent modal: For each suggested field, check the value suggestion display results or at least doesn't break | :black_circle: | :black_circle: | :black_circle: |
| Explore agent modal: Using a value suggested should allow to run the search | :black_circle: | :black_circle: | :black_circle: |
| Explore agent modal: Type a term and run the search should search in each displayed field | :black_circle: | :black_circle: | :black_circle: |
| Explore agent modal: Type a simple field search and this should returns the expected results | :black_circle: | :black_circle: | :black_circle: |
| Explore agent modal: Type a complex field search and this should returns the expected results | :black_circle: | :black_circle: | :black_circle: |

**Details**
<details>
<summary>:black_circle: Explore agent modal: For each suggested field, check the value suggestion display results or at least doesn't break</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Explore agent modal: Using a value suggested should allow to run the search</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Explore agent modal: Type a term and run the search should search in each displayed field</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Explore agent modal: Type a simple field search and this should returns the expected results</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Explore agent modal: Type a complex field search and this should returns the expected results</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

**Review by chantal-kelm — DISMISSED** [review]

**Review by jbiset — DISMISSED** [review]

**Review by jbiset — DISMISSED** [review]

**Review by chantal-kelm — APPROVED** [review]

**Review by jbiset — APPROVED** [review]

**Review by chantal-kelm — APPROVED** [review]

**Pull request merged**
