### PR TITLE
[Backport 4.5] Fix cannot read null properties bug in settings section

### PR DESCRIPTION
**Pull request by Desvelao**
Backport 4c113f7f613e0c52d1e070721f64056c2b38d7e2 from #5135.

### CODE REVIEW

**Comment by Tostti** [comment]
# WZD

Legend:
:black_circle:: none
:green_circle:: pass
:yellow_circle:: warning
:red_circle:: fail
:white_circle:: not applicable

## UI

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| Error is not displayed when going from Settings/Configuration to another section | :green_circle: | :green_circle: | :black_circle: |
| Platform loading indicator is displayed when saving the configuration in Settings/Configuration | :yellow_circle: | :green_circle: | :black_circle: |

**Details**
<details>
<summary>:green_circle: Error is not displayed when going from Settings/Configuration to another section</summary>

Chrome - :green_circle:
imagen


Firefox - :green_circle:
imagen



Safari - :black_circle:

</details>

<details>
<summary>:yellow_circle: Platform loading indicator is displayed when saving the configuration in Settings/Configuration</summary>

Chrome - :yellow_circle:
Although the indicator is shown, In Chrome it breaks the logo after it finishes saving. I could not identify why is this happening, it will be good to be tested in another system to see if the error persists.

https://user-images.githubusercontent.com/42900763/220732502-a5aebe65-769e-4237-8c97-122813812105.mp4



Firefox - :green_circle:

imagen

Safari - :black_circle:

</details>

**Comment by Desvelao** [comment]
> Chrome - yellow_circle
Although the indicator is shown, In Chrome it breaks the logo after it finishes saving. I could not identify why is this happening, it will be good to be tested in another system to see if the error persists.

I tested the problem reported by @Tostti related to the loading logo that replaces the platform logo when saving the Wazuh configuration through `Settings/Configuration` using Google Chrome and I could not replicate it.

Could someone from @wazuh/frontend check it?

**Comment by yenienserrano** [comment]
# WZD

Legend:
:black_circle:: none
:green_circle:: pass
:yellow_circle:: warning
:red_circle:: fail
:white_circle:: not applicable

## UI

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| Error is not displayed when going from Settings/Configuration to another section | :green_circle: | :green_circle: | :black_circle: |
| Platform loading indicator is displayed when saving the configuration in Settings/Configuration | :yellow_circle: | :green_circle: | :black_circle: |

**Details**
<details>
<summary>:green_circle: Error is not displayed when going from Settings/Configuration to another section</summary>

Chrome - :green_circle:

image
image

Firefox - :green_circle:

image
image



Safari - :black_circle:

</details>

<details>
<summary>:yellow_circle: Platform loading indicator is displayed when saving the configuration in Settings/Configuration</summary>

Chrome - :yellow_circle:

OSD: 2.6.0
Chrome: 111.0.5563.64 (Official Build) (64-bit)

With the black header work well
Without the black header don't work

```
opensearchDashboards.branding:
  useExpandedHeader: false
```
image
image
```
opensearchDashboards.branding:
  useExpandedHeader: true
```
image
image


Firefox - :green_circle:

With the black header work well
Without the black header work well

image
image

Safari - :black_circle:

</details>

**Comment by Desvelao** [comment]
I reviewed it again and this is working for me when using Google Chrome.
Google Chrome 104.0.5112.79.

**Comment by chantal-kelm** [comment]
# WZD

Legend:
:black_circle:: none
:green_circle:: pass
:yellow_circle:: warning
:red_circle:: fail
:white_circle:: not applicable

## UI

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| Error is not displayed when going from Settings/Configuration to another section | :green_circle: | :green_circle: | :green_circle: |
| Platform loading indicator is displayed when saving the configuration in Settings/Configuration | :green_circle: | :green_circle: | :green_circle: |

**Details**
<details>
<summary>:green_circle: Error is not displayed when going from Settings/Configuration to another section</summary>

Chrome - :green_circle:

Version 110

https://user-images.githubusercontent.com/99441266/224045790-c1b35dd3-088c-4577-b64f-4a2ebe6b1fba.mov

https://user-images.githubusercontent.com/99441266/224045898-41143fd8-dbff-467a-ac69-b4a87f458df8.mov

Version 111

https://user-images.githubusercontent.com/99441266/224046074-0532c7ba-64ea-49df-a67b-a2e38b7da0cf.mov

https://user-images.githubusercontent.com/99441266/224046164-b5adaeed-18e9-4678-a6ea-b1132971ddde.mov


Firefox - :green_circle:


https://user-images.githubusercontent.com/99441266/224046835-5c5c658d-dee0-4677-a14a-e7aa2ce080de.mov

https://user-images.githubusercontent.com/99441266/224048121-53f92226-c440-4e58-8516-c8dfa1f92243.mov


Safari - :green_circle:


https://user-images.githubusercontent.com/99441266/224047228-fbcef28f-7d81-4ec7-a353-df21605744ca.mov

https://user-images.githubusercontent.com/99441266/224047952-ac8c3543-fa24-4655-9655-834376eff089.mov



</details>

<details>
<summary>:green_circle: Platform loading indicator is displayed when saving the configuration in Settings/Configuration</summary>

Chrome - :green_circle:

OSD: 2.6.0
Chrome: 111.0.5563.64 (Official Build) (64-bit)

With the black header work well
Without the black header don't work

```
opensearchDashboards.branding:
  useExpandedHeader: false
```
image
image
image
image
```
opensearchDashboards.branding:
  useExpandedHeader: true
```
image
image


`Stack Management/Advanced Settings`

It has similar operation and works well

image
image




Firefox - :green_circle:

With the black header work well
Without the black header work well

image
image

Safari - :green_circle:

</details>

**Review by Tostti — APPROVED** [review]
TEST:✔️
CR:✔️

LGTM

**Review by Machi3mfl — APPROVED** [review]
# WZD

Legend:
:black_circle:: none
:green_circle:: pass
:yellow_circle:: warning
:red_circle:: fail
:white_circle:: not applicable

## UI

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| Error is not displayed when going from Settings/Configuration to another section | :green_circle: | :green_circle: | :black_circle: |
| Platform loading indicator is displayed when saving the configuration in Settings/Configuration | :green_circle: | :green_circle: | :black_circle: |

**Details**
<details>
<summary>:green_circle: Error is not displayed when going from Settings/Configuration to another section</summary>

Chrome - :green_circle:

- Version 110.0.5481.77

https://user-images.githubusercontent.com/6089438/224109510-92fa85a4-307e-4a88-8f40-a5efd9242c2f.mp4

Firefox - :green_circle:

https://user-images.githubusercontent.com/6089438/224110002-85949ffa-1e52-4a5e-a873-afe7594be06f.mp4

</details>

<details>
<summary>:green_circle: Platform loading indicator is displayed when saving the configuration in Settings/Configuration</summary>

Chrome - :green_circle:

- Version 110.0.5481.77

https://user-images.githubusercontent.com/6089438/224110370-66c1361a-6291-4c5f-8dca-6dc4c7c1b90f.mp4


Firefox - :green_circle:

https://user-images.githubusercontent.com/6089438/224110644-03efd0db-2484-42b4-b7b6-17ee66fd9d55.mp4

</details>

**Pull request merged**
