### PR TITLE
Replace generic HTTP status codes in the API controller

### PR DESCRIPTION
**Pull request by asteriscos**
### Description
Hi team, this PR replaces HTTPS status error codes to prevent expected errors to be logged in the server console. 

Checking the connection of a downed API should now throw a 503 Service Unavailable.

image

### Issues Resolved
https://github.com/wazuh/wazuh-kibana-app/issues/4650

### Test
- Create in `wazuh.yml` configuration a fake Wazuh API entry to cause a connection exception.
- Load the app
- Try to connect to that API
- Check for errors in the server logs

### Check List
- [ ] All tests pass
  - [ ] `yarn test:jest`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [ ] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Review by AlexRuiz7 — APPROVED** [review]
- Code review: ✔️ 
- Test: ✔️

**Review by AlexRuiz7 — CHANGES_REQUESTED** [review]
Changelog entry missing

**Review by yenienserrano — APPROVED** [review]
LGTM

image

**Review by AlexRuiz7 — APPROVED** [review]
LGTM

**Pull request merged**
