### PR TITLE
Adding remove filters from agent module

### PR DESCRIPTION
**Pull request by Mayons95**
Hello team ! I create this PR to add a new automated test case.
The goal of the test is to check if the remove filter functionality it's working.
So in the development of this test we consider the creation and deletion of a particular filter on all the modules available for a particular agent.
I'll add more information on this PR a soon I have the test result data.

### CODE REVIEW

**Comment by Mayons95** [comment]
Test development in  process

image

**Comment by Mayons95** [comment]
Test it's working on Kibana

image

**Comment by Mayons95** [comment]
Test it's working on WZD
image

**Review by chantal-kelm — APPROVED** [review]

**Review by Machi3mfl — APPROVED** [review]

**Comment by Mayons95** [comment]
Test failure

image

**Pull request merged**
