### PR TITLE
Modules -> Mitre -> Widget: Rows per page

### PR DESCRIPTION
**Pull request by chantal-kelm**
4.3-7.10: Now in the widget you can choose between 10, 15, 25, 50 or 100 rows.

### CODE REVIEW

**Comment by Mayons** [comment]
For the next time, It would be very useful to include some screenshot for visualize quickly the applied changes

**Comment by Mayons** [comment]
Test pending, can't find where the change was implemented
Follow up with @chantal-kelm

**Comment by Mayons** [comment]
TEST OK
Reviewed with @chantal-kelm

**Review by Mayons — APPROVED** [review]

**Comment by Desvelao** [comment]
I will close this PR in favor to https://github.com/wazuh/wazuh-kibana-app/pull/4066.

**Pull request closed without merging**
