### PR TITLE
changed allow_run_as way of editing

### LINKED ISSUE #3059: Adapt allow_run_as editing to use the new endpoint
**Describe the solution you'd like**

Hello team,

With the changes to `allow_run_as` permissions in https://github.com/wazuh/wazuh/pull/7588, we should adapt our security section to use the new endpoint to change the value for the `allow_run_as` parameter of the Wazuh API users.

We should remove the option to select `allow_run_as` value when creating users:

image

Instead, we should only be able to modify the value when editing the user. For that purpose we should use the new endpoint:

`PUT /security/users/{user_id}/run_as` and check the appropriate permissions for the user performing the action with:

```
        actions: [ 'security:edit_run_as' ]
        resources: [ '*:*:*' ]
```

Regards,

David J. Iglesias

### PR DESCRIPTION
**Pull request by asteriscos**
Hi team,

this adapts how the `allow_run_as` user property is edited.

Closes #3059

### CODE REVIEW

**Comment by Desvelao** [comment]
Add the change to `changelog.md` file.

**Comment by Desvelao** [comment]
### Tests
✅ Create a user with `run_as` using `admin` Elasticsearch user ( Wazuh API roles: `administrator`)
✅ Create a user without `run_as` using `admin` Elasticsearch user ( Wazuh API roles: `administrator`)
❌  Edit a user to enable `run_as` using `admin` Elasticsearch user ( Wazuh API roles: `administrator`)
I can't apply the changes, the `Apply` button is disabled
image
❌  Edit a user to disable `run_as` using `admin` Elasticsearch user ( Wazuh API roles: `administrator`)
I can't apply the changes, the `Apply` button is disabled
image
✅ Create a user with using `custom_admin` Elasticsearch user ( Wazuh API roles: `administrator` `custom_policy_deny_edit_run_as`). The `run_as` setting should is disabled and can not be selected.
image
❌  Edit a user `run_as` using `custom_admin` Elasticsearch user ( Wazuh API roles: `administrator` `custom_policy_deny_edit_run_as`). The `run_as` setting should is disabled and can not be selected.
image
I can't apply the changes, the `Apply` button is disabled
image


How I created the `custom_admin` user:
Policy `deny_run_as`
image
Role `deny_run_as`
image
Role mapping `wazuh_admin`
image

I created a user in Elasticsearch called `wazuh_admin` and a role with permissions about `wazuh*` indices.

**Comment by asteriscos** [comment]
> ### Tests
>  Create a user with `run_as` using `admin` Elasticsearch user ( Wazuh API roles: `administrator`)
>  Create a user without `run_as` using `admin` Elasticsearch user ( Wazuh API roles: `administrator`)
>  Edit a user to enable `run_as` using `admin` Elasticsearch user ( Wazuh API roles: `administrator`)
> I can't apply the changes, the `Apply` button is disabled
> image
>  Edit a user to disable `run_as` using `admin` Elasticsearch user ( Wazuh API roles: `administrator`)
> I can't apply the changes, the `Apply` button is disabled
> image
>  Create a user with using `custom_admin` Elasticsearch user ( Wazuh API roles: `administrator` `custom_policy_deny_edit_run_as`). The `run_as` setting should is disabled and can not be selected.
> image
>  Edit a user `run_as` using `custom_admin` Elasticsearch user ( Wazuh API roles: `administrator` `custom_policy_deny_edit_run_as`). The `run_as` setting should is disabled and can not be selected.
> image
> I can't apply the changes, the `Apply` button is disabled
> image
> 
> How I created the `custom_admin` user:
> Policy `deny_run_as`
> image
> Role `deny_run_as`
> image
> Role mapping `wazuh_admin`
> image
> 
> I created a user in Elasticsearch called `wazuh_admin` and a role with permissions about `wazuh*` indices.

I have pushed a fixed. It turns out it was missing a password changed evaluation the show the apply button.

**Comment by frankeros** [comment]
> ### Tests
> 
> white_check_mark Create a user with `run_as` using `admin` Elasticsearch user ( Wazuh API roles: `administrator`)
> white_check_mark Create a user without `run_as` using `admin` Elasticsearch user ( Wazuh API roles: `administrator`)
> x Edit a user to enable `run_as` using `admin` Elasticsearch user ( Wazuh API roles: `administrator`)
> I can't apply the changes, the `Apply` button is disabled
> image
> x Edit a user to disable `run_as` using `admin` Elasticsearch user ( Wazuh API roles: `administrator`)
> I can't apply the changes, the `Apply` button is disabled
> image
> white_check_mark Create a user with using `custom_admin` Elasticsearch user ( Wazuh API roles: `administrator` `custom_policy_deny_edit_run_as`). The `run_as` setting should is disabled and can not be selected.
> image
> x Edit a user `run_as` using `custom_admin` Elasticsearch user ( Wazuh API roles: `administrator` `custom_policy_deny_edit_run_as`). The `run_as` setting should is disabled and can not be selected.
> image
> I can't apply the changes, the `Apply` button is disabled
> image
> 
> How I created the `custom_admin` user:
> Policy `deny_run_as`
> image
> Role `deny_run_as`
> image
> Role mapping `wazuh_admin`
> image
> 
> I created a user in Elasticsearch called `wazuh_admin` and a role with permissions about `wazuh*` indices.

this error still happens

**Comment by Desvelao** [comment]
> > x Edit a user `run_as` using `custom_admin` Elasticsearch user ( Wazuh API roles: `administrator` `custom_policy_deny_edit_run_as`). The `run_as` setting should is disabled and can not be selected.
> > image
> 
> this error still happens

I tested the PR again and this seems to be resolved:
image


I tested to edit the Wazuh API user with a user that can edit the `run_as` setting and I found the `Apply` button appear enabled when only modify the `run_as` setting and no set the new password. I guess this is the expected behavior because `run_as` and `password` are different endpoints. An example changing the `run_as` setting from `enabled` to `disabled` before apply the changes:
image

**Review by Desvelao — APPROVED** [review]
LGTM! Good job! 👍

**Review by frankeros — APPROVED** [review]
tested :heavy_check_mark: 
LGTM!!

**Pull request merged**
