### PR TITLE
Remove deprecated code and request in Management

### PR DESCRIPTION
**Pull request by yenienserrano**
### Description

Removed obsolete code that caused duplicate requests to the api, and change the query to search for 1 agent.
 
### Issues Resolved
- #5242 

### Evidence

<details><summary>Details</summary>

image

image

image

</details> 

### Test

Legend:
:black_circle:: none
:green_circle:: pass
:yellow_circle:: warning
:red_circle:: fail
:white_circle:: not applicable

## UI

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| Ensure that requests in `management/configuration` are not repeated | :black_circle: | :black_circle: | :black_circle: |
| Check that the request to agents is like this `GET /agents?agents_list=000` and does not have the parameter `q`| :black_circle: | :black_circle: | :black_circle: |

**Details**
<details>
<summary>:black_circle: Ensure that requests in management/configuration are not repeated</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Check that the request to agents is like this GET /agents?agents_list=000 and does not have the parameter q</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

### Check List
- [x] All tests pass
  - [x] `yarn test:jest`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [x] Update [CHANGELOG.md](./../CHANGELOG.md)
- [x] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Comment by Desvelao** [comment]
I didn't see any changes related to other problems reported in the issue is not solved: 
> When choosing some configurations (global for instance). See https://github.com/wazuh/wazuh-kibana-app/issues/5242#issue-1608375662.

@yenienserrano, Could you indicate if this was solved and where?

**Comment by Desvelao** [comment]
**todo**: remove the `clusterStatus` property usage in some tests and snapshots.

There are some tests definition and test snapshots that are using the `clusterStatus` property that was removed due to this is not being used anymore in some components.

**Comment by Desvelao** [comment]
**todo**: remove the `clusterStatus` property of `appStateReducers` of Redux in tests.

Affected files:
- public/controllers/management/components/management/groups/groups-main.test.tsx
- public/controllers/management/components/management/groups/__snapshots__/groups-main.test.tsx.snap

**Comment by yenienserrano** [comment]
> clusterStatus

Done

**Comment by Desvelao** [comment]
### Test

Legend:
:black_circle:: none
:green_circle:: pass
:yellow_circle:: warning
:red_circle:: fail
:white_circle:: not applicable

## UI

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| Ensure that requests in `management/configuration` are not repeated | :black_circle: | :black_circle: | :black_circle: |
| Check that the request to agents is like this `GET /agents?agents_list=000` and does not have the parameter `q`| :green_circle: | :black_circle: | :black_circle: |

**Details**
<details>
<summary>:green_circle: Ensure that requests in management/configuration are not repeated</summary>

Chrome - :green_circle:
image
image

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:green_circle: Check that the request to agents is like this GET /agents?agents_list=000 and does not have the parameter q</summary>

Chrome - :green_circle:
image

Firefox - :black_circle:

Safari - :black_circle:

</details>

**Review by Desvelao — APPROVED** [review]
**review**:

code :green_circle: 
test :green_circle: https://github.com/wazuh/wazuh-kibana-app/pull/5485#issuecomment-1580461276

**Pull request merged**
