### PR TITLE
Fixed Inventory checks table filters by stats

### LINKED ISSUE #4952: SCA result filters do not work
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.4   | 7.17     | 1 |  |

| Browser |
| ------- |
| Chrome, Firefox, Safari, etc|

**Description**
CIS benchmark status filters do not work properly

**Preconditions**
1. Have a registered agent
2. Have a finished SCA scan of the agent

**Steps to reproduce**
1. Navigate to Modules>Agent name>Security configuration assessment
3. Click on one of the filter buttons (Pass, Fail, or Not applicable)
4. Check that no filter is applied.

**Video**

[sca.webm](https://user-images.githubusercontent.com/11089305/205292819-d9731d95-50ff-48db-9fc1-de79c0098311.webm)

### PR DESCRIPTION
**Pull request by Machi3mfl**
### Description

Hi Team, This PR fixes the behavior when the Inventory Stat is clicked.
Closes #4952 

### Test case

- When the Inventory Stat is clicked the Check table must be filtered

https://user-images.githubusercontent.com/6089438/207654344-f8e73ffa-25fa-4881-ab8b-bd0317d80ebb.mp4

### Tests

1. **Scenario** The user can add a filter by clicking on the result count indicator (Pass) of the Security configuration assessment
 policy checks
**Given** SCA data is available
**When** the user is seeing the table of checks of a Security configuration assessment
 policy
**And** the user clicks on any result count indicator
**Then** a filter must be added to the search bar
**And** the table should be filtered by the added filter

2. **Scenario** The user can add a filter by clicking on the result count indicator (Fail) of the Security configuration assessment
 policy checks
**Given** SCA data is available
**When** the user is seeing the table of checks of a Security configuration assessment
 policy
**And** the user clicks on any result count indicator
**Then** a filter must be added to the search bar
**And** the table should be filtered by the added filter

3. **Scenario** The user can add a filter by clicking on the result count indicator (Not applicable) of the Security configuration assessment
 policy checks
**Given** SCA data is available
**When** the user is seeing the table of checks of a Security configuration assessment
 policy
**And** the user clicks on any result count indicator
**Then** a filter must be added to the search bar
**And** the table should be filtered by the added filter

### Check List
- [x] All tests pass
  - [x] `yarn test:jest`
- [x] New functionality includes testing.
- [x] New functionality has been documented.
- [x] Update [CHANGELOG.md](./../CHANGELOG.md)
- [x] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Review by Desvelao — CHANGES_REQUESTED** [review]
**review**

Tests

Legend:
:green_circle: Pass
:yellow_circle: Warning
:red_circle: Fail

Results:

| Scenario | Result |
| ---- | ---- |
| 1 |  :green_circle: |
| 2 |  :green_circle: |
| 3 |  :red_circle: |

Details:
<details>
<summary>Scenario 1 - :green_circle: </summary>

image

</details>

<details>
<summary>Scenario 2 - :green_circle: </summary>

image
</details>

<details>
<summary>Scenario 3 - :red_circle:</summary>

I found a problem by clicking on the `Not applicable` result count indicator, the table doesn't display any results.

image

I reviewed the request done when adding this filter and it uses the `result` query paramater with `not applicable` value. This value is not the correct one to get the expected checks.
image

If we review the value for any check that the UI displays as `Not applicable`, we see this is an empty string.
image

So, we expected if we change the value of the `result` query parameter to an empty string, we could get the expected results. By my tests, it is not working, so I guess the Wazuh API could not be expecting this case. We should consult it with the @wazuh/framework team.

In previous versions (ex: 4.3.10), this worked correctly and this was because in that version, all the checks are obtained and the filter are managed in the frontend.
</details>

**Comment by Desvelao** [comment]
> **review**
> 
> Tests
> 
> Legend: green_circle Pass yellow_circle Warning red_circle Fail
> 
> Results:
> 
> Scenario	Result
> 1	
> 2	
> 3	
> Details:
> 
> Scenario 1 - 
> Scenario 2 - 
> Scenario 3 - 
> I found a problem by clicking on the `Not applicable` result count indicator, the table doesn't display any results.
> 
> image
> 
> I reviewed the request done when adding this filter and it uses the `result` query paramater with `not applicable` value. This value is not the correct one to get the expected checks. image
> 
> If we review the value for any check that the UI displays as `Not applicable`, we see this is an empty string. image
> 
> So, we expected if we change the value of the `result` query parameter to an empty string, we could get the expected results. By my tests, it is not working, so I guess the Wazuh API could not be expecting this case. We should consult it with the @wazuh/framework team.
> 
> In previous versions (ex: 4.3.10), this worked correctly and this was because in that version, all the checks are obtained and the filter are managed in the frontend.

We had a meeting with @davidjiglesias and maybe we could get a workaround:
Use `status` query parameter instead of `result`.

For another hand, we could remove the **empty string** as a possible value of `result` filter so the users can't filter and get unexpected results.

We should review the suggestions for `status` too.

**Review by yenienserrano — APPROVED** [review]
LGTM

### Pass

image


### Fail

image

### Not applicable

image

**Review by chantal-kelm — APPROVED** [review]
CR: ✅ 
Test: ✅

**Review by Desvelao — APPROVED** [review]
**review**

:heavy_check_mark: code
:heavy_check_mark: test

Screenshots:

image
image

image

**Pull request merged**
