### PR TITLE
[4.0.4-7.10.0] Fixed accordion style breaking

### PR DESCRIPTION
**Pull request by frankeros**
Hi team, this resolves

- The inventory.scss is breaking all accordions style when it's loaded by the browser.
image

### CODE REVIEW

**Review by gabiwassan — APPROVED** [review]
Great!

**Comment by Desvelao** [comment]
I tested the PR and some sections as the MITRE flyout should too be fixed. Perhaps there could be more sections with this problem.
image
image

**Comment by frankeros** [comment]
> I tested the PR and some sections as the MITRE flyout should too be fixed. Perhaps there could be more sections with this problem.
> image
> image
> 
> These files contain more flyout with this problem:
> 
>     * `public/components/overview/compliance-table/components/requirement-flyout/requirement-flyout.tsx`
> 
>     * `public/components/overview/mitre/components/techniques/components/flyout-technique/flyout-technique.tsx`

I push a new commit to solve this too. Thanks!

**Review by pablomarga — APPROVED** [review]
LGTM!

**Pull request merged**
