### PR TITLE
[Module] [GitHub] Add the module

### PR DESCRIPTION
**Pull request by Desvelao**
This PR adds the GitHub module to the app.

### Features
- Add access to the module on the main and agent menu and `Modules directory`
- Let to configure the module visibility on `Settings/Modules`
- Add configuration viewer on `(Management/Agent)/Configuration` for managers and agents
- Add sample data
- Add the tabs to explore the data on `Modules`
   - Dashboard: created and added the visualizations
   - Events
   - Panel
     - views: 
       - main (4 tables with Elasticsearch aggregations) and access to 4 drills down (one for each table)
       - 4 drill down (user, organization, repository, action) with visualizations and events table
     - module information: display the configuration for the module taking into account if there is some agent pinned or not
     - implementation of the custom search bar (`simple` and `advanced` mode)
     

**Dashboard**
image

**Sample data**
image
image

### Tests
To be decided

### To test it
1. Go to Github
- **Given** the browser is logged in the Wazuh kibana app
- **When** the user navigate to `Modules` ->  `GitHub` -> any of the sections of Github
- **Then** the visualizations and tables will be displayed properly and without any errors

### TODO
- [x] Replace the current selectors to use the new `MultiSelect` component, which is used on the Office 365 module. This should be done after the implementation on the Office 365 branch is completed

Closes https://github.com/wazuh/wazuh-kibana-app/issues/3372

### CODE REVIEW

**Review by frankeros — COMMENTED** [review]
The tables of all drill downs in GitHub are broken 
image

**Comment by frankeros** [comment]
> The tables of all drill downs in GitHub are broken
> image



> The tables of all drill downs in GitHub are broken

Fixed

**Comment by Desvelao** [comment]
### Changes
- Updated the branch with the last changes of `feature/Office365`
- Add the render of missing spacers as the `api_auth` is displayed

**Comment by CPAlejandro** [comment]
Solved problem found in `Office 365/Events`:
image (7)

The problem is that the Events columns are not declared in Office and Github.

This is the result:

**Office**:
image

**Github**:
image

**Pull request merged**
