### PR TITLE
Feature add new dev tools

### PR DESCRIPTION
**Pull request by gabiwassan**
Hi team,
This PR added new dev console and logtest.
- New menu options.
- Integrated with request` PUT logtest`

image
image
image
image

Closes: #1434

### CODE REVIEW

**Comment by frankeros** [comment]
Please replace the section name to `Ruleset Test`

**Comment by Desvelao** [comment]
The target branch should be changed to `4.2-7.10`.

**Comment by Desvelao** [comment]
I tested the PR and it is working. 

2 things to say:
- Could this horizontal scroll be removed?
image
- We should use the same UI for the flyouts. The Ruleset test one has a horizontal line, while other flyouts not. Maybe we should talk to decide on the flyouts style.
image
image
image

One question: why add a button within the add rule file section? Surely there is a reason.

**Comment by gabiwassan** [comment]
> I tested the PR and it is working.
> 
> 2 things to say:
> 
> * Could this horizontal scroll be removed?
>   image
> * We should use the same UI for the flyouts. The Ruleset test one has a horizontal line, while other flyouts not. Maybe we should talk to decide on the flyouts style.
>   image
>   image
>   image
> 
> One question: why add a button within the add rule file section? Surely there is a reason.

I can fix this styles. Thank you!

`One question: why add a button within the add rule file section? Surely there is a reason.
`
The UX team passed that requirement on me, I suppose to make a possible test available before creating a rule.

**Pull request merged**
