### PR TITLE
Remove agent name in agent info ribbon

### PR DESCRIPTION
**Pull request by Desvelao**
### Description
This pull request removes the agent name in the agent info ribbon
 
### Issues Resolved
https://github.com/wazuh/wazuh-kibana-app/issues/5496

### Evidence
image

### Test

Legend:
:black_circle:: none
:green_circle:: pass
:yellow_circle:: warning
:red_circle:: fail
:white_circle:: not applicable

## UI

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| Ensure the agent name is not displayed in the agent info ribbon | :black_circle: | :black_circle: | :black_circle: |

**Details**
<details>
<summary>:black_circle: Ensure the agent name is not displayed in the agent info ribbon</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

### Check List
- [x] All tests pass
  - [ ] `yarn test:jest`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [x] Update [CHANGELOG.md](./../CHANGELOG.md)
- [x] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Review by Tostti — APPROVED** [review]
### Test

Legend:
:black_circle:: none
:green_circle:: pass
:yellow_circle:: warning
:red_circle:: fail
:white_circle:: not applicable

## UI

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| Ensure the agent name is not displayed in the agent info ribbon | :black_circle: | :black_circle: | :black_circle: |

**Details**
<details>
<summary>:black_circle: Ensure the agent name is not displayed in the agent info ribbon</summary>

Chrome - :black_circle:
imagen

Firefox - :black_circle:
imagen

Safari - :black_circle:

</details>

TEST:✔️
CR:✔️

LGTM

**Review by yenienserrano — APPROVED** [review]
CR: ✔️ 
Test: ✔️ 

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| Ensure the agent name is not displayed in the agent info ribbon | 🟢 | :black_circle: | :black_circle: |

**Details**
<details>
<summary>🟢 Ensure the agent name is not displayed in the agent info ribbon</summary>

Chrome - 🟢 

image

Firefox - :black_circle:

Safari - :black_circle:

</details>

**Comment by Desvelao** [comment]
Changes

- Moved changelog entry to 4.4.5

**Review by yenienserrano — APPROVED** [review]
LGTM

**Review by jbiset — DISMISSED** [review]
### Test

Legend:
:black_circle:: none
:green_circle:: pass
:yellow_circle:: warning
:red_circle:: fail
:white_circle:: not applicable

## UI

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
|  | :green_circle: | :green_circle: | :black_circle: |

**Details**
<details>
<summary>:green_circle: Ensure the agent name is not displayed in the agent info ribbon</summary>

Chrome - :green_circle:
chrome_debian_agent

Firefox - :green_circle:
firefox_debian_agent

Safari - :black_circle:

</details>

TEST:✔️
CR:✔️

LGTM

**Review by AlexRuiz7 — APPROVED** [review]

**Pull request merged**
