### PR TITLE
[Redesign add page] Agent register wizard handle properly special characters in password

### PR DESCRIPTION
**Pull request by Machi3mfl**
### Description

This PR, resolves the password management in the register agent command when having special characters

Closes https://github.com/wazuh/wazuh-kibana-app/issues/5493

### Check List
- [x] All tests pass
  - [x] `yarn test:jest`
- [x] New functionality includes testing.
- [x] New functionality has been documented.
- [x] Update [CHANGELOG.md](./../CHANGELOG.md)
- [x] Commits are signed per the DCO using --signoff 

# Testing E2E

- Use an environment with a real manager or mock the following response

```JSON
{
  "data": {
    "affected_items": [
      {
        "auth": {
          "port": 1515,
          "disabled": "no",
          "remote_enrollment": "yes",
          "use_source_ip": "no",
          "purge": "yes",
          "use_password": "yes",
          "ssl_verify_host": "no",
          "ssl_auto_negotiate": "no",
          "ciphers": "HIGH:!ADH:!EXP:!MD5:!RC4:!3DES:!CAMELLIA:@STRENGTH",
          "ssl_manager_cert": "/var/ossec/etc/sslmanagertest.cert",
          "ssl_manager_key": "/var/ossec/etc/sslmanagertest.key",
          "force": {
            "enabled": "yes",
            "key_mismatch": "yes",
            "disconnected_time": {
              "enabled": "yes",
              "value": 3600
            },
            "after_registration_time": 3600
          }
        },
        "authd.pass": "password\"with\"doubleq\\'usds\\\"es"
      }
    ],
    "total_affected_items": 1,
    "total_failed_items": 0,
    "failed_items": []
  },
  "message": "Active configuration was successfully read in specified node",
  "error": 0
}

```

With the following e2e test, we need to check that the password added in the manager `authd.pass` file will be copied in the agent `authd.pass` file

1. Add the `authd.pass` with the password and enable the `use_password` setting. [https://documentation.wazuh.com/current/user-manual/agent-enrollment/security-options/using-password-authentication.html](https://documentation.wazuh.com/current/user-manual/agent-enrollment/security-options/using-password-authentication.html)

```
password"with"doubleq\'usds\"es
```

The API will return the password defined on the authd.pass with the characters " and \ scaped. For example: "password\"with\"doubleq\\'usds\\\"es"

2. Go to the Deploy new agent page and fill out the form. (Depending on your OS)

https://github.com/wazuh/wazuh-kibana-app/assets/6089438/3aad55ee-ec51-439e-ad13-5b6846cd11e9

3. Copy the command and run it on your machine. (Replace de 4.7.0 version with the 4.4.5 version in the command)

4. Start the agent and check if the authd.pass file was created inside the agent folder 

**Linux: /var/ossec/etc/authd.pass
macOS: /Library/Ossec/etc/authd.pass
Windows: C:/Programs/ossec-agent/etc/authd.pass**

5. The password added in the manager and agent `authd.pass` file must be equal

```
password"with"doubleq\'usds\"es
```

### CODE REVIEW

**Comment by Machi3mfl** [comment]
## Added unit test

image

image

**Comment by Machi3mfl** [comment]
# Imposter example response

```JSON
{
  "data": {
    "affected_items": [
      {
        "auth": {
          "port": 1515,
          "disabled": "no",
          "remote_enrollment": "yes",
          "use_source_ip": "no",
          "purge": "yes",
          "use_password": "yes",
          "ssl_verify_host": "no",
          "ssl_auto_negotiate": "no",
          "ciphers": "HIGH:!ADH:!EXP:!MD5:!RC4:!3DES:!CAMELLIA:@STRENGTH",
          "ssl_manager_cert": "/var/ossec/etc/sslmanagertest.cert",
          "ssl_manager_key": "/var/ossec/etc/sslmanagertest.key",
          "force": {
            "enabled": "yes",
            "key_mismatch": "yes",
            "disconnected_time": {
              "enabled": "yes",
              "value": 3600
            },
            "after_registration_time": 3600
          }
        },
        "authd.pass": "password\"with\"doubleq\\'usds\\\"es"
      }
    ],
    "total_affected_items": 1,
    "total_failed_items": 0,
    "failed_items": []
  },
  "message": "Active configuration was successfully read in specified node",
  "error": 0
}


```

**Comment by Machi3mfl** [comment]
# Test evidence 

## Selecting `Linux` and completing all the optional parameters

image

image

### Command copied

```bash
curl -o wazuh-agent-4.7.0-1.x86_64.rpm https://packages.wazuh.com/4.x/yum/wazuh-agent-4.7.0-1.x86_64.rpm && sudo WAZUH_MANAGER='10.10.10.10' WAZUH_REGISTRATION_PASSWORD='password"with"doubleq\'usds\"es' WAZUH_AGENT_GROUP='default' WAZUH_AGENT_NAME='agent-name' rpm -ihv wazuh-agent-4.7.0-1.x86_64.rpm
```
## Selecting `Windows` and completing all the optional parameters

image

image

```powershell
Invoke-WebRequest -Uri https://packages.wazuh.com/4.x/windows/wazuh-agent-4.7.0-1.msi -OutFile ${env.tmp}\wazuh-agent; msiexec.exe /i ${env.tmp}\wazuh-agent /q WAZUH_MANAGER='10.10.10.10' WAZUH_REGISTRATION_PASSWORD='password"with"doubleq\'usds\"es' WAZUH_AGENT_GROUP='default' WAZUH_AGENT_NAME='agent-name' WAZUH_REGISTRATION_SERVER='10.10.10.10' 
```


## Selecting `macOS` and completing all the optional parameters

image

image

```bash
curl -so wazuh-agent.pkg https://packages.wazuh.com/4.x/macos/wazuh-agent-4.7.0-1.intel64.pkg && echo -e "WAZUH_MANAGER='10.10.10.10'\nWAZUH_AGENT_GROUP='default'\nWAZUH_AGENT_NAME='agent-name'\nWAZUH_REGISTRATION_PASSWORD='password\"with\"doubleq\\'usds\\\"es'\n" > /tmp/wazuh_envs && sudo installer -pkg ./wazuh-agent.pkg -target /
```

**Comment by Machi3mfl** [comment]
## Commands 

## Api in authd.pass

```
password"with"doubleq\'usds\"es
```

## Password from /config/auth/auth API endpoint

- in this case, the API scape the special characters " and \
```
"password\"with\"doubleq\\'usds\\\"es
```

## Password in command

```bash
wget https://packages.wazuh.com/4.x/apt/pool/main/w/wazuh-agent/wazuh-agent_4.7.0-1_amd64.deb && sudo WAZUH_MANAGER='10.10.10.10' WAZUH_REGISTRATION_PASSWORD=$'password"with"doubleq\\'"'"'usds\"es' dpkg -i ./wazuh-agent_4.7.0-1_amd64.deb

// password"with"doubleq\\'"'"'usds\"es
```

## Linux 

## RPM
```bash
curl -o wazuh-agent-4.4.5-1.x86_64.rpm https://packages.wazuh.com/4.x/yum/wazuh-agent-4.4.5-1.x86_64.rpm && sudo WAZUH_MANAGER='10.10.10.10' WAZUH_REGISTRATION_PASSWORD=$'password"with"doubleq'"'"'usds\"es' rpm -ihv wazuh-agent-4.4.5-1.x86_64.rpm

```

## DEB
```bash
wget https://packages.wazuh.com/4.x/apt/pool/main/w/wazuh-agent/wazuh-agent_4.4.5-1_amd64.deb && sudo WAZUH_MANAGER='10.10.10.10' WAZUH_REGISTRATION_PASSWORD=$'password"with"doubleq\'"'"'usds\"es' dpkg -i ./wazuh-agent_4.4.5-1_amd64.deb

```

# macOS

```bash
curl -so wazuh-agent.pkg https://packages.wazuh.com/4.x/macos/wazuh-agent-4.4.5-1.pkg && echo -e "WAZUH_MANAGER='10.10.10.10'\nWAZUH_REGISTRATION_PASSWORD=$'password\"with\"doubleq\\'usds\\\"es'\n" > /tmp/wazuh_envs && sudo installer -pkg ./wazuh-agent.pkg -target /
```

**Comment by Machi3mfl** [comment]
# Testing E2E

- Use an environment with a real manager or mock the following response

```JSON
{
  "data": {
    "affected_items": [
      {
        "auth": {
          "port": 1515,
          "disabled": "no",
          "remote_enrollment": "yes",
          "use_source_ip": "no",
          "purge": "yes",
          "use_password": "yes",
          "ssl_verify_host": "no",
          "ssl_auto_negotiate": "no",
          "ciphers": "HIGH:!ADH:!EXP:!MD5:!RC4:!3DES:!CAMELLIA:@STRENGTH",
          "ssl_manager_cert": "/var/ossec/etc/sslmanagertest.cert",
          "ssl_manager_key": "/var/ossec/etc/sslmanagertest.key",
          "force": {
            "enabled": "yes",
            "key_mismatch": "yes",
            "disconnected_time": {
              "enabled": "yes",
              "value": 3600
            },
            "after_registration_time": 3600
          }
        },
        "authd.pass": "password\"with\"doubleq\\'usds\\\"es"
      }
    ],
    "total_affected_items": 1,
    "total_failed_items": 0,
    "failed_items": []
  },
  "message": "Active configuration was successfully read in specified node",
  "error": 0
}

```

With the following e2e test, we need to check that the password added in the manager `authd.pass` file will be copied in the agent `authd.pass` file

1- Add the `authd.pass` with the password and enable the `use_password` setting. [https://documentation.wazuh.com/current/user-manual/agent-enrollment/security-options/using-password-authentication.html](https://documentation.wazuh.com/current/user-manual/agent-enrollment/security-options/using-password-authentication.html)

```
password"with"doubleq\'usds\"es
```


2. Go to the Deploy new agent page and fill out the form. (Depending on your OS)

3. Copy the command and run it on your machine. (Replace de 4.7.0 version with the 4.4.5 version in the command)

4. Start the agent and check if the authd.pass file was created inside the agent folder 

**Linux: /var/ossec/etc/authd.pass
macOS: /Library/Ossec/etc/authd.pass
Windows: C:/Programs/ossec-agent/etc/authd.pass**

5. The password added in the manager and agent `authd.pass` file must be equal

**Comment by chantal-kelm** [comment]
Test in macos

With password set to yes but without authd.pass file:

Captura de pantalla 2023-08-08 a la(s) 09 26 27

With password set to yes and with file authd.pass:

Captura de pantalla 2023-08-08 a la(s) 09 35 51

Captura de pantalla 2023-08-08 a la(s) 09 35 30

**Review by jbiset — COMMENTED** [review]
CR: (in progress)

# UI TEST

## :green_circle:  LINUX

Evidence_2_B_LinuxAgent_ONLINE

- **Real password:**  `password"with"doubleq\'usds\"es`

<details>
<summary>
Evidence
</summary>

linux_case_manager_password

</details>

- **API response authd.pass:** ` "password\"with\"doubleq\\'usds\\\"es"`
- **Generated command:** 
`wget https://packages.wazuh.com/4.x/apt/pool/main/w/wazuh-agent/wazuh-agent_4.7.0-1_amd64.deb && sudo WAZUH_MANAGER='192.168.10.197' WAZUH_REGISTRATION_PASSWORD=$'password"with"doubleq\'"'"'usds\"es' WAZUH_AGENT_NAME='LocalLinux' dpkg -i ./wazuh-agent_4.7.0-1_amd64.deb`
<details>
<summary>
Evidence
</summary>

Evidence_1_A_LinuxAgent

Evidence_1_B_LinuxAgent


</details>

- **Agent authd.pass:** `password"with"doubleq\'usds\"es`
<details>
<summary>
Evidence
</summary>

Evidence_2_Installed_LinuxAgent

</details>

## :yellow_circle:  Windows

- **Real password:**  `password"with"doubleq\'usds\"es`

<details>
<summary>
Evidence
</summary>

linux_case_manager_password

</details>

- **API response authd.pass:** ` "password\"with\"doubleq\\'usds\\\"es"`
- **Generated command:** 
`Invoke-WebRequest -Uri https://packages.wazuh.com/4.x/windows/wazuh-agent-4.7.0-1.msi -OutFile ${env.tmp}\wazuh-agent; msiexec.exe /i ${env.tmp}\wazuh-agent /q WAZUH_MANAGER='192.168.10.197' WAZUH_REGISTRATION_PASSWORD=$'password"with"doubleq\'"'"'usds\"es' WAZUH_AGENT_NAME='VirtualWindows' WAZUH_REGISTRATION_SERVER='192.168.10.197' `
<details>
<summary>
Evidence
</summary>

windows_case_wazuh

windows_case_wazuh_B

</details>

- **Agent authd.pass:**  `$passwordwithdoubleq\'usds\es`
<details>
<summary>
Evidence
</summary>

windows_case_agent

</details>

**Comment by Machi3mfl** [comment]
# UI TEST

## :green_circle:  MACOS

image

- **Real password:**  `password"with"doubleq\'usds\"es`

<details>
<summary>
Evidence
</summary>


image


</details>

- **API response authd.pass:** ` "password\"with\"doubleq\\'usds\\\"es"`
- **Generated command:** 
`curl -so wazuh-agent.pkg https://packages.wazuh.com/4.x/macos/wazuh-agent-4.7.0-1.intel64.pkg && echo -e "WAZUH_MANAGER='192.168.0.55'\nWAZUH_AGENT_GROUP='default'\nWAZUH_AGENT_NAME='macos-agent'\nWAZUH_REGISTRATION_PASSWORD='password\"with\"doubleq\\'\"'\"'usds\\\\\\\\\\\"es'\n" > /tmp/wazuh_envs && sudo installer -pkg ./wazuh-agent.pkg -target /`

**To test i changed the wazuh package version to 4.4.5-1 and remove de intel64 extension.**
<details>
<summary>
Evidence
</summary>

image


</details>

- **Agent authd.pass:** `password"with"doubleq\'usds\"es`
<details>
<summary>
Evidence
</summary>



</details>

**Review by jbiset — APPROVED** [review]

**Review by chantal-kelm — APPROVED** [review]
### Test in macos:

Captura de pantalla 2023-08-09 a la(s) 15 31 25
Captura de pantalla 2023-08-09 a la(s) 15 31 03
Captura de pantalla 2023-08-09 a la(s) 15 30 53
Captura de pantalla 2023-08-09 a la(s) 15 59 42
Captura de pantalla 2023-08-09 a la(s) 15 59 59

**Pull request merged**
