### PR TITLE
Fixed paste value on server address selected

### PR DESCRIPTION
**Pull request by Machi3mfl**
Hi Team, 
This PR solves for this issue #4950 

Related issue #4109 

### Check List
- [x] All tests pass
  - [x] `yarn test:jest`
- [x] New functionality includes testing.
- [x] New functionality has been documented.
- [x] Update [CHANGELOG.md](./../CHANGELOG.md)
- [x] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Comment by Machi3mfl** [comment]
## How to test

- Check if the value pasted in the WAZUH_MANAGER param is the IP

https://user-images.githubusercontent.com/6089438/205335368-0a544fc4-6b84-4701-80b7-3633db95053a.mp4

**Review by Tostti — DISMISSED** [review]
Test: ✔️
CR: ✔️

**Review by Desvelao — CHANGES_REQUESTED** [review]
**review**

- Remove the worktree from the files changed
- Add the pull request link to the changelog. As this pull request is a fix of a new feature, add the pull request link to the same entry of the feature

**Comment by Machi3mfl** [comment]
> **review**
> 
> 
> 
> - Remove the worktree from the files changed
> 
> - Add the pull request link to the changelog. As this pull request is a fix of a new feature, add the pull request link to the same entry of the feature

Resolved

**Review by chantal-kelm — APPROVED** [review]
CR: ✅ 
Test: ✅ 

Evidence:

image

**Review by yenienserrano — APPROVED** [review]
LGTM

image

**Review by Desvelao — APPROVED** [review]

**Pull request merged**
