### PR TITLE
[Fix] Code overflows over the line numbers in API Console editor

### LINKED ISSUE #3339: API console text overflows over the line numbers when scrolling to the right.
| Wazuh | Elastic |
| ----- | ------- |
| 4.2   | 7.10     |

**Description**
When you have a long line of text in the API console, wider than the container it's in, a horizontal scroll bar appears.
Using it, makes the text overlap the line numbering column instead of going under it.

**Steps to reproduce**

1. Go to App -> Dev Tools -> API console
2. Write a long line of text
3. Scroll to the right

**Screenshots**
text too long

**Additional context**
The API console from kibana, when a line is too long, breaks it.

### PR DESCRIPTION
**Pull request by Desvelao**
### Description

Fix the code overflows over the line numbers in the API Console editor.

### Test
1. Go to the API Console editor and scroll the left panel (where you can edit the API request) to the right and the text shouldn't overflow the line numbers.

Closes #3339

### CODE REVIEW

**Review by pablomarga — COMMENTED** [review]
CR: :heavy_check_mark: 
Testing: :heavy_check_mark:

**Review by mpRegalado — APPROVED** [review]
CR: LGTM :heavy_check_mark: 
Testing: LGTM :heavy_check_mark:

**Review by frankeros — APPROVED** [review]
LGTM!

**Review by matiasmoreno876 — APPROVED** [review]
CR: LGTM!

**Pull request merged**
