### PR TITLE
Add kbn-dev 7.17.11

### LINKED ISSUE #5623: Compatibility with Elastic 7.17.11
## Description
We need to ensure the UI compatibility with the next version of Elastic v7.17.11.
This update is confirmed, so we need to be aware of potential issues.

For that, we need to:

- [x] Review Elastic's and Kibana's changelog for this version. 
- [x] Identify improvements and potential impact on the UI.
- [x] Develop a testing environment to verify our components would work under this new build.

## Issues
-  _List here the detected issues_

### PR DESCRIPTION
**Pull request by AlexRuiz7**
### Description
We have upgraded Elasticsearch and Kibana to version 7.17.11, and the changes are reflected in issue #5623

### Issues Resolved
#5623

### Evidence
image

### Test
Up the environment and check that it works.

### Check List
- [ ] All tests pass
  - [ ] `yarn test:jest`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [x] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Comment by JuanGarriuz** [comment]
image
image
image

**Review by yenienserrano — APPROVED** [review]
LGTM

**Review by asteriscos — APPROVED** [review]
LGTM :heavy_check_mark:

**Review by jbiset — APPROVED** [review]
LGTM :green_circle:

**Pull request merged**
