### PR TITLE
[Backport 4.5-7.10] Add `rel="noopener noreferrer"` in documentation links 

### PR DESCRIPTION
**Pull request by yenienserrano**
Backport https://github.com/wazuh/wazuh-kibana-app/commit/39d75a7f0d9cb87ad7677148ca1269fdbe70b69b from https://github.com/wazuh/wazuh-kibana-app/pull/5197.

### CODE REVIEW

**Review by Tostti — APPROVED** [review]
# Wazuh dashboard

Legend:
:black_circle:: none
:green_circle:: pass
:yellow_circle:: warning
:red_circle:: fail
:white_circle:: not applicable

## UI

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| Check the value of attributes in changed anchors containing noopener noreferer | :black_circle: | :green_circle: | :black_circle: |

**Details**
<details>
<summary>:green_circle: Check the value of attributes in changed anchors containing noopener noreferer</summary>

Chrome - :black_circle:

Firefox - :green_circle:
imagen
imagen

Safari - :black_circle:

</details>


TEST:✔️
CR:✔️

LGTM

**Review by asteriscos — APPROVED** [review]
CR: :heavy_check_mark: 
Test: :heavy_check_mark: 

Screenshot from 2023-03-08 17-19-51

Screenshot from 2023-03-08 17-18-06

Screenshot from 2023-03-08 17-12-39

Screenshot from 2023-03-08 17-11-30

Screenshot from 2023-03-08 17-09-41

**Review by asteriscos — CHANGES_REQUESTED** [review]
Test: :x:  

There are a few external links that still don't have the `noreferrer` `noopener` attributes:

<details>
<summary> Screenshots </summary>

Screenshot from 2023-03-08 17-47-15

Screenshot from 2023-03-08 17-37-22

Screenshot from 2023-03-08 17-34-31

Screenshot from 2023-03-08 17-31-01


</details>

**Review by asteriscos — APPROVED** [review]
The remaining changes will be added in a new pull request

**Pull request merged**
