### PR TITLE
Replace search bar on Agents

### PR DESCRIPTION
**Pull request by Desvelao**
### Description
This pull request replaces the search bar and table component on Agents.

> It depends on https://github.com/wazuh/wazuh-kibana-app/pull/5442

Additional changes:
- Remove unused code
 
### Issues Resolved
https://github.com/wazuh/wazuh-kibana-app/issues/4312

### Evidence
image
image
image

Table - Agents
Suggestions:
| field | get distinct values | searchable | searchable term |
| --- | --- | --- | --- |
| dateAdd | GET /agents?distinct=true&limit=30&select={field}&sort=+{field}&q={currentValue} |  :white_check_mark: |  |
| id | GET /agents?distinct=true&limit=30&select={field}&sort=+{field}&q={currentValue} |  :white_check_mark: |  :white_check_mark: |
| ip | GET /agents?distinct=true&limit=30&select={field}&sort=+{field}&q={currentValue} |  :white_check_mark: |  :white_check_mark: |
| group | GET /agents?distinct=true&limit=30&select={field}&sort=+{field}&q={currentValue} |  :white_check_mark: |  :white_check_mark: |
| group_config_status | GET /agents?distinct=true&limit=30&select={field}&sort=+{field}&q={currentValue} |  :white_check_mark: |  :white_check_mark: |
| laskKeepAlive | GET /agents?distinct=true&limit=30&select={field}&sort=+{field}&q={currentValue} |  :white_check_mark: |  :white_check_mark: |
| manager | GET /agents?distinct=true&limit=30&select={field}&sort=+{field}&q={currentValue} |  :white_check_mark: |  :white_check_mark: |
|name | GET /agents?distinct=true&limit=30&select={field}&sort=+{field}&q={currentValue} |  :white_check_mark: |  :white_check_mark: |
|node_name | GET /agents?distinct=true&limit=30&select={field}&sort=+{field}&q={currentValue} |  :white_check_mark: |  :white_check_mark: |
|os.name | GET /agents?distinct=true&limit=30&select={field}&sort=+{field}&q={currentValue} |  :white_check_mark: |  :white_check_mark: |
|os.platform | GET /agents?distinct=true&limit=30&select={field}&sort=+{field}&q={currentValue} |  :white_check_mark: |  :white_check_mark: |
|os.version | GET /agents?distinct=true&limit=30&select={field}&sort=+{field}&q={currentValue} |  :white_check_mark: |  :white_check_mark: |
|status | active,disconnected,pending,neved_connected | :white_check_mark: |  :white_check_mark: |
|version | GET /agents?distinct=true&limit=30&select={field}&sort=+{field}&q={currentValue} |  :white_check_mark: |  :white_check_mark: |

### Test

> Use a Wazuh manager

Legend:
:black_circle:: none
:green_circle:: pass
:yellow_circle:: warning
:red_circle:: fail
:white_circle:: not applicable

## UI

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| Agents: For each suggested field, check the value suggestion display results or at least doesn't break | :black_circle: | :black_circle: | :black_circle: |
| Agents: Using a value suggested should allow to run the search | :black_circle: | :black_circle: | :black_circle: |
| Agents: Type a term and run the search should search in each displayed field | :black_circle: | :black_circle: | :black_circle: |
| Agents: Type a simple field search and this should returns the expected results | :black_circle: | :black_circle: | :black_circle: |
| Agents: Type a complex field search and this should returns the expected results | :black_circle: | :black_circle: | :black_circle: |
| Agents: Clicking on the Refresh button should refresh the data | :black_circle: | :black_circle: | :black_circle: |
| Agents: Clicking on the Export formatted button should refresh export the data to CSV | :black_circle: | :black_circle: | :black_circle: |
| Agents: Enable or disable some visible fields, the table should render the visible fields | :black_circle: | :black_circle: | :black_circle: |
| Agents: Enable or disable some visible fields, type a search term and check the query is searching in the visible fields | :black_circle: | :black_circle: | :black_circle: |
| Agents: Clicking on the status KPI from the Status panel should add a filter to the search bar, the table should filters the data | :black_circle: | :black_circle: | :black_circle: |
| Agents: Clicking on the status KPI from the Details panel should add a filter to the search bar, the table should filters the data | :black_circle: | :black_circle: | :black_circle: |
| Modules directory: Clicking on the status KPI from should redirect to the Agents section adding a filter to the search bar, the table should filters the data | :black_circle: | :black_circle: | :black_circle: |

**Details**
<details>
<summary>:black_circle: Agents: For each suggested field, check the value suggestion display results or at least doesn't break</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Agents: Using a value suggested should allow to run the search</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Agents: Type a term and run the search should search in each displayed field</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Agents: Type a simple field search and this should returns the expected results</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Agents: Type a complex field search and this should returns the expected results</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Agents: Clicking on the Refresh button should refresh the data</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Agents: Clicking on the Export formatted button should refresh export the data to CSV</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Agents: Enable or disable some visible fields, the table should render the visible fields</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Agents: Enable or disable some visible fields, type a search term and check the query is searching in the visible fields</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Agents: Clicking on the status KPI from the Status panel should add a filter to the search bar, the table should filters the data</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Agents: Clicking on the status KPI from the Details panel should add a filter to the search bar, the table should filters the data</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Modules directory: Clicking on the status KPI from should redirect to the Agents section adding a filter to the search bar, the table should filters the data</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

### Check List
- [ ] All tests pass
  - [ ] `yarn test:jest`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [x] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Comment by JuanGarriuz** [comment]
# Compare

Legend:
:while_circle: no apply
:green_circle: query and request is valid
:yellow_circle: there are some minor problem/s or considerations
:red_circle: there is a major problem. The request can not be done, the query translation has errors, etc...

##Agents Search Bar
| query type | query (NEW) | OLD | NEW | Commnent |
| --- | --- | --- | --- | --- |

**Comment by Desvelao** [comment]
# Aclaration

> | query type | query (NEW) | OLD | NEW | Commnent |
> | --- | --- | --- | --- | --- |
> | field | configSum=ab73af41699f13fdd81903b5f23d8d00 | 🟡 | 🟡  | OLD: Query show results, but it isn't render. NEW: configSum isn't a valid field | 
> | field | mergedSum=4a8724b20dee0124ff9656783c490c4e | 🟡 | 🟡  | OLD: Query show results, but it isn't render. NEW: mergedSum isn't a valid field |

In the old search bar, the fields `configSum` and `mergedSum` are suggested in the search bar, but these values can not be seen in the table. The visibility of these fields can not be enabled or disabled.

In the implementation of the new search bar, these fields were removed from the suggestions because these are not displayed in the UI, so it seems strange this possibility.

We could add the capability to add the filters related to these fields and add them to be rendered in the table too.

OLD
- Field suggestions: `configuSum` and `mergedSum` are present to filter
image

- `configSum` and `mergedSum` are not available fields to render in the table.
image

NEW
- Field suggestions: `configuSum` and `mergedSum` are not present to filter
image

- `configSum` and `mergedSum` are not available fields to render in the table.
image

**Comment by asteriscos** [comment]
### Test
Legend:
:black_circle:: none
:green_circle:: pass
:yellow_circle:: warning
:red_circle:: fail
:white_circle:: not applicable

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| Agents: For each suggested field, check the value suggestion display results or at least doesn't break | :black_circle: | :black_circle: | :black_circle: |
| Agents: Using a value suggested should allow to run the search | :black_circle: | :black_circle: | :black_circle: |
| Agents: Type a term and run the search should search in each displayed field | :black_circle: | :black_circle: | :black_circle: |
| Agents: Type a simple field search and this should returns the expected results | :black_circle: | :black_circle: | :black_circle: |
| Agents: Type a complex field search and this should returns the expected results | :black_circle: | :black_circle: | :black_circle: |
| Agents: Clicking on the Refresh button should refresh the data | :black_circle: | :black_circle: | :black_circle: |
| Agents: Clicking on the Export formatted button should refresh export the data to CSV | :black_circle: | :black_circle: | :black_circle: |
| Agents: Enable or disable some visible fields, the table should render the visible fields | :black_circle: | :black_circle: | :black_circle: |
| Agents: Enable or disable some visible fields, type a search term and check the query is searching in the visible fields | :black_circle: | :black_circle: | :black_circle: |
| Agents: Clicking on the status KPI from the Status panel should add a filter to the search bar, the table should filters the data | :black_circle: | :black_circle: | :black_circle: |
| Agents: Clicking on the status KPI from the Details panel should add a filter to the search bar, the table should filters the data | :black_circle: | :black_circle: | :black_circle: |
| Modules directory: Clicking on the status KPI from should redirect to the Agents section adding a filter to the search bar, the table should filters the data | :black_circle: | :black_circle: | :black_circle: |

**Details**
<details>
<summary>:black_circle: Agents: For each suggested field, check the value suggestion display results or at least doesn't break</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Agents: Using a value suggested should allow to run the search</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Agents: Type a term and run the search should search in each displayed field</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Agents: Type a simple field search and this should returns the expected results</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Agents: Type a complex field search and this should returns the expected results</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Agents: Clicking on the Refresh button should refresh the data</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Agents: Clicking on the Export formatted button should refresh export the data to CSV</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Agents: Enable or disable some visible fields, the table should render the visible fields</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Agents: Enable or disable some visible fields, type a search term and check the query is searching in the visible fields</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Agents: Clicking on the status KPI from the Status panel should add a filter to the search bar, the table should filters the data</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Agents: Clicking on the status KPI from the Details panel should add a filter to the search bar, the table should filters the data</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Modules directory: Clicking on the status KPI from should redirect to the Agents section adding a filter to the search bar, the table should filters the data</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

**Comment by Tostti** [comment]
:black_circle:: none
:green_circle:: pass
:yellow_circle:: warning
:red_circle:: fail
:white_circle:: not applicable

## UI

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| Agents: For each suggested field, check the value suggestion display results or at least doesn't break | :black_circle: | :black_circle: | :black_circle: |
| Agents: Using a value suggested should allow to run the search | :black_circle: | :black_circle: | :black_circle: |
| Agents: Type a term and run the search should search in each displayed field | :black_circle: | :black_circle: | :black_circle: |
| Agents: Type a simple field search and this should returns the expected results | :black_circle: | :black_circle: | :black_circle: |
| Agents: Type a complex field search and this should returns the expected results | :black_circle: | :black_circle: | :black_circle: |
| Agents: Clicking on the Refresh button should refresh the data | :black_circle: | :black_circle: | :black_circle: |
| Agents: Clicking on the Export formatted button should refresh export the data to CSV | :black_circle: | :black_circle: | :black_circle: |
| Agents: Enable or disable some visible fields, the table should render the visible fields | :black_circle: | :black_circle: | :black_circle: |
| Agents: Enable or disable some visible fields, type a search term and check the query is searching in the visible fields | :black_circle: | :black_circle: | :black_circle: |
| Agents: Clicking on the status KPI from the Status panel should add a filter to the search bar, the table should filters the data | :black_circle: | :black_circle: | :black_circle: |
| Agents: Clicking on the status KPI from the Details panel should add a filter to the search bar, the table should filters the data | :black_circle: | :black_circle: | :black_circle: |
| Modules directory: Clicking on the status KPI from should redirect to the Agents section adding a filter to the search bar, the table should filters the data | :black_circle: | :black_circle: | :black_circle: |

**Details**
<details>
<summary>:black_circle: Agents: For each suggested field, check the value suggestion display results or at least doesn't break</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Agents: Using a value suggested should allow to run the search</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Agents: Type a term and run the search should search in each displayed field</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Agents: Type a simple field search and this should returns the expected results</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Agents: Type a complex field search and this should returns the expected results</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Agents: Clicking on the Refresh button should refresh the data</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Agents: Clicking on the Export formatted button should refresh export the data to CSV</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Agents: Enable or disable some visible fields, the table should render the visible fields</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Agents: Enable or disable some visible fields, type a search term and check the query is searching in the visible fields</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Agents: Clicking on the status KPI from the Status panel should add a filter to the search bar, the table should filters the data</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Agents: Clicking on the status KPI from the Details panel should add a filter to the search bar, the table should filters the data</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Modules directory: Clicking on the status KPI from should redirect to the Agents section adding a filter to the search bar, the table should filters the data</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

**Review by Tostti — APPROVED** [review]
TEST:✔️
CR:✔️

LGTM

**Review by Tostti — DISMISSED** [review]

**Review by asteriscos — DISMISSED** [review]

**Review by Tostti — APPROVED** [review]

**Pull request merged**
