### PR TITLE
Added toast with a refresh button

### LINKED ISSUE #2954: Refresh index pattern fields doesn´t apply until the page is reloaded
Hi team this issue is related to the Amazon AWS and GCP modules. When you add data to this modules a refresh of the index pattern is needed so when you enter to any of this modules a toast shows up saying that `the index pattern was refreshed succesfully` but it is not true. This refresh is not applied until you refresh the whole page.
Captura de pantalla 2021-02-10 a las 12 51 11

https://user-images.githubusercontent.com/46006326/107507060-4fef7f80-6b9f-11eb-91b9-6f329b1a5335.mov

### PR DESCRIPTION
**Pull request by asteriscos**
Hi team, this fixes:
**Refresh index pattern fields doesn´t apply until the page is reloaded**

Adds a custom toast with a reload button.

closes #2954

### CODE REVIEW

**Comment by Desvelao** [comment]
I tested the PR and the toast is displayed with the button to reload the page. The button works, and the visualizations are displayed after new fields (adding sample data) are added.

There a rare behavior and I am not sure if this could be a problem, but the toast with the message is displayed even though no new field has been added. If you go to `Modules` > `Amazon AWS` the toast is sometimes displayed Could someone test it too?

Screenshot
image

**Comment by Desvelao** [comment]
The change in the `CHANGELOG.md` is missing. You should add it.

**Review by sortizowlh — COMMENTED** [review]
Checked!
Message is shown even though there is no new data

**Review by pablomarga — APPROVED** [review]
I have tested it and everything seems to be ok. Good job! LGTM!

**Comment by asteriscos** [comment]
You were right. In the AWS view when it refreshed the `index-pattern` if there were no alerts with AWS fields, the app didn't actually load those fields. So I made a way to manually load predefined known index-pattern fields and that way it avoids the eternal field load.

**Comment by asteriscos** [comment]
Added changes to `CHANGELOG.md`

**Review by pablomarga — APPROVED** [review]
LGTM!

**Pull request merged**
