### PR TITLE
Cherry pick #3397 into 4.3 7.10

### PR DESCRIPTION
**Pull request by frankeros**
Hi team this is the cherry-pick of #3397 into 4.3-7.10

### CODE REVIEW

**Review by Desvelao — APPROVED** [review]
**review**:
Code Review ✅

**Review by pablomarga — APPROVED** [review]
CR: :heavy_check_mark:

**Review by Machi3mfl — APPROVED** [review]
CR ✅

**Review by gabiwassan — APPROVED** [review]
LGTM! 👍🏼

**Pull request merged**
