### PR TITLE
spelling fix

### PR DESCRIPTION
**Pull request by branchnetconsulting**

### CODE REVIEW

**Comment by JuanjiJG** [comment]
Hello @branchnetconsulting,

Could you please change the destination branch into the `3.2` one? Our `master` branch is the stable one, only updated after releasing a new Wazuh app package.

Thanks for your contribution!

Regards,
Juanjo

**Comment by jesusgn90** [comment]
Hi guys, the problem is not the branch, I've changed the branch for your information guys. But we cannot merge from master to 3.2, any case I'm going to commit to the 3.2 your fix Kevin. Next time use our development branch to fork your branch, thanks in advance.

Regards,
Jesús

**Comment by branchnetconsulting** [comment]
Hi Jesús,

I'd be happy to make a point to use a different branch next time.  What
exactly do you mean by "the development branch" though?  I see lots of
branches that it might be.

Kevin

**Comment by jesusgn90** [comment]
Hello again Kevin, you are right. I'm going to be a bit clearer this time:

- Our master branch is always behind our development branches.
- Our top development branch is always a branched named MAJOR.MINOR according to current Wazuh stable packages.
  - This means you'll see long time the branch 3.2 as our development branch. Once the 3.3.0 is published, we'll create a new branch named 3.3 which will include 3.3.x versions of Wazuh

Usually our team, take the branch 3.2, fork a new branch using a descriptive name such 3.2-fix-agents-search-bar, once the fix or the new feature is tested we create a pull request from 3.2-fix-agents-search-bar to 3.2.

On the other hand, whenever we have a new App package it means there is a new tag at some point of our current development branch, once the package is release we merge commits up to that tag to the master branch.

Hope now you understand it better, regards!

Jesús

**Comment by branchnetconsulting** [comment]
Thanks, that definitely helps clear things up for me.  I've been wanting to
understand the relationship between your Github branches better.

Kevin

**Comment by jesusgn90** [comment]
Ok Kevin, I'm glad you understand it better with the above description. Any case we are always happy to help or explain you Wazuh things. 

Regards,
Jesús

**Pull request closed without merging**
