### PR TITLE
[Backport 4.4-7.10] Update dependencies 

### PR DESCRIPTION
**Pull request by yenienserrano**
Backport 5585d8c1ac471a9023e9dd9c7c0874f037c7ee71 from #5062.

### CODE REVIEW

**Comment by yenienserrano** [comment]
with kibana version 7.10.2 you can not install pdfmake version 0.2.7

image

**Review by asteriscos — APPROVED** [review]
- [x] Test build 
- [x] Test app
- [x] Test package installation

**Review by Desvelao — APPROVED** [review]
**review**:

:green_circle: code
:green_circle: test

**Comment by Desvelao** [comment]
# Changes

Moved the deletion of `pug-loader` dependency to the `Removed` section in the changelog

**Review by asteriscos — APPROVED** [review]

**Pull request merged**
