### PR TITLE
5245 wazuh api usage modules

### PR DESCRIPTION
**Pull request by yenienserrano**
### Description
Corrects the limit of the agent exploration table in the dashboards, since when turning the page the limit was increased.
 
### Issues Resolved
- #5245

### Evidence
<details><summary>Screenshot</summary>

image

image

</details> 

### Test
1. Navegate to some dashboard
2. Click on Explore agent
3. Turn the page
4. See that the limit does not change

### Check List
- [x] All tests pass
  - [x] `yarn test:jest`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [X] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Comment by Desvelao** [comment]
# Test

Legend:
:black_circle:: none
:green_circle:: pass
:yellow_circle:: warning
:red_circle:: fail
:white_circle:: not applicable

## UI

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| Use the pagination of Explore agent modal, and the limit property in the request payload should have the same value that the items per page | :green_circle: | :black_circle: | :black_circle: |

**Details**
<details>
<summary>:green_circle: Use the pagination of Explore agent modal, and the limit property in the request payload should have the same value that the items per page</summary>

Chrome - :green_circle:
image

Firefox - :black_circle:

Safari - :black_circle:

</details>

**Review by Desvelao — APPROVED** [review]
**review**

:green_circle: code
:green_circle: test

**Review by asteriscos — APPROVED** [review]
Test: :heavy_check_mark: 
CR: :heavy_check_mark: 

The page limit is always the same.

image

**Comment by asteriscos** [comment]
This pull request is closed because a [refactor in the search bar](https://github.com/wazuh/wazuh-kibana-app/issues/4312) will make this fix obsolete.

**Pull request closed without merging**
