### PR TITLE
Columns are added to the report

### PR DESCRIPTION
**Pull request by yenienserrano**
**Description**

The vulnerability report columns have been changed

**Issues Resolved**

Improve Wazuh report for vulnerability detector module [#3603](https://github.com/wazuh/wazuh-kibana-app/issues/3603)

**Test**

Generate a vulnerability report without having selected any agent

Check List

- [x] Changing columns in the report

image

### CODE REVIEW

**Comment by Desvelao** [comment]
**review**:
Code ✅ 
Testing :x:

I found a problem with the render of the table, the width of the table exceeds the page.

image

**Comment by eze9252** [comment]
Code :heavy_check_mark: 
Testing :heavy_check_mark:

**Review by eze9252 — APPROVED** [review]

**Review by Desvelao — APPROVED** [review]
**review**
Code ✅

**Review by gabiwassan — APPROVED** [review]
LGTM

**Review by asteriscos — APPROVED** [review]
CR: :heavy_check_mark: 
Test: :heavy_check_mark:

**Pull request merged**
