### PR TITLE
Fixed that alerts table is empty when switching pinned agents

### PR DESCRIPTION
**Pull request by CPAlejandro**
Hi guys,
We have fixed a bug that caused alerts not to be displayed if you switch from one pinned agent to another in the explore agent submenu.

### CODE REVIEW

**Review by frankeros — COMMENTED** [review]
I tested it, and when you try to apply a filter from Mitre flyout the filter is not be applied.
image

**Comment by asteriscos** [comment]
Refactor of `discover.tsx` in progress. I'm merging filter managers to avoid inconsistencies.

**Comment by frankeros** [comment]
I found another error testing it, adding a filter from **Recent Events** the filter is not applied and the console shows an error.

image

Steps to reproduce it: 
1. Go to MITRE ATT&CK / Frameworks 
2. Open the detail of a technique with events
3. Expand some item in Recent Events
4. Apply some filter from the table value

**Comment by asteriscos** [comment]
`Views to test this PR:`

- Security Events
- Flyout Framework (Mitre)
- Flyout Inventory (Integrity Monitoring)
- Flyout Controls (GDPR)

**Review by frankeros — APPROVED** [review]
tested locally :heavy_check_mark: 

Outstanding work! :tada:

**Pull request merged**
