### PR TITLE
Fix routes resolvers circular redirections  - infinite loop

### LINKED ISSUE #4028: Circular re-directions - Infinite loop
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.2   | 7.x     | 4xxx | Basic, ODFE, Xpack |

| Browser |
| ------- |
| Chrome, Firefox, Safari, etc|

**Description**
There are some cases in which an infinite redirection loop is produced. The app router should have a circuit breaker to avoid it and also those cases should be identified and fixed.

- [x] Identify which scenarios produce a circular redirection
- [x] Fix looping scenarios

Related to #3929

### PR DESCRIPTION
**Pull request by asteriscos**
## Description

This PR fixes circular redirections in the router resolvers when a service failure, such as session expired or service unavailable, causes an exception and the app tries to recover itself by redirecting to health-check and/or settings to setup an API or show a blank-screen to display an error message. 

This has been tested with 3 cases:
- No Wazuh API is configured in `wazuh.yml`
- Wazuh **app is idle** for more than an hour
- Renaming `kibana.yml` to make the service unavailable once the app is already running

This closes #4028 and https://github.com/wazuh/wazuh-kibana-app/issues/3929

### CODE REVIEW

**Comment by Mayons** [comment]
Testing in progress

**Comment by Mayons** [comment]
Test OK. 
Couldn't reproduce circular redirections on the app

**Review by yenienserrano — APPROVED** [review]
Test: ✔️ 
CR: ✔️

**Review by matiasmoreno876 — APPROVED** [review]
CR OK ✅ 
TEST OK ✅

**Pull request merged**
