### PR TITLE
Sanitize report's inputs and usernames - 4.2

### PR DESCRIPTION
**Pull request by asteriscos**
# Description

This PR adds parameter validation to the reports endpoints, applies https://github.com/wazuh/wazuh-kibana-app/pull/4330 changes to Wazuh 4.2

# Changes

- Add parameter validation to the reporting endpoints.
- Removed some parameters in the reporting endpoints.
- Build the report name in the backend.
- Add testing with Jest.
- Add tests with invalid parameters in the reporting endpoints.

# Test

- Do requests to the reports endpoints with unexpected / forbidden parameters using some tools as cURL or Postman.
- Check that each kind of report can be generated as expected:
  - Modules (with agent selected, without agent selected, changing the type of selected time range, etc...)
  - Group
  - Agent configuration
  - Agent inventory

### CODE REVIEW

**Comment by Desvelao** [comment]
# Changes
Add entry to changelog and bump revision to 4209

**Review by Desvelao — APPROVED** [review]
**review**
code :heavy_check_mark: 
test :heavy_check_mark:

**Comment by Desvelao** [comment]
> Add the MD5 dependency with:
> 
> ```shell
> npm install md5 --save
> ```

# Changes
Add the project dependency of `md5`.

**Review by AlexRuiz7 — CHANGES_REQUESTED** [review]
Test:
- `GET /reports` - 🟢 
- `GET /reports/<report-name>.pdf` - 🟢 
- `DELETE /reports/<report-name>.pdf` - 🟢 
- `POST /reports/groups/:groupId` - 🔴 

    image

    This is probably the same issue described here #4348
- `POST /reports/agents/:agentId/inventory` - 🟢 
- `POST /reports/modules/general` - 🟢 
- `POST /reports/agents/:agentId` - 🟢

**Comment by AlexRuiz7** [comment]
This patch won't be included in 4.2 after all.

**Pull request closed without merging**
