### PR TITLE
Fix wrong filter button in Management > Decoders > Manage decoders files

### LINKED ISSUE #5812: Fix the filter button in Management > Decoders > Manage decoders files
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.x   | 7.x     | 4xxx | Basic, ODFE, Xpack |

| Browser |
| ------- |
| Chrome, Firefox, Safari, etc|

**Description**
The Manage decoders files section of Management > Decoders has defined a button related to Rules instead of Decoders.

The filter and text are wrong.

**Steps to reproduce**
1. Navigate to Management > Decoders > Manage decoders files
2. See the button that displays `Custom rules`

**Screenshots**
image

### PR DESCRIPTION
**Pull request by Desvelao**
### Description
This pull requests fixes a filter button in Management > Decoders > Manage decoders files.

Changes:
- label and filter of button

Side changes:
- Removed unused `buttonOptions` property in Management > Rules
 
### Issues Resolved
#5812

### Evidence
image
image

### Test
[Provide instructions to test this PR]

### Check List
- [ ] All tests pass
  - [ ] `yarn test:jest`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [x] Update [CHANGELOG.md](./../CHANGELOG.md)
- [x] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Comment by JuanGarriuz** [comment]
### Test UI

image
image

**Comment by JuanGarriuz** [comment]
LGTM

**Review by JuanGarriuz — APPROVED** [review]
LGTM

**Review by asteriscos — APPROVED** [review]
Test: :heavy_check_mark: 
CR: :heavy_check_mark: 

image

**Pull request merged**
