### PR TITLE
fix render size elements in agents preview

### LINKED ISSUE #3334: Api name cuts off if the name of the api is too long
| Wazuh | Elastic |
| ----- | ------- | 
| 4.2   | 7.x     |

**Description**
If there is more than one API registered, and one of them has a name too long, it cuts off without any elipsis.

**Steps to reproduce**

1. Register a second API in `kibana/data/wazuh/config/wazuh.yml`, it doesn't need to be active
2. Set the name of the active API (`default` if no other is set) to a very long name
3. Open the app

**Screenshots**
image
image

**Additional context**
It's possible that a similar issue happens to the Index Pattern selector but I have not tested it yet, worth looking into.

### PR DESCRIPTION
**Pull request by eze9252**
Hi team, this resolves:

- elements on the agent preview page not render correctly in lows widths

How to Test:

- go to the agents preview
- lower the page width
- check if elements render correctly

Closes [#3354](https://github.com/wazuh/wazuh-kibana-app/issues/3354)

### CODE REVIEW

**Review by matiasmoreno876 — APPROVED** [review]
LGTM!

**Review by mpRegalado — CHANGES_REQUESTED** [review]
When the size of the screen falls on some intermediate value it overflows to the side
Peek 2021-07-08 14-04

**Comment by eze9252** [comment]
> When the size of the screen falls on some intermediate value it overflows to the side
> Peek 2021-07-08 14-04


https://user-images.githubusercontent.com/36004787/124934830-63dfc600-e005-11eb-99b1-1b8404401c8f.mp4

**Comment by mpRegalado** [comment]
> @mpRegalado Do you clean cache? Because I see ok...
> https://user-images.githubusercontent.com/36004787/124934830-63dfc600-e005-11eb-99b1-1b8404401c8f.mp4

I just tried it on a fresh installation with a incognito window to the same effect.

**Pull request closed without merging**
