### PR TITLE
[Backport 4.5-7.10] Fix macos apple install command

### PR DESCRIPTION
**Pull request by Machi3mfl**
Backpor b38ed8983ed3cdec7e4a873c56e4274b169f09de from  #5470

### CODE REVIEW

**Review by Tostti — DISMISSED** [review]
imagen
TEST:✔️
CR:✔️

LGTM

**Comment by Desvelao** [comment]
# Changes

- Changed the pull request entry on changelog
- Fixed release version titles on changelog

**Comment by Desvelao** [comment]
# Wazuh dashboard

Legend:
:black_circle:: none
:green_circle:: pass
:yellow_circle:: warning
:red_circle:: fail
:white_circle:: not applicable

## UI

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| The command in the deployment guide to starting a new macOS agent must use `sudo` | :green_circle: | :green_circle: | :black_circle: |

**Details**
<details>
<summary>:green_circle: The command in the deployment guide to starting a new macOS agent must use `sudo`</summary>

Chrome - :green_circle:
image

Firefox - :green_circle:
image

Safari - :black_circle:

</details>

**Review by Tostti — APPROVED** [review]
imagen
TEST:✔️
CR:✔️

LGTM

**Pull request merged**
