### PR TITLE
Fixed agents details card style

### LINKED ISSUE #3837: Wrong width in Agents details card when agents name is too long
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.3   | 7.10.2     | 4.3 | Basic, ODFE, Xpack |

| Browser |
| ------- |
| Chrome, Firefox, Safari, etc|

**Description**
Wrong width in Agents details card when agents name is too long. 

Screen Shot 2022-02-14 at 15 48 47

### PR DESCRIPTION
**Pull request by Machi3mfl**
Hi Team,
This PR resolves a wrong width from the agent's details card. 
Because of that, In some resolutions, the agent's evolution visualization is off the screen.

Closes #3837

### CODE REVIEW

**Review by yenienserrano — APPROVED** [review]
Test: :heavy_check_mark: 
CR: :heavy_check_mark:

**Review by matiasmoreno876 — APPROVED** [review]
CR OK ✅ 
TEST OK ✅ 

image

**Comment by Mayons** [comment]
Test OK
image
image

**Comment by Mayons** [comment]
image
Test OK  after @Desvelao changes

**Pull request merged**
