### PR TITLE
Wrong redirect after login

### PR DESCRIPTION
**Pull request by Machi3mfl**
Hi Team,
This PR resolve the wrong redirect after login.
Now, always the user is redirected to overview.
#3694

### CODE REVIEW

**Review by CPAlejandro — COMMENTED** [review]
Changelog is missing

**Review by CPAlejandro — APPROVED** [review]
CR: LGTM!

**Review by gabiwassan — APPROVED** [review]
LGTM! 🚀

**Comment by matiasmoreno876** [comment]
**TEST:** 

> Safari Browser

Safari-browser

> Firefox Browser

Firefox-browser

> Chrome Browser

Chrome-browser

> Brave Browser

Brave-browser

**Pull request merged**
