### PR TITLE
fix error message in conf managment and add test

### LINKED ISSUE #3340: Internal server error when fetching some unavailable information
| Wazuh | Elastic |
| ----- | ------- |
| 3.x   | 6.x     |

**Description**
When visiting the Management -> Configuration section, some menus show internal server errors in the console when opened, and the data they should show is displayed as "Error" and not as "not available". This could lead to confusion thinking there is something wrong with the connection rather than the settings.

**Steps to reproduce**

1. Go to Management -> Configuration
2. Click on Alerts or Integrations or Agentless
3. See error

**Screenshots**
image

### PR DESCRIPTION
**Pull request by eze9252**
Hi Team, this resolve:

Change of message when API fails (not because of server problem) or does not bring information of certain configuration.

### Tests
- Review the message in a Wazuh manager configuration for `Alerts > Email alerts` (It could have more configurations that could be displaying the same message due to the same problem in the API response)

Closes #3340

### CODE REVIEW

**Comment by Desvelao** [comment]
**issue**: When retrieving some configuration as the emails related, the request to the API endpoint reply with a failed response. 
Example of failed request:

Wazuh API Endpoint: `/cluster/manager-node/configuration/mail/alerts`
Response:
```json
{"statusCode":500,"error":"Internal Server Error","message":"3013 - Error connecting with socket"}
```
**suggestion**: Maybe we could manage this specific error and show a more precise message instead of the message changed in the PR: `There was a problem while fetching the configuration for this section. It may be a server problem or the configuration doesn't exist.` Anyways, the generic suggested solution in the PR looks good too.

**Comment by Desvelao** [comment]
**review**:
CR: ✅

**Review by Desvelao — APPROVED** [review]

**Comment by Desvelao** [comment]
@eze9252 add the change to the changelog file

**Review by pablomarga — APPROVED** [review]
Testing: :heavy_check_mark: 
CR: :heavy_check_mark:

**Pull request merged**
