### PR TITLE
Fix password input in deploy new agent section

### LINKED ISSUE #5093: The "Deploy a new agent" page breaks if password authentication is enabled
| Wazuh | Rev  |
| ----- | ---- |
| 4.4.0   | 4400-alpha2 |

| Browser |
| ------- |
| Firefox|

**Description**
Enabling password authentication for agent enrollment breaks the "Deploy a new agent" page. 

**Steps to reproduce**
1. Install Wazuh v4.4.0-alpha2 using the Wazuh installation assistant.
```
 curl -sO https://packages-dev.wazuh.com/4.4/wazuh-install.sh && sudo bash ./wazuh-install.sh -a
```
2. Edit ``/var/ossec/etc/ossec.conf`` and enable password authentication. 
```
<auth>
  <use_password>yes</use_password>
</auth>
```
3. Set your password. 
```
echo "SECRET" > /var/ossec/etc/authd.pass
```
4. Change the ``authd.pass`` file permissions and ownership.
```
chmod 640 /var/ossec/etc/authd.pass
chown root:wazuh /var/ossec/etc/authd.pass
```
5. Restart your Wazuh manager. 
```
systemctl restart wazuh-manager
```
6. Enter the app menu and click on **Agents** > **Deploy a new agent**.  See that the page is broken as shown below. 

image

**Note**: If password authentication is enabled without providing a password, the "Deploy a new agent" page shows a field for entering the password and breaks as soon as you type something.

registration_password

### PR DESCRIPTION
**Pull request by chantal-kelm**
### Description

The following use cases have been fixed:

When a user enables authentication and sets a default password

When a user enables authentication and enters a password at login
 
### Issues Resolved

#5093 

### Evidence

When a user enables authentication and sets a default password:

image (7)
image (8)

When a user enables authentication and enters a password at login:

image (5)
image (8)
image (9)

Fixed the 'textToCopy' error displayed in the console:

image

### For the first case:

add these lines to the imposter's wazuh-config.yml file:

 ```
 - method: GET
    path: /agents/000/config/auth/auth
    response:
      statusCode: 200
      staticFile: ossec/ossec.json
```

Create a ossec folder with a ossec.json file where you are going to put these lines of code:

```
{
    "data": {
      "authd.pass":"hola",
      "auth": {
        "port": 1515,
        "disabled": "no",
        "remote_enrollment": "yes",
        "ipv6": "no",
        "use_source_ip": "no",
        "purge": "yes",
        "use_password": "yes",
        "ssl_verify_host": "no",
        "ssl_auto_negotiate": "no",
        "ciphers": "HIGH:!ADH:!EXP:!MD5:!RC4:!3DES:!CAMELLIA:@STRENGTH",
        "ssl_manager_cert": "/var/ossec/etc/sslmanager.cert",
        "ssl_manager_key": "/var/ossec/etc/sslmanager.key",
        "key_request": {
          "enabled": "no"
        },
        "force": {
          "enabled": "yes",
          "key_mismatch": "yes",
          "disconnected_time": {
            "enabled": "yes",
            "value": 3600
          },
          "after_registration_time": 3600
        }
      }
    },
    "error": 0
  }
```
   
### For the second case:

* Remove this line from the ossec.json file: `"authd.pass": "hola",`

*Go to the deploy new agent section.

 ### First case:

* Make the configuration in the imposter mentioned for case 1.
* Check that the 'Wazuh password' input does not appear in the deploy new agent section.
* Control that depending on whether the switch is activated or not the hidden password is shown with **** or the previously defined password is shown.
* Try to choose HP, Solaris or Alpine, check that the variable WAZUH_REGISTRATION_PASSWORD='hello' does not appear in the install command and that the 'show password' switch does not appear either.
image

### Second case:

* Perform the configuration in the impostor mentioned for case 2.
* Check that the 'Wazuh password' entry appears in the deploy new agent section and that you can enter a password without having selected an os yet.
* Check that depending on whether the switch is activated or not the hidden password is shown with **** or the password you typed in is shown.
* Choose some operating system other than hp, alpine or solaris put a password, check that the hide password switch works fine.
* Choose some operating system other than HP, Alpine or Solaris set a password, check that the password hiding switch works fine, now choose HP, Solaris or Alpine check that the ui is not broken.
* Try choosing hp, solaris or alpine, the password input and the switch should not appear.
image

### Check List
- [ ] All tests pass
  - [ ] `yarn test:jest`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [ ] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Review by asteriscos — CHANGES_REQUESTED** [review]
Test: :x: 

With some of the operating systems works, but when I choose Solaris it throws an exception:

Screenshot from 2023-01-10 18-39-21
Screenshot from 2023-01-10 18-39-45

**Comment by Desvelao** [comment]
> Test: x
> 
> With some of the operating systems works, but when I choose Solaris it throws an exception:
> 
> Screenshot from 2023-01-10 18-39-21 Screenshot from 2023-01-10 18-39-45

Good catch! I think the problem is related to the command used to deploy and Solaris agent doesn't use the password deployment variable and there is an error when try to match the expected string in the command.

I think the problem could be happening for:
- Solaris
- HP-UX
- Alpine

If this is the case, we must fix the function that obfuscates the password.

I will check it.

**Comment by Desvelao** [comment]
> > Test: x
> > With some of the operating systems works, but when I choose Solaris it throws an exception:
> > Screenshot from 2023-01-10 18-39-21 Screenshot from 2023-01-10 18-39-45
> 
> Good catch! I think the problem is related to the command used to deploy and Solaris agent doesn't use the password deployment variable and there is an error when trying to match the expected string in the command.
> 
> I think the problem could be happening for:
> 
> * Solaris
> * HP-UX
> * Alpine
> 
> If this is the case, we must fix the function that obfuscates the password.
> 
> I will check it.

I confirm it. It breaks for Alpine, HP-UX and Alpine.

The logic to obfuscate the password must not be done for operating systems that don't support the `WAZUH_REGISTRARTION_PASSWORD` variable. We could fix the method that obfuscates the password or avoid this method is executed for these operating systems.

**Comment by chantal-kelm** [comment]
> Test: ❌
> 
> With some of the operating systems works, but when I choose Solaris it throws an exception:
> 
> Screenshot from 2023-01-10 18-39-21 Screenshot from 2023-01-10 18-39-45

Fixed Solaris, HP and Alpine password input

**Comment by chantal-kelm** [comment]
> > > Test: x
> > > With some of the operating systems works, but when I choose Solaris it throws an exception:
> > > Screenshot from 2023-01-10 18-39-21 Screenshot from 2023-01-10 18-39-45
> > 
> > 
> > Good catch! I think the problem is related to the command used to deploy and Solaris agent doesn't use the password deployment variable and there is an error when trying to match the expected string in the command.
> > I think the problem could be happening for:
> > 
> > * Solaris
> > * HP-UX
> > * Alpine
> > 
> > If this is the case, we must fix the function that obfuscates the password.
> > I will check it.
> 
> I confirm it. It breaks for Alpine, HP-UX and Solaris.
> 
> The logic to obfuscate the password must not be done for operating systems that don't support the `WAZUH_REGISTRARTION_PASSWORD` variable. We could fix the method that obfuscates the password or avoid this method is executed for these operating systems.

Fixed Solaris, HP and Alpine password input

**Review by asteriscos — APPROVED** [review]
CR: :heavy_check_mark: 
Test: :heavy_check_mark: 

### Without password
Peek 2023-01-11 18-52

### With password
Peek 2023-01-11 18-37

**Review by asteriscos — APPROVED** [review]
Test: :heavy_check_mark: 

screencapture-localhost-5601-app-wazuh-2023-01-12-09_02_06

**Review by Desvelao — APPROVED** [review]
**review**:

# Kibana 7.10

Legend:
:black_circle:: none
:green_circle:: passed
:red_circle:: failed
:yellow_circle:: warning
:white_circle:: not applicable

| Test | Chrome | Package |
| --- |  --- | --- |
| Check that the 'Wazuh password' input does not appear in the deploy new agent section. | :black_circle: | Kibana 7.10 |
| Control that depending on whether the switch is activated or not the hidden password is shown with **** or the previously defined password is shown. | :green_circle: | Kibana 7.10 |
| Try to choose HP, Solaris or Alpine, check that the variable WAZUH_REGISTRATION_PASSWORD='hello' does not appear in the install command and that the 'show password' switch does not appear either. | :green_circle: | Kibana 7.10 |
| Check that the 'Wazuh password' entry appears in the deploy new agent section and that you can enter a password without having selected an os yet. | :green_circle: | Kibana 7.10 |
| Check that depending on whether the switch is activated or not the hidden password is shown with **** or the password you typed in is shown | :green_circle: | Kibana 7.10 |
| Choose some operating system other than hp, alpine or solaris put a password, check that the hide password switch works fine | :green_circle: | Kibana 7.10 |
| Choose some operating system other than HP, Alpine or Solaris set a password, check that the password hiding switch works fine, now choose HP, Solaris or Alpine check that the ui is not broken. | :green_circle: | Kibana 7.10 |
| Try choosing hp, solaris or alpine, the password input and the switch should not appear. | :black_circle: | Kibana 7.10 |


**Details**
<details>
<summary>:green_circle: Check that the 'Wazuh password' input does not appear in the deploy new agent section.</summary>

Chrome - :green_circle:

image
image

</details>

<details>
<summary>:green_circle: Control that depending on whether the switch is activated or not the hidden password is shown with **** or the previously defined password is shown.</summary>

Chrome - :green_circle:

image
image

</details>

<details>
<summary>:green_circle: Try to choose HP, Solaris or Alpine, check that the variable WAZUH_REGISTRATION_PASSWORD='hello' does not appear in the install command and that the 'show password' switch does not appear either.</summary>

Chrome - :green_circle:

image
image
image

</details>

<details>
<summary>:green_circle: Check that the 'Wazuh password' entry appears in the deploy new agent section and that you can enter a password without having selected an os yet.</summary>

Chrome - :green_circle:

image


</details>

<details>
<summary>:green_circle: Check that depending on whether the switch is activated or not the hidden password is shown with **** or the password you typed in is shown</summary>

Chrome - :green_circle:

image
image

</details>

<details>
<summary>:green_circle: Choose some operating system other than hp, alpine or solaris put a password, check that the hide password switch works fine</summary>

Chrome - :green_circle:

image
image

</details>

<details>
<summary>:green_circle: Choose some operating system other than HP, Alpine or Solaris set a password, check that the password hiding switch works fine, now choose HP, Solaris or Alpine check that the ui is not broken.</summary>

Chrome - :green_circle:

image
image
image
image

</details>

<details>
<summary>:black_circle: Try choosing hp, solaris or alpine, the password input and the switch should not appear.</summary>

Chrome - :black_circle:

image
image
image

</details>

**Pull request merged**
