### PR TITLE
Fix Alerts Summary table truncated results

### LINKED ISSUE #5130: Alerts Summary table results truncated
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.4   | 7.x     | 4xxx | Basic, ODFE, Xpack |

| Browser |
| ------- |
| Chrome, Firefox, Safari, etc|

**Description**
There's a problem in the Alerts Summary PDF report. The results are truncated, there seems to be a problem in the indexer query result parser.

**Preconditions**
1. Have alerts

**Steps to reproduce**
1. Navigate to a module Dashboard
2. Click on Generate Report button
3. Download the PDF report and validate the results

**Screenshots**
image

### PR DESCRIPTION
**Pull request by asteriscos**
### Description
Team,

this PR fixes the query result of the PDF report _Alerts Summary Table_ to avoid truncating the number of rows. The parsing algorithm wasn't iterating all the bucket combinations, therefore it returned only the first combination of buckets. Now it iterates al possible combinations of the aggregation buckets and returns all possible results.

Note: We also found server-side functions truncate and sort indexer queries. The issue is described in the issue https://github.com/wazuh/wazuh-kibana-app/issues/5134
 
### Issues Resolved
Closes #5130 

### Evidence
image

### Test

- Generate a report of each module with and without a pinned agent.
  - The rendered Alerts Summary table should be consistent with the rest of the visualizations and the available alerts in the reported Module Dashboard
- Setup the Allow agents restriction filter and verify it applies to the report table.

#### Check allowed Agents

| Module | Allowed agents filtered |
| --- |  --- |
| Security events | :black_circle: |

#### Security Information Management

| Module | With pinned agent | Without agent | 
| --- |  --- | --- |
| Security events | :black_circle: | :black_circle: |
| Integrity monitoring | :black_circle: | :black_circle: |
| Office 365 | :black_circle: | :black_circle: |
| Amazon AWS | :black_circle: | :black_circle: |
| Google Cloud Platform | :black_circle: | :black_circle: |
| GitHub | :black_circle: | :black_circle: |

#### Auditing and Policy Monitoring

| Module | With pinned agent | Without agent | 
| --- |  --- | --- |
| Policy monitoring | :black_circle: | :black_circle: |
| Security configuration assessment | :black_circle: | :black_circle: |
| System auditing | :black_circle: | :black_circle: |
| OpenSCAP | :black_circle: | :black_circle: |
| CIS-CAT | :black_circle: | :black_circle: |

#### Threat Detection and Response

| Module | With pinned agent | Without agent | 
| --- |  --- | --- |
| Vulnerabilities | :black_circle: | :black_circle: |
| MITRE ATT&CK | :black_circle: | :black_circle: |
| VirusTotal | :black_circle: | :black_circle: |
| Osquery | :black_circle: | :black_circle: |
| Docker listener | :black_circle: | :black_circle: |

#### Regulatory Compliance

| Module | With pinned agent | Without agent | 
| --- |  --- | --- | 
| PCI DSS | :black_circle: | :black_circle: |
| NIST 800-53 | :black_circle: | :black_circle: |
| GDPR | :black_circle: | :black_circle: |
| HIPAA | :black_circle: | :black_circle: |
| TSC | :black_circle: | :black_circle: |

### Check List
- [ ] All tests pass
  - [ ] `yarn test:jest`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [x] Update [CHANGELOG.md](./../CHANGELOG.md)
- [ ] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Review by yenienserrano — APPROVED** [review]
#### Security Information Management

| Module | With pinned agent | Without agent | 
| --- |  --- | --- |
| Security events | :black_circle: | :black_circle: |
| Integrity monitoring | :black_circle: | :black_circle: |
| Office 365 | :black_circle: | :black_circle: |
| Amazon AWS | :black_circle: | :black_circle: |
| Google Cloud Platform | :black_circle: | :black_circle: |
| GitHub | :black_circle: | :black_circle: |


#### Auditing and Policy Monitoring


| Module | With pinned agent | Without agent | 
| --- |  --- | --- |
| Policy monitoring | :black_circle: | :black_circle: |
| Security configuration assessment | :black_circle: | :black_circle: |
| System auditing | :black_circle: | :black_circle: |
| OpenSCAP | :black_circle: | :black_circle: |
| CIS-CAT | :black_circle: | :black_circle: |


#### Threat Detection and Response


| Module | With pinned agent | Without agent | 
| --- |  --- | --- |
| Vulnerabilities | :black_circle: | :black_circle: |
| MITRE ATT&CK | :black_circle: | :black_circle: |
| VirusTotal | :black_circle: | :black_circle: |
| Osquery | :black_circle: | :black_circle: |
| Docker listener | :black_circle: | :black_circle: |


#### Regulatory Compliance


| Module | With pinned agent | Without agent | 
| --- |  --- | --- | 
| PCI DSS | :black_circle: | :black_circle: |
| NIST 800-53 | :black_circle: | :black_circle: |
| GDPR | :black_circle: | :black_circle: |
| HIPAA | :black_circle: | :black_circle: |
| TSC | :black_circle: | :black_circle: |

**Comment by Tostti** [comment]
#### Security Information Management

| Module | With pinned agent | Without agent | 
| --- |  --- | --- |
| Security events | :green_circle: | :green_circle: |
| Integrity monitoring | :green_circle: | :green_circle: |
| Office 365 |  :white_circle: | :green_circle: |
| Amazon AWS |  :green_circle: | :green_circle: |
| Google Cloud Platform | :green_circle: | :green_circle: |
| GitHub | :green_circle: | :green_circle: |


#### Auditing and Policy Monitoring


| Module | With pinned agent | Without agent | 
| --- |  --- | --- |
| Policy monitoring | :green_circle: | :green_circle: |
| Security configuration assessment | :white_circle: | :white_circle: |
| System auditing |  :green_circle: | :green_circle: |
| OpenSCAP |  :green_circle: | :green_circle: |
| CIS-CAT |  :green_circle: | :green_circle: |


#### Threat Detection and Response


| Module | With pinned agent | Without agent | 
| --- |  --- | --- |
| Vulnerabilities | :white_circle: | :white_circle: |
| MITRE ATT&CK |  :green_circle: | :green_circle: |
| VirusTotal |  :green_circle: | :green_circle: |
| Osquery |  :green_circle: | :green_circle: |
| Docker listener | :green_circle: | :green_circle: |


#### Regulatory Compliance


| Module | With pinned agent | Without agent | 
| --- |  --- | --- | 
| PCI DSS |  :green_circle: | :green_circle: |
| NIST 800-53 |  :green_circle: | :green_circle: |
| GDPR |  :green_circle: | :green_circle: |
| HIPAA |  :green_circle: | :green_circle: |
| TSC |  :green_circle: | :green_circle: |

**Review by Tostti — APPROVED** [review]
TEST:✔️
CR:✔️

LGTM

**Comment by asteriscos** [comment]
## Important
I found out that the filters applied to the PDF report tables are not including the `allowed_agents` filtered when an agents RBAC policy is applied to the user.

### Allowed Agents applied to the visualizations
Screenshot from 2023-01-18 11-59-30

### Segregation of the Allowed Agents filter in the server-side controller
Screenshot from 2023-01-18 12-38-49

Screenshot from 2023-01-18 12-39-27

### Final query filters
Screenshot from 2023-01-18 12-40-14

This mus be fixed in this PR

**Comment by asteriscos** [comment]
### Added allowed_agents filter to the following server-side queries

#### Audit requests:
- getTop3AgentsSudoNonSuccessful
- getTop3AgentsFailedSyscalls
- getTopFailedSyscalls

#### GDPR requests:
- topGDPRRequirements
- getRulesByRequirement

#### Overview requests:
- topLevel15

#### PCI requests:
- topPCIRequirements
- getRulesByRequirement

#### Rootcheck requests:
- top5RootkitsDetected
- agentsWithHiddenPids
- agentsWithHiddenPorts

#### Alerts Summary tables:
- alerts summary tables

#### Syscheck requests:
- top3agents
- top3Rules
- lastTenDeletedFiles
- lastTenModifiedFiles

#### TSC requests:
- topTSCRequirements
- getRulesByRequirement

#### Vulnerability requests:
- topAgentCount
- topCVECount
- uniqueSeverityCount
- topPackages
- topPackagesWithCVE

These requests need to be included in the tests, with the `allowed_agents` policy and without it.
Each module PDF report data consistency must be checked.

**Comment by Desvelao** [comment]
| Module | With pinned agent | Without agent | Allowed agents with pinned agent | Allowed agent without pinned agent |
| --- |  --- | --- | --- | --- |
| Security events | :black_circle: | :black_circle: | :black_circle: | :black_circle: |
| Integrity monitoring | :black_circle: | :black_circle: | :black_circle: | :black_circle: |
| Office 365 | :black_circle: | :black_circle: | :black_circle: | :black_circle: |
| Amazon AWS | :black_circle: | :black_circle: | :black_circle: | :black_circle: |
| Google Cloud Platform | :black_circle: | :black_circle: | :black_circle: | :black_circle: |
| GitHub | :black_circle: | :black_circle: | :black_circle: | :black_circle: |
| Policy monitoring | :black_circle: | :black_circle: | :black_circle: | :black_circle: |
| Security configuration assessment | :black_circle: | :black_circle: | :black_circle: | :black_circle: |
| System auditing | :black_circle: | :black_circle: | :black_circle: | :black_circle: |
| OpenSCAP | :black_circle: | :black_circle: | :black_circle: | :black_circle: |
| CIS-CAT | :black_circle: | :black_circle: | :black_circle: | :black_circle: |
| Vulnerabilities | :black_circle: | :black_circle: | :black_circle: | :black_circle: |
| MITRE ATT&CK | :black_circle: | :black_circle: | :black_circle: | :black_circle: |
| VirusTotal | :black_circle: | :black_circle: | :black_circle: | :black_circle: |
| Osquery | :black_circle: | :black_circle: | :black_circle: | :black_circle: |
| Docker listener | :black_circle: | :black_circle: | :black_circle: | :black_circle: |
| PCI DSS | :black_circle: | :black_circle: | :black_circle: | :black_circle: |
| NIST 800-53 | :black_circle: | :black_circle: | :black_circle: | :black_circle: |
| GDPR | :black_circle: | :black_circle: | :black_circle: | :black_circle: |
| HIPAA | :black_circle: | :black_circle: | :black_circle: | :black_circle: |
| TSC | :black_circle: | :black_circle: | :black_circle: | :black_circle: |

**Comment by Desvelao** [comment]
I was researching the problem with the tests. There are some tests failing that are related to the checking the md5 of PDF reports.

I think the problem is the note for the allowed agents is added when is not the use case:
image


@asteriscos, could you review it?

**Comment by Tostti** [comment]
Tests

| Module | With pinned agent | Without agent | Allowed agents with pinned agent | Allowed agent without pinned agent |
| --- |  --- | --- | --- | --- |
| Security events | :green_circle: | :green_circle: | :green_circle: | :green_circle: |
| Integrity monitoring | :green_circle: | :green_circle: | :green_circle: | :green_circle: |
| Office 365 | :white_circle: | :green_circle: | :white_circle: | :green_circle: |
| Amazon AWS | :green_circle: | :green_circle: | :green_circle: | :green_circle: |
| Google Cloud Platform | :green_circle: | :green_circle: | :green_circle: | :green_circle: |
| GitHub | :green_circle: | :green_circle: | :green_circle: | :green_circle: |
| Policy monitoring | :green_circle: | :green_circle: | :green_circle: | :green_circle: |
| Security configuration assessment | :white_circle: | :white_circle: | :white_circle: | :white_circle: |
| System auditing | :green_circle: | :green_circle: | :green_circle: | :green_circle: |
| OpenSCAP | :green_circle: | :green_circle: | :green_circle: | :green_circle: |
| CIS-CAT | :green_circle: | :green_circle: | :green_circle: | :green_circle: |
| Vulnerabilities | :white_circle: | :white_circle: | :white_circle: | :white_circle: |
| MITRE ATT&CK | :green_circle: | :green_circle: | :green_circle: | :green_circle: |
| VirusTotal | :green_circle: | :green_circle: | :green_circle: | :green_circle: |
| Osquery | :green_circle: | :green_circle: | :green_circle: | :green_circle: |
| Docker listener | :green_circle: | :green_circle: | :green_circle: | :green_circle: |
| PCI DSS | :green_circle: | :green_circle: | :green_circle: | :green_circle: |
| NIST 800-53 | :green_circle: | :green_circle: | :green_circle: | :green_circle: |
| GDPR | :green_circle: | :green_circle: | :green_circle: | :green_circle: |
| HIPAA | :green_circle: | :green_circle: | :green_circle: | :green_circle: |
| TSC | :green_circle: | :red_circle: | :green_circle: | :red_circle: |


# :red_circle: TSC
<details>

When an agent is pinned, it works as expected and in `Alerts summary` only shows the alerts for that agent. However, if no agent is pinnned, it only shows alerts for one agent. 
In my tests I was able to pin each agent individually and see the corresponding alerts, but without any agent pinned, I always see only the alerts for one of the agents.

## Evidence
### Agents
imagen

### Without pinned agents, 9 pages and only showing agent 002 (4.4-2)
imagen
imagen

### With agent 001 pinned, 9 pages and only showing agent 001 (4.4-3)
imagen
imagen

### With agent 002 pinned, 9 pages and only showing agent 002 (4.4-2)
imagen
imagen

### With agent 003 pinned , 9 pages and only showing agent 003 (4.4)
imagen
imagen

</details>

**Review by Desvelao — APPROVED** [review]
**review**:

code :green_circle: 
test :green_circle: 

I checked when the allowed agents should appear and it is working as expected. I verified the next cases:

| case | result |
| --- | --- |
| With pinned agent | :green_circle: |
| Without pinned agent | :green_circle: |
| With pinned agent and allowed agents | :green_circle: |
| Without pinned agent and allowed agents | :green_circle: |

**Review by Tostti — APPROVED** [review]
Checked when the allowed agents should appear and it is working as expected. Verified the next cases:

| case | result |
| --- | --- |
| With pinned agent | :green_circle: |
| Without pinned agent | :green_circle: |
| With pinned agent and allowed agents | :green_circle: |
| Without pinned agent and allowed agents | :green_circle: |

TEST:✔️
CR:✔️

LGTM

**Pull request merged**
