### PR TITLE
Error in management configuration

### LINKED ISSUE #3553: Error in /Management/Configuration when disabled option of cluster is "yes"
Error in /Management/Configuration when setting the disabled option to yes in ossec.conf

### PR DESCRIPTION
**Pull request by CPAlejandro**
Hi guys,

In this PR we have fixed a bug in /Management/Configuration by setting the disabled option of cluster to yes in `ossec.conf`

Close #3553

### CODE REVIEW

**Review by Desvelao — CHANGES_REQUESTED** [review]
**nitpick**: Add an entry to the changelog

**Review by Desvelao — APPROVED** [review]
**review**:
Code Review ✅

**Review by Machi3mfl — APPROVED** [review]
CR ✅

**Review by mpRegalado — APPROVED** [review]
Testing: LGTM :heavy_check_mark:

**Pull request merged**
