### PR TITLE
Fixed Group Configuration and Management configuration error after trying to going back after you save

### LINKED ISSUE #3671: Group Configuration and Management configuration error after trying to going back after you save
@CPAlejandro commented on [Tue Nov 02 2021](https://github.com/wazuh/wazuh-dashboard/issues/78)

When in any of these settings you try to go back after saving, the question appears if you want to save when it should already be saved.
https://images.zenhubusercontent.com/375074140/b853d2c8-a48c-4851-a915-83a6f8ff6c29/simplescreenrecorder_2021_11_02_10_10_19.mp4

### PR DESCRIPTION
**Pull request by CPAlejandro**
Hi guys,
With this PR we solve the error when we modify the management configuration or of some group, we save and we give the back button, before it told us that we had not saved, when we had done it

To test it:
- Go to Management/Configuration edit the file, save and try to go back with the button, it doesn't have to ask you about unsaved changes
- Same as before but in Groups/Configuration of one of them

Closes #3671 and first problem of [this comment](https://github.com/wazuh/wazuh-kibana-app/issues/3310#issuecomment-954792529)

### CODE REVIEW

**Review by Desvelao — APPROVED** [review]
LGTM!

**Comment by asteriscos** [comment]
CR: :heavy_check_mark: 
Test: :x: 

There's an odd behavior when in:

1. _Security_ -> _Users_ 
2. and clicking a user to see the details
3. then clicking again in the same spot to close the flyout
4. the unsaved changes warning pops up

Peek 2021-11-02 11-46

**Review by AlexRuiz7 — APPROVED** [review]
CR: ✔️ 
Test: ✔️

**Review by asteriscos — APPROVED** [review]
Test: :heavy_check_mark: 
CR: :heavy_check_mark:

**Review by AlexRuiz7 — APPROVED** [review]
CR: ✔️ 
Test: ✔️

**Pull request merged**
