### PR TITLE
Agents section performance improvements

### LINKED ISSUE #3623: Time-consuming Agents section
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.3.x   | 7.x     | 4xxx | Basic, ODFE, Xpack |

**Description**
The `Agents` section for the app can take too much time to load and render some elements. This is due to the requests related to Elasticsearch when the selected app time filter involves numerous documents or the Elasticsearch response is slow. The `Agents` section should be fast because it is frequently visited.

**Tasks**
- [ ] Research about how to enhance the performance. Some possible solutions:
  - Limit the time filter range to a specific value and doesn't depend on the app selected time filter
  - Move the related UI elements to another view (`Evolution` visualization and `Most agent active` stat)
  - Add a time picker
- [ ] Apply the better solution

**Acceptance criteria**
- The view should be fast and not be affected by environments with numerous documents in its indices.

### PR DESCRIPTION
**Pull request by asteriscos**
# Description

This PR optimizes the number of requests Agents Overview makes and it also avoids a few serialization of requests to allow asynchronous components start up.

## Results

As a result of these changes the section has improved significantly the init loading time.

Before the changes:
image

After the changes:
image

Closes #3623 

## Loading experience

This PR includes a change to make each card and KPI have independent loading indicator to make information available as soon as possible, instead of waiting every dashboard request response.

Peek 2022-08-01 19-17

There's a known issue with the Evolution loading indicator: there's a shared loading state which makes the Agents Evolution loading icon flicker.

### CODE REVIEW

**Review by Mayons95 — APPROVED** [review]

**Comment by Mayons95** [comment]
TR: :heavy_check_mark: 
https://user-images.githubusercontent.com/104914131/188895974-f1456634-c301-4872-9ddb-faacd70a499f.mp4

**Comment by asteriscos** [comment]
> TR: heavy_check_mark
> 
>  Screencast.from.07-09-22.10.50.14.webm 
> Comment: We detected a wrong label on synced agent percentage. Screenshot from 2022-09-07 10-51-50 C.C @asteriscos

Good catch!
I added the new `synced agents` initial value as well in [this commit](https://github.com/wazuh/wazuh-kibana-app/pull/4363/commits/62a8f60b0c5ac6341f4dcf9995d76b40f485ba7d).
Screenshot from 2022-09-07 16-54-29

**Comment by Mayons95** [comment]
Commit Test OK! 
I attached the video here
[Screencast from 07-09-22 12:07:48.webm](https://user-images.githubusercontent.com/104914131/188913526-e9802383-4489-4ea2-96fa-be58a554b754.webm)
C.C @asteriscos @AlexRuiz7

**Review by yenienserrano — APPROVED** [review]
LGTM!

https://user-images.githubusercontent.com/63758389/189111229-8872988d-e329-455f-9430-b248dc7aa1de.mp4

**Pull request merged**
