### PR TITLE
Fix deploy new agent section

### LINKED ISSUE #4931: Fix section deploy new agent, add alpine agent
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.4   | 7.x     | 4xxx | Basic, ODFE, Xpack |

We need to include the latest information about supported OSs and commands.

- Simplify OS versions, combining them by package
- Enable the preselection when there is a single option
- Hide less popular OSs under a Show less button.
- We need to incorporate the new Alpine information into the deploy agent page
- Review packages URLs and test them all

### PR DESCRIPTION
**Pull request by chantal-kelm**
### Description

- Fixed the way macOS versions and architectures were displayed.
- Fixed the way agents were displayed.
- Fixed the way Ubuntu versions were displayed.
- Added extra steps message and new command for Windows XP and Windows Server 2008
- Added Alpine agent with all its steps.
- Windows command fixed
- CI/CD has [updated](https://github.com/wazuh/wazuh-packages/issues/1625#issuecomment-1357808349) all installation commands, we have also updated them in our code.
 
### Issues Resolved

#4931 

### Manual Backports

[4.4-2.3-wzd](https://github.com/wazuh/wazuh-kibana-app/pull/4974)
[4.4-7.16 ](https://github.com/wazuh/wazuh-kibana-app/pull/4979)

### Evidence

https://user-images.githubusercontent.com/99441266/204812848-a0be5f6d-15c3-4a2e-b893-a4b0f0016ec4.mov

### Steps to test

* Click on agents
* Click on deploy new agent
* Check that the information shown is correct.
* Check that the information shown for the windows agent is the one shown in this [comment](https://github.com/wazuh/wazuh-packages/issues/1625#issuecomment-1320226193)
* Check that the information shown for the alpine agent is the same as the one shown in this [comment](https://github.com/wazuh/wazuh-packages/issues/1625#issuecomment-1328980215)

### Check List
- [x] All tests pass
  - [x] `yarn test:jest`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [x] Update [CHANGELOG.md](./../CHANGELOG.md)
- [x] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Review by Mayons95 — APPROVED** [review]
TR: :heavy_check_mark: 
LGTM

Screenshot from 2022-12-15 10-35-42

**Comment by Desvelao** [comment]
**thought**: I thought we are working on a refactor to do the deploy guides extensible. Continuing the previous approach, now with more operating systems, messages, etc... add more technical debt. I think we should not merge the related PR and we should work on the refactor instead.

**Review by Tostti — APPROVED** [review]
CR: ✔️
TEST: ✔️

image

LGTM

**Review by Tostti — APPROVED** [review]

**Review by asteriscos — APPROVED** [review]
CR: :heavy_check_mark: 
Test: :heavy_check_mark: 

image

**Pull request merged**
