### PR TITLE
[PR] Add agent synchronization statistics

### LINKED ISSUE #3402: Add agent synchronization statistics
| Wazuh version | Component | Install type | Install method   | Platform   |
| ------------- | --------- | ------------ | ---------------- | ---------- |
| 4.4.0      | App / API / Core | - |  - | -  |

Hello Team,

## Summary
It could be very useful to have agent configuration synchronization statistics in percentage (and it could be in numbers also). 
Currently, we have to check agent by agent if they are synchronized.
In large environments, it is more useful having that information in the same visualization.

## Suggested changes
More precisely, I am looking for:
1. To have the percentage of agents that have their configuration synchronized all in one visualization, in the Agents tab.
2. Add in the agent's list, the status of synchronization of each agent.
3. Add the ability to filter the agents by synchronization status.

Thank you in advance.

### Agents config synchronization percentage

We will add a widget below `Agents coverage` in the `Agents preview` page. This widget will contain the value of the percentage of agents which has its configuration synchronized with the Wazuh manager over the total active agents.

The value represents the synchronization and not the application of such configuration. It might happen that the configuration is synchronized but not applied.

The percentage will always be related to the total amount of active agents at the time of visualization and not a group or a filtered set of agents.

There might be a latency between the time a user sends a new configuration to be applied and the update of the indicator, which will depend on the load of the system and the number of agents. It might, at first, decrease its value as the agents are being recognized as being unsynchronized to later raise as the agents are being synchronized.

The new indicator value won't be available for alerting, indexing or building historical reports.

There won't be a clickable area in the widget to perform additional actions in the view, following the design of the `Agents coverage` widget instead of the `Active `widget.

The widget will use an API call to the [agent's summary API](https://documentation.wazuh.com/current/user-manual/api/reference.html#operation/api.controllers.agent_controller.get_agent_summary_status) method to obtain its value. Because this call is already made to load the `Agents preview`, no further calls need to be done besides what it is already present.

### Agent list table

The table in the same `Agents preview` page will have a new field "Configuration state" which will show if the agent has its configuration synchronized or not,  similarly to the way it is show in the agent configuration panel.

This field must behave like the other fields in the table, and should support the filter and visibility rules which are applicable to the other fields of the table.

The information of the table is obtained from the API call to [list agents](https://documentation.wazuh.com/current/user-manual/api/reference.html#operation/api.controllers.agent_controller.get_agents), which already being made in the `Agents preview`. This call will include a new field indicating if the configuration is synchronized or not.

### Additional tasks

We will use the issue https://github.com/wazuh/wazuh/issues/9334 to follow up the API implementation.

### PR DESCRIPTION
**Pull request by asteriscos**
Hi team,

this adds agent synchronization statistics to the Agents Summary view.  Also includes agents `Pending` status to the doughnut chart.

Closes #3402 #3836 

<details>
<summary>Screenshots</summary>

#### Modules Overview
Screenshot from 2022-09-01 18-01-46

#### Agents Overview
Screenshot from 2022-09-01 18-01-58

#### Management Status
Screenshot from 2022-09-01 18-02-40

</details>

### CODE REVIEW

**Comment by yenienserrano** [comment]
the endpoint response type has been modified GET /agents/summary/status so the responses of the views using that endpoint have been fixed.

**Test:**

1. Navigate to the following views:
         - Overview
         - Management/Status 
         - Agents
2. The number of agents in the different states should be displayed. 
3. in the agent module in the details part there should appear Agents synced and in the table there should be a Synchronized column.

**Review by chantal-kelm — APPROVED** [review]
CR: :heavy_check_mark:
Test: :heavy_check_mark: 

image
Screenshot from 2022-07-14 12-09-35
Screenshot from 2022-07-14 12-09-48
Screenshot from 2022-07-14 12-10-00

**Review by chantal-kelm — APPROVED** [review]
CR: :heavy_check_mark:
Test: :heavy_check_mark: 

Screenshot from 2022-07-14 12-09-35
Screenshot from 2022-07-14 12-09-48
Screenshot from 2022-07-14 12-10-00

**Comment by Mayons95** [comment]
TR :heavy_check_mark: 
LGTM ! 
Test OK 
Evidence Attached
Screenshot from 2022-09-01 14-23-33
Screenshot from 2022-09-01 14-23-24
Screenshot from 2022-09-01 14-23-15
Screenshot from 2022-09-01 14-21-23
Screenshot from 2022-09-01 14-21-10
Screenshot from 2022-09-01 14-20-59

**Review by Mayons95 — APPROVED** [review]
TR :heavy_check_mark:

**Review by AlexRuiz7 — APPROVED** [review]
- Code Review: ✔️ 
- Test: ✔️

**Pull request merged**
