### PR TITLE
Add install / update examples without having sudo installed

### PR DESCRIPTION
**Pull request by iasdeoupxe**
Not every system has sudo installed / available so mention a way without sudo as well.

### CODE REVIEW

**Comment by jesusgn90** [comment]
Thanks @iasdeoupxe, let me try those commands one more time, then I'll merge this PR.

**Comment by iasdeoupxe** [comment]
Thanks. I don't have a Red Hat based OS at hand but was able to test this successfully on my Debian 9 installation where i don't have sudo available / installed.

Once this PR is accepted it probably needs a similar PR like https://github.com/wazuh/wazuh-documentation/pull/600 to the documentation as well?

**Comment by jesusgn90** [comment]
This one has been merged, let me know if you are planning to make another one for the documentation, otherwise, we can do it by ourselves.

Thanks!

**Comment by iasdeoupxe** [comment]
@jesusgn90 Thanks for merging. The follow-up PR for the documentation part can be found in https://github.com/wazuh/wazuh-documentation/pull/952

**Pull request merged**
