### PR TITLE
Create reusable card for operating systems

### LINKED ISSUE #5435: [Redesign add agent] Create reusable card for operating systems
## Description

This issue is part of the redesign of the deploy a new agent section. These cards will be reusable, they will show the operating system and architecture and based on that selection made by the user we will manage what data to show to the user in other steps.

Captura de pantalla 2023-05-11 a la(s) 15 29 28

**Updated design:**

image

## Tasks
The steps that have to be completed in order to close the issue.

- [x] Creation of reusable card component

- [x] Display information inside the card

- [x] Create a checkbox component with its respective logic

- [x] Applying styles

## Additional information
Add here any additional information relevant to the issue or that will help to close it: chunks of code, logs, additional error messages, related issues and so on.

### PR DESCRIPTION
**Pull request by chantal-kelm**
### Description

This PR is part of the redesign of the deploy a new agent section. These cards will be reusable, they will show the operating system and architecture and based on that selection made by the user we will manage what data to show to the user in other steps.
 
### Issues Resolved

#5435

### Evidence

image

### Test

Verify that everything is displayed as in the [design](https://www.figma.com/file/AUe4qvDcvo8hOw0tgeTASk/Deploy?type=design&node-id=266-68669&t=Tiwlk9Ip3YIIC0tt-0)

### Check List
- [ ] All tests pass
  - [ ] `yarn test:jest`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [ ] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Review by Tostti — CHANGES_REQUESTED** [review]
# Wazuh dashboard

Legend:
:black_circle:: none
:green_circle:: pass
:yellow_circle:: warning
:red_circle:: fail
:white_circle:: not applicable

## UI

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| Verify that everything is displayed as in the design |  :red_circle: | :red_circle: | :black_circle: |

[Design](https://www.figma.com/file/AUe4qvDcvo8hOw0tgeTASk/Deploy?type=design&node-id=266-68669&t=Tiwlk9Ip3YIIC0tt-0)

**Details**
<details>
<summary>:red_circle: Verify that everything is displayed as in the design</summary>

Chrome - :red_circle:
The font is different as the design's. 

imagen

Firefox - :yellow_circle:

Is it suppossed that only the cards are shown? 

imagen


Safari - :black_circle:

</details>

**Review by Machi3mfl — CHANGES_REQUESTED** [review]
Remove all the `.DS_Store` files

**Review by Machi3mfl — CHANGES_REQUESTED** [review]
Check the server console

image

**Review by Machi3mfl — CHANGES_REQUESTED** [review]
OS checkbox not working,

https://github.com/wazuh/wazuh-kibana-app/assets/6089438/ffdade09-bbdb-4117-92b4-9c3b03b80a89

**Review by Machi3mfl — APPROVED** [review]

**Pull request merged**
