### PR TITLE
Features/fix error timestamp security events

### LINKED ISSUE #2785: The alerts time does not match in the Security event dashboard and events tabs
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| v4.0.3  | 7.9.1  | 40010|

**Description**

The alerts time does not match in the Security event dashboard and events tabs.

**Steps to reproduce**

1. Go to `Wazuh >  Modules > Security events > Dashboard`
2. Check the time of the alerts
3. Go to `Wazuh >  Modules > Security events > Events`
4. Check the time of the alerts
5. The time does not match

**Screenshots**

image

image

**Additional context**

The same issue happens in the **4.0.4** version. `Browser timezone` is used for date formatting.

### PR DESCRIPTION
**Pull request by CPAlejandro**
Hi team, we resolve:
-Fix bug that show an hour before in /security-events/dashboard.It was solved applying Timeservice.offset before.
Closes #2785

### CODE REVIEW

**Comment by Desvelao** [comment]
I tested the PR and it's working
image
image

**Review by Desvelao — APPROVED** [review]
LGTM!

**Review by gabiwassan — APPROVED** [review]
LGTM

**Review by frankeros — APPROVED** [review]
LGTM!

**Comment by lucio2047** [comment]
Hi everyone, 
I have a doubt: I try to apply the following recommendation "-Fix bug that show an hour before in /security-events/dashboard.It was solved applying Timeservice.offset before.
Closes #2785" indicated by @CPAlejandro , but how can I do it? Which file do I need to edit in order to configure Timeservice.offset?

Thank you very much.

**Comment by frankeros** [comment]
Hi @lucio2047, this PR will be included in the next release 4.0.4  for Kibana 7.10.0

**Comment by lucio2047** [comment]
Hi Franco,

Thank you very much. I´m sorry, I`m new about Wazuh. What does it mean PR?
Programa Release?

By following the several respondes, I mean there is a bug about timestamp
in release 4.0.3 which it will be solved with the next release 4.0.4, ok?

If the response to my prior question is YES, how can I update my current
release 4.0.3 to 4.0.4?, is it automatic? Do I need execute yum installa
wazup update?

Thank you very much!

**Comment by frankeros** [comment]
PR means Pull Request, I mean this fix will be included in the next release.
You could follow this [doc](https://documentation.wazuh.com/4.0/installation-guide/index.html) to upgrade to a new version. But the release with this fix is not done yet.

**Comment by frankeros** [comment]
You need to upgrade Wazuh-Manager, Wazuh-Agent(s), and the Wazuh Kibana plugin, the rest of the components should be the same.
For managers and agents, you could try to stop the services, update the repositories, install the latest version (4.0.4), then restart the services. More info [here](https://documentation.wazuh.com/4.0/installation-guide/open-distro/all-in-one-deployment/all_in_one.html#installing-the-wazuh-manager)
For the Kibana plugin, you should run 
```
sudo -u kibana /usr/share/kibana/bin/kibana-plugin remove wazuh
```
then repeat step 4 of the [doc](https://documentation.wazuh.com/4.0/installation-guide/open-distro/all-in-one-deployment/all_in_one.html#installing-kibana) and restart Kibana service

**Comment by lucio2047** [comment]
Thank you Franco. I`d try to upgrade.

My final questions: when is the new release coming? in December?,  at the
end of November?

Thank you again!

**Comment by lucio2047** [comment]
Hi Franco, how are you?

I'm a little confuse about new release that solves the problem reported
under #2797

Right now the last version is Wazuh v4.0.4 - Kibana v7.9.3. As you
mentioned, #2797 will be fixed  with the next release 4.0.4 for Kibana
7.10.0. Well, How could I  notice about the new release? I am following the
Wazuh Twitter account. What do you think? Is there another way to notice
new releases?
<https://github.com/wazuh/wazuh-kibana-app/releases/tag/v4.0.4-7.9.3>

Thanks in advance.

**Comment by frankeros** [comment]
HI @lucio2047, the release 4.0.4 7.10.0 is unofficial for now. The official release will be 4.1.0-7.10.0 and it will be ready soon.
You could watch the repo activity by watching the from Github
image

Thanks for your patience.
Best

**Pull request merged**
