### PR TITLE
[Backport 4.4-2.4-wzd] Add mismatch error message when method not allowed

### PR DESCRIPTION
**Pull request by Tostti**
Backport from https://github.com/wazuh/wazuh-kibana-app/pull/4964

### CODE REVIEW

**Comment by Tostti** [comment]
Tested:
image

**Review by Machi3mfl — APPROVED** [review]
CR: :heavy_check_mark: 
Test: :heavy_check_mark: 

image

**Review by yenienserrano — APPROVED** [review]
LGTM 

image

**Review by Desvelao — APPROVED** [review]
**review**

**review**

Code :green_circle: 

Test

| Scenario | Result |
| --- | --- |
| 1 | :green_circle: |

<details>
  <summary>Scenario 1 :green_circle: </summary>
  
An API in 4.3.x  
image

<details>

**Pull request merged**
