### PR TITLE
Add Alerts summary and Last alerts definitions in PDF reports

### LINKED ISSUE #5044: `Alerts summary` data is missing in the reports of some modules
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.x   | 7.x     | 4xxx | Basic, ODFE, Xpack |

| Browser |
| ------- |
| Chrome, Firefox, Safari, etc|

**Description**
In a side test, I found that the PCI DSS module has no `Alerts summary` table in the module report.

We changed the addition of this data to the report in this PR: https://github.com/wazuh/wazuh-kibana-app/pull/4376.

We should ensure that the generation of PDF reports includes at least the previous `Alerts summary` table.

In my opinion, we should ensure that all the modules that must have this data, it appears in the report.

**Preconditions**
1. 

**Steps to reproduce**
1. Navigate to '...'

**Expected Result**
1. 

**Actual Result**
1. 

**Screenshots**

**Additional context**
Add any other context about the problem here. Here you can paste log entries too or any other useful information that may help with the issue.

### PR DESCRIPTION
**Pull request by asteriscos**
### Description
This PR adds missing Alerts summary and Last alerts tables definitions to PDF reports. It also fixes a missing field issue when a particular field doesn't have a value.

### Issues Resolved
Closes #5044 
 
### Evidence

PCI DSS Agent PDF report
Screenshot from 2022-12-30 18-16-18

Osquery Agent PDF report
Screenshot from 2022-12-30 18-14-21

### Test
Generate a report of each module with and without a pinned agent.
Pending definition of each test.

#### Security Information Management

| Module | With pinned agent | Without agent | 
| --- |  --- | --- |
| Security events | :black_circle: | :black_circle: |
| Integrity monitoring | :black_circle: | :black_circle: |
| Office 365 | :black_circle: | :black_circle: |
| Amazon AWS | :black_circle: | :black_circle: |
| Google Cloud Platform | :black_circle: | :black_circle: |
| GitHub | :black_circle: | :black_circle: |

#### Auditing and Policy Monitoring

| Module | With pinned agent | Without agent | 
| --- |  --- | --- |
| Policy monitoring | :black_circle: | :black_circle: |
| Security configuration assessment | :black_circle: | :black_circle: |
| System auditing | :black_circle: | :black_circle: |
| OpenSCAP | :black_circle: | :black_circle: |
| CIS-CAT | :black_circle: | :black_circle: |

#### Threat Detection and Response

| Module | With pinned agent | Without agent | 
| --- |  --- | --- |
| Vulnerabilities | :black_circle: | :black_circle: |
| MITRE ATT&CK | :black_circle: | :black_circle: |
| VirusTotal | :black_circle: | :black_circle: |
| Osquery | :black_circle: | :black_circle: |
| Docker listener | :black_circle: | :black_circle: |

#### Regulatory Compliance

| Module | With pinned agent | Without agent | 
| --- |  --- | --- | 
| PCI DSS | :black_circle: | :black_circle: |
| NIST 800-53 | :black_circle: | :black_circle: |
| GDPR | :black_circle: | :black_circle: |
| HIPAA | :black_circle: | :black_circle: |
| TSC | :black_circle: | :black_circle: |

### Check List
- [x] All tests pass
  - [x] `yarn test:jest`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [x] Update [CHANGELOG.md](./../CHANGELOG.md)
- [x] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Comment by asteriscos** [comment]
#### Security Information Management

| Module | With pinned agent | Without agent | 
| --- |  --- | --- |
| Security events | :black_circle: | :black_circle: |
| Integrity monitoring | :black_circle: | :black_circle: |
| Office 365 | :black_circle: | :black_circle: |
| Amazon AWS | :black_circle: | :black_circle: |
| Google Cloud Platform | :black_circle: | :black_circle: |
| GitHub | :black_circle: | :black_circle: |


#### Auditing and Policy Monitoring


| Module | With pinned agent | Without agent | 
| --- |  --- | --- |
| Policy monitoring | :black_circle: | :black_circle: |
| Security configuration assessment | :black_circle: | :black_circle: |
| System auditing | :black_circle: | :black_circle: |
| OpenSCAP | :black_circle: | :black_circle: |
| CIS-CAT | :black_circle: | :black_circle: |


#### Threat Detection and Response


| Module | With pinned agent | Without agent | 
| --- |  --- | --- |
| MITRE ATT&CK | :green_circle: | :green_circle: |
| VirusTotal | :red_circle: | :red_circle: |
| Osquery | :green_circle: | :green_circle: |
| Docker listener | :green_circle: | :green_circle: |


#### Regulatory Compliance


| Module | With pinned agent | Without agent | 
| --- |  --- | --- | 
| PCI DSS | :green_circle: | :green_circle: |
| NIST 800-53 | :green_circle: | :green_circle: |
| GDPR | :green_circle: | :green_circle: |
| HIPAA | :green_circle: | :green_circle: |
| TSC | :green_circle: | :green_circle: |

**Comment by Tostti** [comment]
### Testing that the results are the same as in 4.3.10 production version and no visualization or section is missing
#### Security Information Management

| Module | With pinned agent | Without agent | Comments 
| --- |  --- | --- |--- |
| Security events | :red_circle: | :green_circle: | With pinned agent, the `Groups summary` section is missing|
| Integrity monitoring | :green_circle: | :black_circle: | |
| Office 365 | :black_circle: | :green_circle: ||
| Amazon AWS | :black_circle: | :green_circle: ||
| Google Cloud Platform | :black_circle: | :green_circle: ||
| GitHub | :black_circle: | :green_circle: ||


#### Auditing and Policy Monitoring


| Module | With pinned agent | Without agent  | Comments 
| --- |  --- | --- |--- |
| Policy monitoring | :green_circle: | :green_circle: | |
| System auditing | :black_circle: | :green_circle: | |
| OpenSCAP | :black_circle: | :green_circle: | |
| CIS-CAT | :green_circle: | :green_circle: | |


#### Threat Detection and Response


| Module | With pinned agent | Without agent | Comments 
| --- |  --- | --- |--- |
| MITRE ATT&CK | :green_circle: | :green_circle: | |
| VirusTotal | :green_circle: | :green_circle: | |
| Osquery | :green_circle: | :green_circle: | In both cases, there is an `Alerts summary` that is not present in 4.3.10 |
| Docker listener | :black_circle: | :yellow_circle: | In 4.3.10, the `Alerts summary` section is called `Events summary` |


#### Regulatory Compliance


| Module | With pinned agent | Without agent  | Comments 
| --- |  --- | --- | --- |
| PCI DSS | :green_circle: | :green_circle: | |
| NIST 800-53 | :yellow_circle: | :green_circle: | In 4.3.10, with a pinned agent the `Last alerts` section is called `Alerts summary` |
| GDPR | :green_circle: | :green_circle: | |
| HIPAA | :yellow_circle: | :green_circle: | In 4.3.10, with a pinned agent the `Last alerts` section is called `Alerts summary` |
| TSC | :green_circle: | :green_circle: | With a pinned agent, there is an `Alerts summary` that is not present in 4.3.10 |

**Comment by asteriscos** [comment]
There's an issue in the Github module when the pinned agent state changes. The problem doesn't seem to be directly related to the PDF report generation process. 

Peek 2023-01-04 10-06

This endpoint requires the body of the request to have these properties:
`http://localhost:5601/reports/modules/github`

```
body: schema.object({
          array: schema.any(),
          browserTimezone: schema.string(),
          filters: schema.maybe(schema.any()),
          agents: schema.maybe(schema.oneOf([agentIDValidation, schema.boolean()])),
          components: schema.maybe(schema.any()),
          searchBar: schema.maybe(schema.string()),
          section: schema.maybe(schema.string()),
          tab: schema.string(),
          tables: schema.maybe(schema.any()),
          time: schema.oneOf([schema.object({
            from: schema.string(),
            to: schema.string()
          }), schema.string()]),
          indexPatternTitle: schema.string(),
          apiId: schema.string()
        }),
       ```

When the report request is made, it tries to obtain the applied filters from the visualizations:
Screenshot from 2023-01-04 10-22-11
Screenshot from 2023-01-04 10-21-41

But when the pinned agent state changes it removes all the visualizations from the array:
Screenshot from 2023-01-04 10-20-35

And it doesn't re-run the constructor to reset the properties that allow to push the visualizations to the list:
Screenshot from 2023-01-04 10-19-27
Screenshot from 2023-01-04 10-18-42

**Comment by yenienserrano** [comment]
| Module | With pinned agent | Without agent | 
| --- |  --- | --- |
| Security events | :black_circle: | :black_circle: |
| Integrity monitoring | :black_circle: | :black_circle: |
| Office 365 | :black_circle: | :black_circle: |
| Amazon AWS | :black_circle: | :black_circle: |
| Google Cloud Platform | :black_circle: | :black_circle: |
| GitHub | :black_circle: | :black_circle: |


#### Auditing and Policy Monitoring


| Module | With pinned agent | Without agent | 
| --- |  --- | --- |
| Policy monitoring | :black_circle: | :black_circle: |
| Security configuration assessment | :black_circle: | :black_circle: |
| System auditing | :black_circle: | :black_circle: |
| OpenSCAP | :black_circle: | :black_circle: |
| CIS-CAT | :black_circle: | :black_circle: |


#### Threat Detection and Response


| Module | With pinned agent | Without agent | 
| --- |  --- | --- |
| Vulnerabilities | :black_circle: | :black_circle: |
| MITRE ATT&CK | :black_circle: | :black_circle: |
| VirusTotal | :black_circle: | :black_circle: |
| Osquery | :black_circle: | :black_circle: |
| Docker listener | :black_circle: | :black_circle: |


#### Regulatory Compliance


| Module | With pinned agent | Without agent | 
| --- |  --- | --- | 
| PCI DSS | :black_circle: | :black_circle: |
| NIST 800-53 | :black_circle: | :black_circle: |
| GDPR | :black_circle: | :black_circle: |
| HIPAA | :black_circle: | :black_circle: |
| TSC | :black_circle: | :black_circle: |

**Review by yenienserrano — APPROVED** [review]
CR: ✅ 
Test: ✅

**Review by yenienserrano — DISMISSED** [review]

**Review by Tostti — DISMISSED** [review]
TEST:✔️
CR:✔️

LGTM

**Review by Tostti — APPROVED** [review]

**Review by Desvelao — APPROVED** [review]
LGTM!

**Pull request merged**
