### PR TITLE
Refactor try-catch components/add-moludes-data

### PR DESCRIPTION
**Pull request by Machi3mfl**
Hi team,
This PR implements a new strategy to catch in components/add-modules-data.

Close: #3471

### CODE REVIEW

**Review by gabiwassan — APPROVED** [review]
LGTM ! 🚀

**Review by matiasmoreno876 — APPROVED** [review]
LGTM!

**Review by pablomarga — APPROVED** [review]
LGTM!

**Comment by MauGaP** [comment]
you will need to update changelog in order to merge this one

**Pull request merged**
