### PR TITLE
Test decoders before matching rules

### PR DESCRIPTION
**Pull request by sortizowlh**
Hi team!
This PR adds a feature to check decoders and rulesets using logtest.

To test it:
1. Go to Management/Decoders
- **Given** the browser is logged in the Wazuh kibana app
- **When** the browser enters `Management/Decoders`
- **Then** Decoders Sections will be displayed

**Prerequisite 1**: command: `Apr 28 13:43:51 localhost local_decoder_example: test`

2. Test a decoder
- **Given** the browser is at Decoder section
- **When** the user navigate to `custom decoder` -> `Add new decoder file` -> `Decoder test`
- **And** the user paste **Prerequisite 1** and click in test
- **Then** Decoders Test Section will not display  an error

Related issue: #3348

### CODE REVIEW

**Review by mpRegalado — CHANGES_REQUESTED** [review]
You accidentally branched from e4399fe732ec6c8d41524ba748ea15c4baa99c8a and so the changes on the `feature/3391_office365_module_navigation` branch are included in this PR.
You should probably rebase it.

**Comment by Desvelao** [comment]
**issue**: There are changes related to the Office 365 module. We should remove these changes to the PR.

**nitpick**: Add the change to the changelog

**Review by mpRegalado — APPROVED** [review]
CR: LGTM: :heavy_check_mark:

**Comment by Desvelao** [comment]
### Changes
- Add change to the changelog

**Review by Desvelao — APPROVED** [review]
**review**:
Code Review ✅

**Comment by CPAlejandro** [comment]
Comparing the result with the verbose mode:

- **A log sample that matches a decoder but that matches no rule**

```
<decoder name="local_decoder_example">
    <program_name>local_decoder_example</program_name>
</decoder>
```

**Expected result:**

`2021/11/05 10:36:19 wazuh-testrule: INFO: Started (pid: 2391674).
Since Wazuh v4.1.0 this binary is deprecated. Use wazuh-logtest instead
wazuh-testrule: Type one log per line.
Nov  5 10:20:01 my-server local_decoder_example[12345]: this will get decoded but match no rule at all
**Phase 1: Completed pre-decoding.
       full event: 'Nov  5 10:20:01 my-server local_decoder_example[12345]: this will get decoded but match no rule at all'
       timestamp: 'Nov  5 10:20:01'
       hostname: 'my-server'
       program_name: 'local_decoder_example'
       log: 'this will get decoded but match no rule at all'
**Phase 2: Completed decoding.
       decoder: 'local_decoder_example'`
       
image


- **A log sample that matches a rule that is level 0 (which always suppresses alerts)**


- **A log sample that matches a rule that is level 1 or 2**

`<rule id="5753" level="2">
    <if_sid>5750</if_sid>
    <match>no matching cipher found</match>
    <description>sshd: could not negotiate with client, no matching cipher.</description>
  </rule>`
  
  **Expected result:**
`Starting wazuh-logtest v4.2.4
Type one log per line
Nov  5 10:20:01 my-server sshd[12345]: fatal: no matching cipher found
**Phase 1: Completed pre-decoding.
        full event: 'Nov  5 10:20:01 my-server sshd[12345]: fatal: no matching cipher found'
        timestamp: 'Nov  5 10:20:01'
        hostname: 'my-server'
        program_name: 'sshd'
**Phase 2: Completed decoding.
        name: 'sshd'
**Phase 3: Completed filtering (rules).
        id: '5753'
        level: '2'
        description: 'sshd: could not negotiate with client, no matching cipher.'
        groups: '['syslog', 'sshd']'
        firedtimes: '1'
        mail: 'False'`

image

image

**Pull request merged**
